### ISSUE TITLE
ImportError: No module named juice on Windows

### ISSUE THREAD

**Issue by adrianhall** [mkdocs/mkdocs#1112]
Platform: Windows 10
python --version: Python 2.7.12
pip --version: pip 9.0.1 from c:\python27\lib\site-packages (python 2.7)

```
> mkdocs serve
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\mkdocs.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\mkdocs\__main__.py", line 78, in <module>
    theme_choices = utils.get_theme_names()
  File "c:\python27\lib\site-packages\mkdocs\utils\__init__.py", line 409, in get_theme_names
    return get_themes().keys()
  File "c:\python27\lib\site-packages\mkdocs\utils\__init__.py", line 401, in get_themes
    for name, theme in themes.items())
  File "c:\python27\lib\site-packages\mkdocs\utils\__init__.py", line 401, in <genexpr>
    for name, theme in themes.items())
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2229, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named juice
```

I tried to install juice with 'pip install juice', but got the following:

```
Collecting sh==1.11 (from juice)
  Downloading sh-1.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\adrianha\appdata\local\temp\pip-build-avgxa_\sh\setup.py", line 4, in <module>
        import sh
      File "sh.py", line 37, in <module>
        support." % __version__)
    ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/
pypi/pbs) for windows support.
```

From C:\Python27\lib\site-packages\mkdocs\__init__.py
```
__version__ = '0.16.0'
```

**Comment by facelessuser** [comment]
Are your docs trying to build with a "juice" theme that you don't have installed?  I'm just guessing.  I don't know what juice is, but I'm not familiar with Mkdocs needing a juice module.

**Comment by adrianhall** [comment]
Me neither.  My docs use mkdocs-material, which I have installed.  Also, `mkdocs --version` causes the same error, and that isn't building anything.

**Comment by d0ugal** [comment]
I suspect at some point you tried installing the mkdocs-juice theme and it has an issue. https://pypi.python.org/pypi/mkdocs-juice

Luckily there was a nice fix for this recently and broken themes should no longer cause issues (unless you are explicitly using them in the mkdocs.yml).

Please update to 0.16.1 (released a few mins ago), and hopefully this will be resolved.
