### ISSUE TITLE
ImportError: No module named livereload

### ISSUE THREAD

**Issue by GabeHiemstra** [mkdocs/mkdocs#1150]
I have installed using "yum new mkdocs". Then I create a simple new project like this:

mkdocs new keepalive

Then when I do mkdocs serve, I get the following errors:

```
/usr/lib/python2.7/site-packages/mkdocs/cli.py:85: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/lib/python2.7/site-packages/mkdocs/cli.py:99: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/lib/python2.7/site-packages/mkdocs/cli.py:124: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/lib/python2.7/site-packages/mkdocs/cli.py:144: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/lib/python2.7/site-packages/mkdocs/cli.py:175: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/lib/python2.7/site-packages/mkdocs/cli.py:193: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
INFO    -  Building documentation...
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.14.0', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mkdocs/cli.py", line 111, in serve_command
    livereload=livereload,
  File "/usr/lib/python2.7/site-packages/mkdocs/serve.py", line 84, in serve
    _livereload(host, port, config, builder, tempdir)
  File "/usr/lib/python2.7/site-packages/mkdocs/serve.py", line 16, in _livereload
    from livereload import Server
ImportError: No module named livereload
```

**Comment by waylan** [comment]
It appears that you did not get all of the required  dependencies installed. I've never used the Yum package manager myself, so I don't know what is required to make Yum install dependencies. However if you use Python's package manager, pip, all the dependencies will be installed automatically for you:

    pip install mkdocs

You may need to install the current installation first with Yum.

**Comment by d0ugal** [comment]
I just tried on Fedora 25 (so dnf, not yum) and it installed MkDocs fine with livereload.

I suspect you are on an older fedora (or maybe centos?) and the package is perhaps broken. Where did you get it from?

**Comment by GabeHiemstra** [comment]
Thanks for the comments. I have installed mkdocs using yum. I have just looked at the transaction history and a total of 10 packages were installed (mkdocs + 9 dependencies). Livereload was not one of them. I will now try to re-install using pip.

**Comment by GabeHiemstra** [comment]
Installed using pip and everything works fine. I only had to open the port in the firewall and change the address.

**Comment by xyen8180** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\dubai\manage.py", line 25, in <module>
    main()
  File "C:\Users\Administrator\Desktop\dubai\manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Administrator\Desktop\dubai\venv\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\Administrator\Desktop\dubai\venv\lib\site-packages\django\core\management\__init__.py", line 420, in execute
    django.setup()
  File "C:\Users\Administrator\Desktop\dubai\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Administrator\Desktop\dubai\venv\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Administrator\Desktop\dubai\venv\lib\site-packages\django\apps\config.py", line 228, in create
    import_module(entry)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'livereload'


i am having this problem after pip install, installed apps and middleware

**Comment by pawamoy** [comment]
I don't see any call from MkDocs in the traceback you posted, so you're probably commenting on the wrong repository. Try on Django instead?

**Comment by xyen8180** [comment]
It's not on mcdocs I'm using my own repo I'm full stack developer and I'm highly irritated with everychange i have to force reload django template in brother with ctrl+R so i installed livereload but it's not working saying the same problem module not found

**Comment by oprypin** [comment]
There's no livereload in this repository anymore, please don't post on any random thread you find
