### ISSUE TITLE
ImportError: No module named tornado.wsgi

### ISSUE THREAD

**Issue by sergafts** [mkdocs/mkdocs#1183]
Whenever I am trying to use `mkdocs serve` I get the following:

```
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/cli.py", line 81, in serve_command
    livereload=livereload,
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/serve.py", line 83, in serve
    _livereload(host, port, config, builder, tempdir)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/serve.py", line 15, in _livereload
    from livereload import Server
  File "/usr/local/lib/python2.7/dist-packages/livereload/__init__.py", line 14, in <module>
    from .server import Server, shell
  File "/usr/local/lib/python2.7/dist-packages/livereload/server.py", line 19, in <module>
    from tornado.wsgi import WSGIContainer
ImportError: No module named tornado.wsgi
```

I tried upgrading `tornado`, `livereload` (`pip install --upgrade <>`) but the issue remains.
Versions:

```
python 2.7.3
mkdocs 0.16.2
tornado 4.4.2
livereload 2.5.1
```

**Comment by waylan** [comment]
Its working fine for me with Tornado 4.3. However, I just checked and no changes were made to tornado.wsgi between 4.3 and 4.4.2. My best guess is you have a bad install. Try uninstalling tornado and reinstalling.

**Comment by sergafts** [comment]
Reinstalled `tornado`, works with both `4.3` & `4.4`. Thank you.
