### ISSUE TITLE
The path custom_theme doesn't exist

### ISSUE THREAD

**Issue by ppKrauss** [mkdocs/mkdocs#1206]
The Guide say to add at `MYDOCS/mkdocs.yml`  the line `theme_dir: custom_theme` and I created it as `mkdir MYDOCS/docs/custom_theme` with a copy of [base.html](https://raw.githubusercontent.com/mkdocs/mkdocs/master/mkdocs/themes/mkdocs/base.html) into it.

The command `mkdocs build` (at `MYDOCS` and was working fine) now say 

> ERROR   -  Config value: 'theme_dir'. Error: The path custom_theme doesn't exist

**Comment by tramponi** [comment]
The correct path should be:

`MYDOCS/custom_theme`

:) cheers

**Comment by ppKrauss** [comment]
Thanks @tramponi (!), now is alive!  ... Sorry, other problem:

```
WARNING -  Your theme does not appear to contain a 'main.html' template. The 'base.html' template was used instead, which is deprecated. Update your theme so that the primary entry point is 'main.html'. 
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/commands/build.py", line 380, in build
    build_pages(config, dirty=dirty)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/commands/build.py", line 333, in build_pages
    dump_json)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/commands/build.py", line 213, in _build_page
    output_content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/gits/miniguias/DiscussOKBr/custom_theme/base.html", line 63, in top-level template code
    {%- block content %}
  File "/home/user/gits/miniguias/DiscussOKBr/custom_theme/base.html", line 64, in block "content"
    <div class="col-md-3">{% include "toc.html" %}</div>
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: toc.html
```

**Comment by ppKrauss** [comment]
oops, explain: need to **only override** some files.

**Comment by tramponi** [comment]
As stated here:
http://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks

> The built-in themes implement many of their parts inside template blocks which can be individually overridden in the main.html template. Simply create a main.html template file in your theme_dir and define replacement blocks within that file. Just make sure that the main.html extends base.html. For example, to alter the title of the MkDocs theme, your replacement main.html template would contain the following:

`{% extends "base.html" %}

{% block title %}
<title>Custom title goes here</title>
{% endblock %}`

So, don't put a copy of base.html inside, but use main.html instead.

**Comment by ppKrauss** [comment]
Thanks @tramponi. Hum... using the main.html that you suggested (and is the overriding-template-blocks suggestion),  it is not working:

1. With no addiction, error "jinja2.exceptions.TemplateNotFound: base.html"

2. Adding `base.html` file, error below

```
mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/user/gits/miniguias/DiscussOKBr/site 
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/commands/build.py", line 380, in build
    build_pages(config, dirty=dirty)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/commands/build.py", line 333, in build_pages
    dump_json)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/commands/build.py", line 213, in _build_page
    output_content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/gits/miniguias/DiscussOKBr/custom_theme/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/user/gits/miniguias/DiscussOKBr/custom_theme/base.html", line 60, in top-level template code
    {% include "nav.html" %}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: nav.html
```

**Comment by waylan** [comment]
@ppKrauss what do you have the `theme` config option set to? As it states in the "Note" [here]:

> For this to work, the `theme` setting must be set to a known installed theme. If the `theme` setting is instead set to `null` (or not defined), then there is no theme to override and the contents of the `theme_dir` must be a complete, standalone theme. See [Custom Themes] for more information.

It works differently depending on the specific set of options you have set. Without a clear understanding of which set of options you have, I can't help you.

[here]: http://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme_dir
[Custom Themes]: http://www.mkdocs.org/user-guide/custom-themes/

**Comment by ppKrauss** [comment]
Thanks @waylan .  We are abandoning the ideal "by Overridde Custom Default Theme", because it not works fine (or it is not so obvous to use)... Now we are adopting a copy-and-sync strategy. See https://github.com/okfn-brasil/miniguias, that will be a ["hub" for many guides](https://okfn-brasil.github.io/miniguias/).
