### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by sybrenstuvel** [mkdocs/mkdocs#1237]
IPv4 is old, IPv6 is current. `mkdocs  serve -a '[::0]:8081'` fails with the following error:

```
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
Traceback (most recent call last):
  File "/home/sybren/.virtualenvs/flamenco/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/sybren/.virtualenvs/flamenco/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sybren/.virtualenvs/flamenco/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sybren/.virtualenvs/flamenco/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sybren/.virtualenvs/flamenco/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sybren/.virtualenvs/flamenco/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sybren/.virtualenvs/flamenco/lib/python3.6/site-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/home/sybren/.virtualenvs/flamenco/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 116, in serve
    _livereload(host, port, config, builder, tempdir)
  File "/home/sybren/.virtualenvs/flamenco/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 55, in _livereload
    server.serve(root=site_dir, host=host, port=int(port), restart_delay=0)
ValueError: invalid literal for int() with base 10: ':0]:8081'
```

Tested with mkdocs-0.16.3 on Python 3.6.

Instead of doing `config['dev_addr'].split(':', 1)` (serve.py:112), please consider using the [ipaddress](https://docs.python.org/3/library/ipaddress.html) module from the standard Python library.

**Comment by waylan** [comment]
The server is intended for development purposes only and it not intended to be used to serve your site to the world. It's just a "localhost" server. The only reason the user can specify an IP/port is to avoid conflicts with other servers which might be running on the same machine.

That being the case, is there any reason why we need to support IPv6?

**Comment by waylan** [comment]
I'm labeling this as a "bug" do to the failure to properly split off the port. If that gives us IPv6 support for free, then great. But if not, we'll address that matter separately.

**Comment by sybrenstuvel** [comment]
> The only reason the user can specify an IP/port is to avoid conflicts with other servers which might be running on the same machine.
> That being the case, is there any reason why we need to support IPv6?

Localhost may not even be IPv4, or you may want to bind to a public IP like `[::0]` to let someone else on the network look at the docs you're writing.

**Comment by waylan** [comment]
One more note. the ipaddress lib was added to the standard library in 3.3, but we support 2.6 and 2.7 in the current release with no plans to drop support for 2.7.

**Comment by waylan** [comment]
For future reference, the ipadress lib has been [backported](https://pypi.python.org/pypi/ipaddress) for 2.6, 2.7 and 3.2.

**Comment by waylan** [comment]
As it turns out, we were not doing any validation of the value at all (except to ensure the provided value was a string, which it always would be from the command line). I've provided a fix which includes proper validation (with pretty error messages) and tests in #1238. And as I suspected, properly separating the port from the host gives us IPv6 support for free.

**Comment by peng-cheng-li** [comment]
does mkdocs support ipv6?
I can't run mkdocs server :::8000
