### ISSUE TITLE
Permission denied on zerorpc-0.6.1-py2.7.egg/EGG-INFO/entry_points.txt'

### ISSUE THREAD

**Issue by zhangzq** [mkdocs/mkdocs#1277]
when I run `mkdocs build`, I got following python error:

Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 7, in <module>
    from mkdocs.__main__ import cli
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/__main__.py", line 78, in <module>
    theme_choices = utils.get_theme_names()
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/utils/__init__.py", line 413, in get_theme_names
    return get_themes().keys()
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/utils/__init__.py", line 392, in get_themes
    for theme in pkg_resources.iter_entry_points(group='mkdocs.themes'):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 706, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2577, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2307, in parse_map
    for group, lines in data:
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2878, in split_sections
    for line in yield_lines(s):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2174, in yield_lines
    for ss in strs:
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2503, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1477, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1469, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1580, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/zerorpc-0.6.1-py2.7.egg/EGG-INFO/entry_points.txt'

**Comment by waylan** [comment]
It appears that you have some file permissions improperly configured on your system. Try running the following command:

    sudo chmod -R o+r /usr/local/lib/python2.7/dist-packages/

See [this][1] for more info.

[1]; https://stackoverflow.com/a/24663620/866026
