### ISSUE TITLE
Image with relative path in heading works in serve but not after build

### ISSUE THREAD

**Issue by smalers** [mkdocs/mkdocs#1324]
I thought I was being clever by using an icon to visually indicate which sections in a document are relevant to Linux and which are relevant to Windows, using 32x32 icon files.  For example, I use the following Markdown:

```
### ![Linux](../../images/linux-32.png) Linux ###
```
This renders great with `mkdocs serve` so I used it quite a few places.  The icons are stored in `docs/images`.  However, when I run `mkdocs build` and then deploy the site folder to a static Amazon S3 website, the images are not rendered and the above renders as:  Linux Linux.  For example, the serve version is:

![image](https://user-images.githubusercontent.com/6448274/31940157-5b1cbb92-b87a-11e7-86fc-dc99ee4d11b8.png)

And the build/deploy version is:

![image](https://user-images.githubusercontent.com/6448274/31940240-a92b34da-b87a-11e7-9253-868d7b5d2520.png)

Note that the deployment drops the site in an Amazon S3 bucket where the root for the site can have any number of parent folders, so using relative paths is necessary.  In all other cases images work where I have used relative paths down from a file, so maybe the relative path upward is an issue?  I often use ../ to reference other Markdown files in a site.  I see other issues related to this but it is difficult to tell what the status is.  I really don't want to copy the Linux/Windows icons to multiple subfolders.

I'm using MkDocs 0.16.3 and Material theme.  I did try MkDocs 0.17.0 but mkdocs serve gave the following error so I went back to 0.16.3:

```
sam (1-add-dev-doc *) doc-dev-mkdocs-project $ mkdocs serve
INFO    -  Building documentation...
Traceback (most recent call last):
  File "c:\program files\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python35\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\mkdocs\__main__.py", line 127, in serve_command
    livereload=livereload
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\mkdocs\commands\serve.py", line 114, in serve
    config = builder()
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\mkdocs\commands\serve.py", line 104, in builder
    theme_dir=theme_dir
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\mkdocs\config\base.py", line 181, in load_config
    errors, warnings = cfg.validate()
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\mkdocs\config\base.py", line 105, in validate
    post_failed, post_warnings = self._post_validate()
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\mkdocs\config\base.py", line 85, in _post_validate
    config_option.post_validation(self, key_name=key)
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\mkdocs\config\config_options.py", line 433, in post_validation
    config[key_name] = theme.Theme(**theme_config)
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\mkdocs\theme.py", line 47, in __init__
    self._load_theme_config(name)
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\mkdocs\theme.py", line 77, in _load_theme_config
    theme_dir = utils.get_theme_dir(name)
  File "C:\Users\sam\AppData\Roaming\Python\Python35\site-packages\mkdocs\utils\__init__.py", line 373, in get_theme_dir
    return os.path.dirname(os.path.abspath(theme.load().__file__))
  File "c:\program files\python35\lib\site-packages\pkg_resources\__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "c:\program files\python35\lib\site-packages\pkg_resources\__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "c:\program files\python35\lib\site-packages\pkg_resources\__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (mkdocs 0.17.0 (c:\users\sam\appdata\roaming\python\python35\site-packages), Requirement.parse('mkdocs==0.16.3'))

```

**Comment by waylan** [comment]
Yes, the material theme has not been updated for MkDocs 0.17 yet, which explains the error.

Now to focus on the relative path issue. The screen shots of the rendered page are completely unhelpful. We need to see the HTML output. I suggest using your browsers "view source" feature (right-click on page to access) and copy and paste the HTML generated by MkDocs from your Markdown links. It may also be helpful to provide the directory structure of the relevant files.

**Comment by smalers** [comment]
**My bad on this one.**   Here is more information in case it helps others.  I'll let the MkDocs team evaluate whether it warrants action on their part.

Images are in a folder docs/images, where docs is the normal MkDocs folder:

```text
docs/
  images/
       linux-32.png
  dev-new/
       overview.md     (this file has the reference to ../../images/linux-32.png
```

Within the docs there are several folders.  The content in question uses images that reference the images by using `../../images/linux-32.png` .  **This was in error and should have been `../images/linux-32.png`**.  Apparently when run as a local server, any extra `../` don't cause a 404 error and bang against the root but do display the file.  The generated html from `mkdocs serve` and `mkdocs build` was the same.

I don't know if there is a way to better handle the content error that caused my confusion.  A possible enhancement to MkDocs would be to generate a console warning or 404 error if a relative reference goes beyond the local root, but I suppose someone could piece together different websites in a deployed environment and the URL would be valid.  Maybe add a `--check` option to MkDocs that is more picky with such things, to help developers of content?  I tried the `--verbose` option to see if it prints a warning in this case and it does not.  I don't know if there are other such gotchas that would benefit from a check capability.

Thanks.

**Comment by waylan** [comment]
So it sounds like this was simply a user error which has since been corrected.

The way things are currently implemented, that's not possible to generate warnings for bad internal links. MkDocs simply passes the  `docs_dir` to a `copy_files` function which blindly copies everything (except Markdown files) to the `site_dir`. MkDocs has no knowledge of what files actually exist outside of the Markdown files. To do anything in that regard would require a complete refactor of the internals, which is the subject of a few other open issues.

Given the above, I'm closing this.
