### ISSUE TITLE
Not building with theme

### ISSUE THREAD

**Issue by Tslimshady99** [mkdocs/mkdocs#1338]
Everytime i try and build with a theme it wont build and stops, 
```
Running with gitlab-runner 10.1.0 (c1ecf97f)
  on 103.patzar.net (b923334b)
Using Docker executor with image python:latest ...
Using docker image sha256:ed906f21ec9882aee6645c59ddbca26e13ae775cd92b9ca2dbb391005fa35739 for predefined container...
Pulling docker image python:latest ...
Using docker image python:latest ID=sha256:79e1dc9af1c1d276a3cae7c1c56290f2101c0aedbf70cbbb322e1a6b16149bd5 for build container...
Running on runner-b923334b-project-10-concurrent-0 via 103.patzar.net...
Fetching changes...
Removing site/
HEAD is now at 23572d7 Update gitlab-ci.yml
From http://git.patzar.net/BotDev/Docs
   23572d7..a95787f  master     -> origin/master
Checking out a95787f0 as master...
Skipping Git submodules setup
$ python -V
Python 3.6.3
$ pip install mkdocs
Collecting mkdocs
  Downloading mkdocs-0.17.1-py2.py3-none-any.whl (1.2MB)
Collecting Jinja2>=2.7.1 (from mkdocs)
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
Collecting livereload>=2.5.1 (from mkdocs)
  Downloading livereload-2.5.1.tar.gz
Collecting tornado>=4.1 (from mkdocs)
  Downloading tornado-4.5.2.tar.gz (483kB)
Collecting Markdown>=2.3.1 (from mkdocs)
  Downloading Markdown-2.6.9.tar.gz (271kB)
Collecting click>=3.3 (from mkdocs)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting PyYAML>=3.10 (from mkdocs)
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.7.1->mkdocs)
  Downloading MarkupSafe-1.0.tar.gz
Collecting six (from livereload>=2.5.1->mkdocs)
  Downloading six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: livereload, tornado, Markdown, PyYAML, MarkupSafe
  Running setup.py bdist_wheel for livereload: started
  Running setup.py bdist_wheel for livereload: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/71/95/bf/6ccaa70b36701dd3fa337296d7ec6614bf14f51d58bc3a4a7a
  Running setup.py bdist_wheel for tornado: started
  Running setup.py bdist_wheel for tornado: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/b3/47/3a/96e12476829cb196adabc879fedb72f1bb2c8613b6961e78e7
  Running setup.py bdist_wheel for Markdown: started
  Running setup.py bdist_wheel for Markdown: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/bf/46/10/c93e17ae86ae3b3a919c7b39dad3b5ccf09aeb066419e5c1e5
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for MarkupSafe: started
  Running setup.py bdist_wheel for MarkupSafe: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57
Successfully built livereload tornado Markdown PyYAML MarkupSafe
Installing collected packages: MarkupSafe, Jinja2, tornado, six, livereload, Markdown, click, PyYAML, mkdocs
Successfully installed Jinja2-2.9.6 Markdown-2.6.9 MarkupSafe-1.0 PyYAML-3.12 click-6.7 livereload-2.5.1 mkdocs-0.17.1 six-1.11.0 tornado-4.5.2
$ mkdocs build
WARNING -  Config value: 'theme_dir'. Warning: The configuration option {0} has been deprecated and will be removed in a future release of MkDocs. 
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /builds/BotDev/Docs/site 
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/build.py", line 150, in _build_page
    template = env.get_template('main.html')
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main.html
ERROR: Job failed: exit code 1
```
I also tried using
```
theme:
  name: cinder
```
but that also did the same thing

**Comment by waylan** [comment]
You appear to be using an older template which has not been updated for a more recent version of MkDocs. In 0.16, that theme would have issues a warning that it would stop working in the next release. Now that we have released 0.17, it no longer works. If you want to continue using that theme, you will need to stay on MkDocs 0.16.x until the theme is updated. You should file a bug report with the theme project if one has not been filed already.

**Comment by robodude666** [comment]
@waylan I frankly disagree that the config file should be required. `mkdocs` can't assume sane defaults?Also, why would a `custom_dir` theme continue to work then without a config file?

It's also been 18 days since the release of 0.17.0 and `mkdocs-bootstrap` and `mkdocs-bootswatch` haven't been updated yet to fulfill this requirement.

**Comment by waylan** [comment]
> @waylan I frankly disagree that the config file should be required. mkdocs can't assume sane defaults?Also, why would a `custom_dir` theme continue to work then without a config file?

The failure is not related to either of those issues, both of which were first introduced in 0.17 and are currently in their grace period (giving theme devs an opportunity to update now before the next release). The problem relates to the fact that the theme does not have a `main,html` template, which requirement was [introduced in 16.0][1] over a year ago.

> It's also been 18 days since the release of 0.17.0 and `mkdocs-bootstrap` and `mkdocs-bootswatch` haven't been updated yet to fulfill this requirement.

You may have a valid point, but that is an issue you should take of which those respective projects. As I've pointed out, themes have had over a year to update. We can't hold MkDocs back because some theme devs have not done so.

As an aside, I provided the necessary changes to both `mkdocs-bootstrap` and `mkdocs-bootswatch` (see mkdocs/mkdocs-bootstrap#8 and mkdocs/mkdocs-bootswatch#23) back when MkDocs 0.16.0 was released (you could install from HEAD of the master branch of either repo to get updated themes), but I do not have the credentials to do a release of those projects. While I have been given commit access to all three repos, only the `mkdocs/mkdocs` repo has automated releases from Travis CI (a release happens if an authorized committer pushes a tag). The themes require manual uploads to PyPI, which require a PyPI user account with permissions for the respective projects (which I do not have). Either @d0ugal or @tomchristie would need to do that.

[1]: http://www.mkdocs.org/about/release-notes/#increased-template-customization-607

**Comment by robodude666** [comment]
woops, fair enough. didn't see PyPi is outdated.
