### ISSUE TITLE
Migrating from .16.x to .17.x has issues with a number of themes

### ISSUE THREAD

**Issue by andrewschott** [mkdocs/mkdocs#1363]
A number of the themes linked to on the wiki do not currently allow a successful site build for me.

cinder and bootswatch family themes are two that I am having issues with where the only change is mkdocs version.  I have installed onto a CentOS7 VPS via pip.  Perhaps I am missing a dependency that is not forced via pip?  Similar issues on both my F27 and RHEL7 workstations.

Thanks much!

Here is my verbose output and "pip list" if this helps (ask for more if needed)

```
$ mkdocs build --verbose
DEBUG   -  Loading configuration file: /home/andrew/workspace/schotty.com/schotty_com/mkdocs.yml 
DEBUG   -  [Errno 2] No such file or directory: u'/usr/lib/python2.7/site-packages/cinder/mkdocs_theme.yml' 
WARNING -  The theme 'cinder' does not appear to have a configuration file. Please upgrade to a current version of the theme. 
DEBUG   -  Config value: 'site_name' = u'Schotty.com' 
DEBUG   -  Config value: 'extra' = <mkdocs.config.config_options.SubConfig object at 0x7fd7a9f96790> 
DEBUG   -  Config value: 'extra_javascript' = [] 
DEBUG   -  Config value: 'plugins' = PluginCollection([(u'search', <mkdocs.contrib.legacy_search.SearchPlugin object at 0x7fd7aa114550>)]) 
DEBUG   -  Config value: 'extra_css' = [] 
DEBUG   -  Config value: 'theme_dir' = None 
DEBUG   -  Config value: 'config_file_path' = u'/home/andrew/workspace/schotty.com/schotty_com/mkdocs.yml' 
DEBUG   -  Config value: 'copyright' = None 
DEBUG   -  Config value: 'remote_branch' = u'gh-pages' 
DEBUG   -  Config value: 'site_url' = u'https://www.schotty.com/' 
DEBUG   -  Config value: 'use_directory_urls' = True 
DEBUG   -  Config value: 'strict' = False 
DEBUG   -  Config value: 'theme' = Theme(name='cinder', dirs=['/usr/lib/python2.7/site-packages/cinder', u'/usr/lib/python2.7/site-packages/mkdocs/templates'], static_templates=[u'sitemap.xml'], ) 
DEBUG   -  Config value: 'docs_dir' = u'/home/andrew/workspace/schotty.com/schotty_com/docs' 
DEBUG   -  Config value: 'repo_name' = u'' 
DEBUG   -  Config value: 'site_dir' = u'/home/andrew/workspace/schotty.com/schotty_com/site' 
DEBUG   -  Config value: 'dev_addr' = Address(host=u'127.0.0.1', port=8000) 
DEBUG   -  Config value: 'repo_url' = u'' 
DEBUG   -  Config value: 'remote_name' = u'origin' 
DEBUG   -  Config value: 'pages' = [u'index.md', {u'Blog': [u'Blog/Blogroll.md']}, {u'Docker': [u'Docker/Docker Minecraft Server Container.md', u'Docker/Docker_Dedicated_CSGO_Server Container.md']}, {u'EL & Fedora': [u'EL & Fedora/Albion_Online.md', u'EL & Fedora/Apache_2_Notes.md', u'EL & Fedora/DIY_Steam_Machine.md', u'EL & Fedora/EL6-7_shellinabox.md', u'EL & Fedora/EL7_Cockpit.md', u'EL & Fedora/EL7_Gitlab.md', u'EL & Fedora/EL7_Lets_Encrypt.md', u'EL & Fedora/EL7_Nextcloud.md', u'EL & Fedora/EL7_Plex_Media_Server.md', u'EL & Fedora/EL7_ProXPN.md', u'EL & Fedora/EL7_Remote_Access_Made_Easy.md', u'EL & Fedora/EL7_Samba_CIFS_Server.md', u'EL & Fedora/EL7_Unity3d_Editor.md', u'EL & Fedora/EL7_Wine_and_Crossover.md', u'EL & Fedora/EL7_Xbox360_Wireless_Controller.md', u'EL & Fedora/EL7_iperf.md', u'EL & Fedora/EL7_openvpn.md', u'EL & Fedora/EL_&_Fedora_NetInstall_Installation_Procedure.md', u'EL & Fedora/EL_Repos.md', u'EL & Fedora/Fedora_Upgrades.md', u'EL & Fedora/Fedora_on_Dell_Inspiron_5000.md', u'EL & Fedora/RPM_Cheatsheet.md', u'EL & Fedora/RPM_Creation.md']}, {u'General Linux': [u'General Linux/Chromeos_Crouton.md', u'General Linux/EXT_Filesystems_On_Windows.md', u'General Linux/Flatpak_Guide.md', u'General Linux/GNOME3_+_KDE-Connect.md', u'General Linux/Git_Cheatsheet.md', u'General Linux/LVM_Cheatsheet.md', u'General Linux/Mikrotik_RouterOS_Cheatsheet.md', u'General Linux/OpenBSD_3.0_Installation_Guide.md', u'General Linux/Pi_Top_Notes.md', u'General Linux/PocketCHIP.md', u'General Linux/SSH_Tips.md', u'General Linux/Ubuntu_apt_problems_&_fixes.md', u'General Linux/Using_Linux_Counter.md', u'General Linux/Wine_Basics.md', u'General Linux/Wine_Plus_Blizzard_App.md', u'General Linux/mkdocs.md', u'General Linux/tmux_Cheatsheet.md']}, {u'Schotty.com': [u'Schotty.com/Contact_Schotty.md', u'Schotty.com/Links.md', u'Schotty.com/Schotty.com_EL_Hosted_yum_Repositories.md', u'Schotty.com/Schotty.com_Hosted_Services.md']}] 
DEBUG   -  Config value: 'markdown_extensions' = [u'toc', u'tables', u'fenced_code'] 
DEBUG   -  Config value: 'site_description' = None 
DEBUG   -  Config value: 'extra_templates' = [] 
DEBUG   -  Config value: 'site_author' = None 
DEBUG   -  Config value: 'google_analytics' = [u'UA-81841123-1', u'schotty.com'] 
DEBUG   -  Config value: 'mdx_configs' = {} 
DEBUG   -  Config value: 'edit_uri' = u'' 
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/andrew/workspace/schotty.com/schotty_com/site 
DEBUG   -  Copying static assets from /usr/lib/python2.7/site-packages/mkdocs/contrib/legacy_search/templates 
DEBUG   -  Copying static assets from the docs dir. 
DEBUG   -  Building template: sitemap.xml 
DEBUG   -  Building extra_templates pages 
DEBUG   -  Building markdown pages. 
DEBUG   -  Building page index.md 
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 150, in _build_page
    template = env.get_template('main.html')
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main.html
[andrew@oberth schotty_com]$ 

```

```
$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
ailurus (10.10.3)
Antenna-DTV (0.1)
apsw (3.20.1.post1)
asn1crypto (0.23.0)
Babel (2.3.4)
backports-abc (0.5)
backports.ssl-match-hostname (3.5.0.1)
bcrypt (3.1.4)
Beaker (1.5.4)
BeautifulSoup (3.2.1)
beautifulsoup4 (4.6.0)
bodhi (2.12.2)
bodhi-client (2.12.2)
bzr (2.7.0)
CCColUtils (1.5)
certifi (2017.11.5)
cffi (1.10.0)
chardet (3.0.4)
CherryPy (3.5.0)
click (6.7)
cryptography (2.0.2)
cssselect (0.9.2)
cssutils (1.0.1)
decorator (4.0.11)
dnspython (1.15.0)
dockerfile-parse (0.0.7)
docutils (0.13.1)
enum34 (1.1.6)
fedora-review (0.6.1)
fedpkg (1.30)
feedparser (5.2.1)
file-magic (0.3.0)
flowblade (1.14.0)
Genshi (0.7)
gevent (1.1.2)
gitdb2 (2.0.3)
GitPython (2.1.7)
gpg (1.9.0)
greenlet (0.4.11)
gssapi (1.2.0)
html5-parser (0.4.4)
html5lib (0.999999999)
idna (2.5)
iniparse (0.4)
ipaddress (1.0.18)
jedi (0.10.2)
Jinja2 (2.10)
kerberos (1.2.5)
kitchen (1.2.4)
Ksplice-Uptrack (1.2.45)
livereload (2.5.1)
lockfile (0.11.0)
lxml (4.1.1)
Mako (1.0.6.dev0)
Markdown (2.6.10)
markdown-include (0.5.1)
MarkupSafe (1.0)
mechanize (0.3.5)
mkdocs (0.17.2)
mkdocs-bootstrap (0.1.1)
mkdocs-bootswatch (0.4.0)
mkdocs-cinder (0.9.4)
mkdocs-cluster (0.0.7)
msgpack-python (0.4.8)
munch (2.2.0)
netifaces (0.10.6)
nose (1.3.7)
numpy (1.13.3)
obMenu (1.0)
odfpy (1.3.4)
offtrac (0.1.0)
olefile (0.44)
openidc-client (0.4.0)
osbs-client (0.41)
packagedb-cli (2.14.1)
packaging (16.8)
paramiko (2.3.1)
Paste (2.0.3)
Pillow (4.3.0)
pip (9.0.1)
ply (3.9)
psutil (5.2.2)
pwquality (1.4.0)
pyasn1 (0.3.7)
pycairo (1.15.3)
pycparser (2.14)
pycrypto (2.6.1)
pycryptopp (0.6.0.1206569328141510525648634803928199668821045408958)
pycups (1.9.72)
pycurl (7.43.0)
Pygments (2.2.0)
pygobject (3.26.1)
pygpgme (0.3)
pyliblzma (0.5.3)
pymdown-extensions (4.7)
PyNaCl (1.1.2)
pyOpenSSL (17.2.0)
pyparsing (2.1.10)
PySide (1.2.2)
PySocks (1.6.7)
python-bugzilla (2.1.0)
python-dateutil (2.6.0)
python-fedora (0.9.0)
python-xlib (0.19)
python-yubico (1.3.2)
pytz (2017.2)
pyusb (1.0.0)
pyxattr (0.5.3)
pyxdg (0.25)
PyYAML (3.12)
regex (2016.9.22)
reportlab (3.4.0)
requests (2.18.4)
requests-kerberos (0.10.0)
rpkg (1.51)
rpm (4.14.0)
scour (0.35)
setproctitle (1.1.10)
setuptools (36.2.0)
simplejson (3.10.0)
singledispatch (3.4.0.3)
six (1.11.0)
smmap2 (2.0.3)
straight.plugin (1.4.0.post1)
Tempita (0.5.1)
tornado (4.5.2)
uniconvertor (2.0)
urlgrabber (3.10.1)
urllib3 (1.22)
webencodings (0.5.1)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
x2go (0.5.0.5)
yum-metadata-parser (1.1.4)

```

**Comment by waylan** [comment]
Those themes are two versions behind. Some things were deprecated in MkDocs version 0.16 (but still worked with a warning) and no longer work in 0.17. Unfortunately, despite that fact that I created pull requests on those projects to update them, no new releases have been made. Please report the issue to the respective projects directly.

The wiki page is a publicly editable page and anyone can add to the list of themes. I'm not going to police the list to ensure only up-to-date themes are listed there. However, if you come across an error on the list, feel free to add a note to the list (please keep things respectful and don't delete items without good reason and an explanation).

As there is no actionable item here for the MkDocs project, I'm closing this.

**Comment by andrewschott** [comment]
Thanks, this helped immensely.

**Comment by ishenyi** [comment]
I have the same problem. If I wanna change back to mkdocs version 0.15.3 (now version 0.17.2), what should I do. I tried blew,but didn‘ t work. Give me some guids,tks!

`pip install mkdocs==0.15.3`

**Comment by waylan** [comment]
@ishenyi if you are changing to a different version you need to uninstall the current version first, then reinstall the desired version. Despite its name, pip's `--upgrade` flag will do this for you even if you are moving backwards. All it really does is cause the currently installed version to be uninstalled before installing the requested version.

    pip install --upgrade mkdocs=0.15

If for some reason that doesn't work, you could always use two commands:

    pip uninstall mkdocs
    pip install mkdocs=0.15

Oh, and you don't need to specify the `.3` in the version. The most recent of `0.15` will always be used if you leave the last part off.

**Comment by ketozhang** [comment]
Seems like no developers are wanting to change their themes to match with the current update and wish to stick to 0.15.x.

**Comment by noraj1337** [comment]
Hi @waylan I would appreciate some help to upgrade [windmill-dark](https://github.com/noraj1337/mkdocs-windmill-dark/) theme to the new search plugin introduce in mkdocs 0.17.0. See https://github.com/noraj1337/mkdocs-windmill-dark/issues/2
