### ISSUE TITLE
Help with themes

### ISSUE THREAD

**Issue by nxtVentix** [mkdocs/mkdocs#1450]
i have added a theme

if a type now `mkdocs build`

```
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.15.3', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mkdocs/__main__.py", line 136, in build_command
    site_dir=site_dir
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 151, in load_config
    errors, warnings = cfg.validate()
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 79, in validate
    failed, warnings = self._validate()
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 52, in _validate
    self[key] = config_option.validate(value)
  File "/usr/lib/python3/dist-packages/mkdocs/config/config_options.py", line 96, in validate
    return self.run_validation(value)
  File "/usr/lib/python3/dist-packages/mkdocs/config/config_options.py", line 295, in run_validation
    if value in themes:
TypeError: unhashable type: 'dict'
````
my `mkdocs.yml`:
```
site_name: My Docs
theme:
  name: 'rtd-dropdown'
```

**Comment by nxtVentix** [comment]
fixed with: `python -m mkdocs build`

**Comment by waylan** [comment]
Note the version of MkDocs in your error:

```
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.15.3', 'console_scripts', 'mkdocs')()
```

You appear to have version 0.15.3 installed. However, the latest version is 0.17.3. I suspect updating to the latest version would resolve your problem.

It could also be that you have two versions installed somehow. Do you get different results from the following two commands?

```
mkdocs --version
python -m mkdocs --version
```
