### ISSUE TITLE
Overriding template blocks

### ISSUE THREAD

**Issue by feppie64** [mkdocs/mkdocs#1633]
Hi,

I'm trying to override main.html, so I can remove the Google Fonts call in the readthedocs theme. To achieve this, I am trying to follow https://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks. However, the following minimal example gives an error:

```
mkdir mkdocs
cd mkdocs
mkdocs new .
mkdir docs/custom_theme
echo "theme:
    name: mkdocs
    custom_dir: custom_theme/" >> mkdocs.yml
echo "{% extends ""base.html"" %}

{% block title %}
<title>Custom title goes here</title>
{% endblock %}" > docs/custom_theme/main.html
mkdocs build
```

The error is:

```
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python36\lib\site-packages\mkdocs\__main__.py", line 162, in build_command
    site_dir=site_dir
  File "c:\python36\lib\site-packages\mkdocs\config\base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "c:\python36\lib\site-packages\mkdocs\config\base.py", line 115, in validate
    post_failed, post_warnings = self._post_validate()
  File "c:\python36\lib\site-packages\mkdocs\config\base.py", line 95, in _post_validate
    config_option.post_validation(self, key_name=key)
  File "c:\python36\lib\site-packages\mkdocs\config\config_options.py", line 430, in post_validation
    format(path=theme_config['custom_dir'], name=self.name))
AttributeError: 'Theme' object has no attribute 'name'
```

This error does not seem to show up in 0.17.5, but it does in 1.0.4.

A possible cause could be that I'm putting my directory inside the docs_dir, contrary to the documentation. However, putting it next to the docs_dir, gives another error:

```
mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: D:\mkdocs\site
ERROR   -  Error building page index.md
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python36\lib\site-packages\mkdocs\__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "c:\python36\lib\site-packages\mkdocs\commands\build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "c:\python36\lib\site-packages\mkdocs\commands\build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "c:\python36\lib\site-packages\mkdocs\commands\build.py", line 158, in _build_page
    output_content = template.render(context)
  File "c:\python36\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\python36\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\lib\site-packages\jinja2\_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "D:\mkdocs\custom_theme\main.html", line 1, in <module>
    {% extends base.html %}
  File "c:\python36\lib\site-packages\jinja2\environment.py", line 397, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'base' is undefined
```

Can anybody help me to get this working?

https://github.com/mkdocs/mkdocs/issues/1207 would also be helpful.

Thanks in advance.

**Comment by waylan** [comment]
I was able to reproduce this error. It appears we broke somehting.

```sh
$ mkdir test-docs
$ cd test-docs
$ mkdocs new .
INFO    -  Writing config file: .\mkdocs.yml
INFO    -  Writing initial docs: .\docs\index.md
$ mkdir custom_theme
$ echo "
theme:
    name: mkdocs
    custom_dir: custom_theme
" >> mkdocs.yml
$ cat mkdocs.yml
site_name: My Docs

theme:
    name: mkdocs
    custom_dir: custom_theme

$ echo "{% extends ""base.html"" %}

{% block title %}
<title>Custom title goes here</title>
{% endblock %}" > custom_theme/main.html
$ cat custom_theme/main.html
{% extends base.html %}

{% block title %}
<title>Custom title goes here</title>
{% endblock %}
$ mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: C:\Users\wlimberg\Documents\GitHub\test-docs\site
ERROR   -  Error building page 'index.md': 'base' is undefined
Traceback (most recent call last):
  File "C:\Users\wlimberg\Documents\GitHub\mkdocs\venv\Scripts\mkdocs-script.py", line 11, in <module>
    load_entry_point('mkdocs', 'console_scripts', 'mkdocs')()
  File "C:\Users\wlimberg\Documents\GitHub\mkdocs\venv\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\wlimberg\Documents\GitHub\mkdocs\venv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\wlimberg\Documents\GitHub\mkdocs\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\wlimberg\Documents\GitHub\mkdocs\venv\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\wlimberg\Documents\GitHub\mkdocs\venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\wlimberg\documents\github\mkdocs\mkdocs\__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "c:\users\wlimberg\documents\github\mkdocs\mkdocs\commands\build.py", line 295, in build
    _build_page(file.page, config, files, nav, env, dirty)
  File "c:\users\wlimberg\documents\github\mkdocs\mkdocs\commands\build.py", line 216, in _build_page
    output = template.render(context)
  File "C:\Users\wlimberg\Documents\GitHub\mkdocs\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\wlimberg\Documents\GitHub\mkdocs\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\wlimberg\Documents\GitHub\test-docs\custom_theme\main.html", line 1, in top-level template code
    {% extends base.html %}
  File "C:\Users\wlimberg\Documents\GitHub\mkdocs\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'base' is undefined
```

**Comment by waylan** [comment]
The problem is a syntax error in the template. Notice that the for the first line of the template (`{% extends base.html %}`), the error reports that `'base' is undefined`. Of course, as `base.html` is not a quoted string, Jinja expects `base` to be a variable name and, of course, there is no variable defined with the name `base`.

Wrap the template in quotes and the problem goes away:

```sh
$ echo "{% extends \"base.html\" %}

{% block htmltitle %}
<title>Custom title goes here</title>
{% endblock %}" > custom_theme/main.html
$ cat custom_theme/main.html
{% extends "base.html" %}

{% block htmltitle %}
<title>Custom title goes here</title>
{% endblock %}
$ mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: C:\Users\wlimberg\Documents\GitHub\test-docs\site
```

And as a final note, the block is named `htmltitle` as documented in the list of blocks, not `title`. The example in the docs should probably be updated to reflect the actual block name.

**Comment by feppie64** [comment]
Thanks a lot for your quick answer. It is working now and therefore, this issue can be closed.
