### ISSUE TITLE
Installation issue - DistributionNotFound

### ISSUE THREAD

**Issue by nitinsurana** [mkdocs/mkdocs#1636]
`pip install mkdocs`
followed by `mkdocs--version`
in ubuntu12 with python 2.7 gives
```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 7, in <module>
    from mkdocs.__main__ import cli
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/__main__.py", line 78, in <module>
    theme_choices = utils.get_theme_names()
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/utils/__init__.py", line 403, in get_theme_names
    return get_themes().keys()
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/utils/__init__.py", line 380, in get_themes
    builtins = pkg_resources.get_entry_map(dist='mkdocs', group='mkdocs.themes')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 341, in get_entry_map
    return get_distribution(dist).get_entry_map(group)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 330, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 209, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: mkdocs
```

**Comment by waylan** [comment]
First, just to eliminate the possibility, there should be a space between `mkdocs` and `--version`.

If that isn't the problem, is `mkdocs` listed if you run the `pip freeze` command?

Although, looking at the traceback, it appears that MkDocs is installed just fine. However, the error is raised when attempting to acquire a list of installed themes. If would appear that you have a problem with one of your installed themes which is raising the error.

**Comment by gurleen-gks** [comment]
Running `pip --upgrade --user distribute` before installing mkdocs fixed the issue.
