### ISSUE TITLE
Extension config and tabs

### ISSUE THREAD

**Issue by epicfaace** [mkdocs/mkdocs#1728]
When I do

```
markdown_extensions:
  - toc:
    permalink: true
```

I get a nasty error:
```
ERROR   -  Config value: 'markdown_extensions'. Error: Invalid Markdown Extensions configuration
[E 190121 10:10:07 ioloop:801] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 1229, in _run
        return self.callback()
      File "/usr/local/lib/python3.6/site-packages/livereload/handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/usr/local/lib/python3.6/site-packages/livereload/watcher.py", line 93, in examine
        func()
      File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 107, in builder
        site_dir=site_dir
      File "/usr/local/lib/python3.6/site-packages/mkdocs/config/base.py", line 210, in load_config
        "Aborted with {0} Configuration Errors!".format(len(errors))
    mkdocs.exceptions.ConfigurationError: Aborted with 1 Configuration Errors!
```

However, when I do
```
markdown_extensions:
  - toc:
      permalink: true
```
It works fine!

**Comment by waylan** [comment]
Yep, that's correct. That is how YAML works, which we have no control over.  `permalink: true` must be properly indented so that YAML recognizes it as a child of `- toc:`. If you want to take issue with that, then I suggest taking the issue upstream to the PyYAML project. Although YAML is very clearly defined by specification, so it's not likely you will effect any change.
