### ISSUE TITLE
mkdocs serve fails with python3.4

### ISSUE THREAD

**Issue by mananaBanana** [mkdocs/mkdocs#1775]
Installed `mkdocs` with pip
`$ sudo python3 -m pip install mkdocs`
It is installed successfully and commands like `mkdocs new` work fine.
But when I try to run the http server it fails with the following error.
```zsh
$ mkdocs serve
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mkdocs/__main__.py", line 134, in serve_command
    livereload=livereload
  File "/usr/local/lib/python3.4/dist-packages/mkdocs/commands/serve.py", line 124, in serve
    _livereload(host, port, config, builder, site_dir)
  File "/usr/local/lib/python3.4/dist-packages/mkdocs/commands/serve.py", line 36, in _livereload
    from livereload import Server
  File "/usr/local/lib/python3.4/dist-packages/livereload/__init__.py", line 15, in <module>
    from .server import Server, shell
  File "/usr/local/lib/python3.4/dist-packages/livereload/server.py", line 20, in <module>
    from tornado.wsgi import WSGIContainer
  File "/usr/local/lib/python3.4/dist-packages/tornado/wsgi.py", line 35, in <module>
    from tornado import httputil
  File "/usr/local/lib/python3.4/dist-packages/tornado/httputil.py", line 45, in <module>
    from typing import (
ImportError: cannot import name 'Awaitable'.
```

When I look up Awaitable it looks like it is a part of some typehinting in python3.5 and above. Or is that I am missing some module?
Thanks!

**Comment by mananaBanana** [comment]
Checked with python2.7 and it works fine.

**Comment by waylan** [comment]
Note that Python has [dropped support][1] for Python version 3.4 on March 19, 2019. I imagine at least one of our dependencies has also dropped support and is causing this failure. In fact, I checked and Tornado dropped support for Python 3.4 as of version 6.0 and Python-Livereload dropped support as of 2.6. We have two options:

1. Drop support for Python 3.4 ourselves.
2. Require an older version of the dependencies which are causing the problem.

Personally, I vote for option 1. Note that Python-Markdown is also scheduled to drop support with version 3.1, which is expected to be released soon.

@mananaBanana, I expect that you will continue to encounter more such errors as time progresses. I would strongly suggest upgrading to a newer Python version. In the short term, you might want to downgrade `tornado` to version 5.1.1 and `livereload` to version 2.5.2 and see if that resolves the issue.

[1]: https://devguide.python.org/#status-of-python-branches

**Comment by marcobraghim** [comment]
How can I set mkdocs to use python version 2.7 instead of 3? I'm not familiar to python.

**Comment by YevhenMaslov** [comment]
Got the same issue on Windows, any tips how to adjust terminal commands?
