### ISSUE TITLE
Unrecognised configuration name: nav

### ISSUE THREAD

**Issue by marcobraghim** [mkdocs/mkdocs#1786]
If I try to run the same configuration with python2.x in the Read The Docs, will build but not reconizing the 'nav' at all too.

-------------
```
Read the Docs build information
Build id: 8973113
Project: suitup-php
Version: version2.0
Commit: c4397d3222a3cd37e4ac8b6e5ed925a00699561a
Date: 2019-04-26T12:04:24.092151Z
State: finished
Success: False


[rtd-command-info] start-time: 2019-04-26T12:04:24.516785Z, end-time: 2019-04-26T12:04:24.525012Z, duration: 0, exit-code: 0
git remote set-url origin https://github.com/braghimsistemas/suitup-php


[rtd-command-info] start-time: 2019-04-26T12:04:24.582775Z, end-time: 2019-04-26T12:04:24.999831Z, duration: 0, exit-code: 0
git fetch --tags --prune --prune-tags --depth 50


[rtd-command-info] start-time: 2019-04-26T12:04:25.245514Z, end-time: 2019-04-26T12:04:25.263184Z, duration: 0, exit-code: 0
git checkout --force origin/version2.0
HEAD is now at c4397d3 docs

[rtd-command-info] start-time: 2019-04-26T12:04:25.330667Z, end-time: 2019-04-26T12:04:25.344707Z, duration: 0, exit-code: 0
git clean -d -f -f
Removing _build/
Removing docs/readthedocs-data.js

[rtd-command-info] start-time: 2019-04-26T12:04:29.833729Z, end-time: 2019-04-26T12:04:32.972050Z, duration: 3, exit-code: 0
python3.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0
Using base prefix '/home/docs/.pyenv/versions/3.7.1'
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/bin/python3.7
Also creating executable in /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/bin/python
Installing setuptools, pip, wheel...
done.

[rtd-command-info] start-time: 2019-04-26T12:04:33.039059Z, end-time: 2019-04-26T12:04:35.354433Z, duration: 2, exit-code: 0
/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/bin/python -m pip install --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/.cache/pip pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/f9/fb/863012b13912709c13cf5cfdbfb304fa6c727659d6290438e1a88df9d848/pip-19.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-19.1

[rtd-command-info] start-time: 2019-04-26T12:04:35.467011Z, end-time: 2019-04-26T12:04:48.697077Z, duration: 13, exit-code: 0
/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/bin/python -m pip install --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/.cache/pip Pygments==2.3.1 setuptools<41 docutils==0.14 mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 mkdocs==0.17.3
Collecting Pygments==2.3.1
  Using cached https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl
Collecting setuptools<41
  Using cached https://files.pythonhosted.org/packages/44/56/75e64a8fbbe9e0bd30cfdd58ca1856bc0dc15a43e41504a58d8373f34213/setuptools-40.9.0-py2.py3-none-any.whl
Collecting docutils==0.14
  Downloading https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl (543kB)
Collecting mock==1.0.1
  Using cached https://files.pythonhosted.org/packages/a2/52/7edcd94f0afb721a2d559a5b9aae8af4f8f2c79bc63fdbe8a8a6c9b23bbe/mock-1.0.1.tar.gz
Collecting pillow==5.4.1
  Downloading https://files.pythonhosted.org/packages/ae/2a/0a0ab2833e5270664fb5fae590717f867ac6319b124160c09f1d3291de28/Pillow-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (2.0MB)
Collecting alabaster!=0.7.5,<0.8,>=0.7
  Using cached https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Collecting commonmark==0.8.1
  Using cached https://files.pythonhosted.org/packages/ab/ca/439c88039583a29564a0043186875258e9a4f041fb5c422cd387b8e10175/commonmark-0.8.1-py2.py3-none-any.whl
Collecting recommonmark==0.5.0
  Using cached https://files.pythonhosted.org/packages/9b/3d/92ea48401622510e57b4bdaa74dc9db2fb9e9e892324b48f9c02d716a93a/recommonmark-0.5.0-py2.py3-none-any.whl
Collecting mkdocs==0.17.3
  Using cached https://files.pythonhosted.org/packages/79/52/f395c87a3ec799586a8cdf8f360a96ccbbf7f119200204d17166cc4fb097/mkdocs-0.17.3-py2.py3-none-any.whl
Collecting future (from commonmark==0.8.1)
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
Collecting sphinx>=1.3.1 (from recommonmark==0.5.0)
  Downloading https://files.pythonhosted.org/packages/9a/b0/a8cf1d35237aebefd63f05543ed49ea24d302239828ca89409b0c1a35b27/Sphinx-2.0.1-py2.py3-none-any.whl (3.2MB)
Collecting click>=3.3 (from mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting PyYAML>=3.10 (from mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz
Collecting tornado<5.0,>=4.1 (from mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/e3/7b/e29ab3d51c8df66922fea216e2bddfcb6430fb29620e5165b16a216e0d3c/tornado-4.5.3.tar.gz
Collecting livereload>=2.5.1 (from mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/ae/dd/f518bb99d84a3d26f45c281030b4d74b8cbe23bf8ad311b42e413aa33e51/livereload-2.6.0-py2.py3-none-any.whl
Collecting Jinja2>=2.7.1 (from mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting Markdown>=2.3.1 (from mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/f5/e4/d8c18f2555add57ff21bf25af36d827145896a07607486cc79a2aea641af/Markdown-3.1-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting sphinxcontrib-htmlhelp (from sphinx>=1.3.1->recommonmark==0.5.0)
  Downloading https://files.pythonhosted.org/packages/e4/35/80a67cc493f4a8a9634ab203a77aaa1b84d79ccb1c02eca72cb084d2c7f7/sphinxcontrib_htmlhelp-1.0.2-py2.py3-none-any.whl (96kB)
Collecting babel!=2.0,>=1.3 (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl
Collecting sphinxcontrib-qthelp (from sphinx>=1.3.1->recommonmark==0.5.0)
  Downloading https://files.pythonhosted.org/packages/ce/5b/4747c3ba98b3a3e21a66faa183d8f79b9ded70e74212a7988d236a6eb78a/sphinxcontrib_qthelp-1.0.2-py2.py3-none-any.whl (90kB)
Collecting sphinxcontrib-devhelp (from sphinx>=1.3.1->recommonmark==0.5.0)
  Downloading https://files.pythonhosted.org/packages/b0/a3/fea98741f0b2f2902fbf6c35c8e91b22cd0dd13387291e81d457f9a93066/sphinxcontrib_devhelp-1.0.1-py2.py3-none-any.whl (84kB)
Collecting sphinxcontrib-jsmath (from sphinx>=1.3.1->recommonmark==0.5.0)
  Downloading https://files.pythonhosted.org/packages/c2/42/4c8646762ee83602e3fb3fbe774c2fac12f317deb0b5dbeeedd2d3ba4b77/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl
Collecting sphinxcontrib-serializinghtml (from sphinx>=1.3.1->recommonmark==0.5.0)
  Downloading https://files.pythonhosted.org/packages/57/b3/3648e48fa5682e61e9839d62de4e23af1795ceb738d68d73bd974257a95c/sphinxcontrib_serializinghtml-1.1.3-py2.py3-none-any.whl (89kB)
Collecting packaging (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Collecting imagesize (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
Collecting requests>=2.5.0 (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting sphinxcontrib-applehelp (from sphinx>=1.3.1->recommonmark==0.5.0)
  Downloading https://files.pythonhosted.org/packages/13/9a/4428b3114d654cb1cd34d90d5e6fab938d5436f94a571155187ea1dd78b4/sphinxcontrib_applehelp-1.0.1-py2.py3-none-any.whl (121kB)
Collecting six (from livereload>=2.5.1->mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.7.1->mkdocs==0.17.3)
  Downloading https://files.pythonhosted.org/packages/98/7b/ff284bd8c80654e471b769062a9b43cc5d03e7a615048d96f4619df8d420/MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.5.0->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/df/1c/59cca3abf96f991f2ec3131a4ffe72ae3d9ea1f5894abe8a9c5e3c77cfee/urllib3-1.24.2-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.5.0->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.5.0->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.5.0->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Building wheels for collected packages: mock, future, PyYAML, tornado
  Building wheel for mock (setup.py): started
  Building wheel for mock (setup.py): finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/.cache/pip/wheels/7e/72/92/744b532c779242b57aab4bcba80c312b30c069bbd60025e7e6
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/.cache/pip/wheels/0c/61/d2/d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/.cache/pip/wheels/ad/56/bc/1522f864feb2a358ea6f1a92b4798d69ac783a28e80567a18b
  Building wheel for tornado (setup.py): started
  Building wheel for tornado (setup.py): finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/.cache/pip/wheels/72/bf/f4/b68fa69596986881b397b18ff2b9af5f8181233aadcc9f76fd
Successfully built mock future PyYAML tornado
Installing collected packages: Pygments, setuptools, docutils, mock, pillow, alabaster, future, commonmark, snowballstemmer, sphinxcontrib-htmlhelp, pytz, babel, sphinxcontrib-qthelp, sphinxcontrib-devhelp, sphinxcontrib-jsmath, sphinxcontrib-serializinghtml, pyparsing, six, packaging, MarkupSafe, Jinja2, imagesize, urllib3, certifi, chardet, idna, requests, sphinxcontrib-applehelp, sphinx, recommonmark, click, PyYAML, tornado, livereload, Markdown, mkdocs
  Found existing installation: setuptools 40.6.3
    Uninstalling setuptools-40.6.3:
      Successfully uninstalled setuptools-40.6.3
Successfully installed Jinja2-2.10.1 Markdown-3.1 MarkupSafe-1.1.1 PyYAML-5.1 Pygments-2.3.1 alabaster-0.7.12 babel-2.6.0 certifi-2019.3.9 chardet-3.0.4 click-7.0 commonmark-0.8.1 docutils-0.14 future-0.17.1 idna-2.8 imagesize-1.1.0 livereload-2.6.0 mkdocs-0.17.3 mock-1.0.1 packaging-19.0 pillow-5.4.1 pyparsing-2.4.0 pytz-2019.1 recommonmark-0.5.0 requests-2.21.0 setuptools-40.9.0 six-1.12.0 snowballstemmer-1.2.1 sphinx-2.0.1 sphinxcontrib-applehelp-1.0.1 sphinxcontrib-devhelp-1.0.1 sphinxcontrib-htmlhelp-1.0.2 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.2 sphinxcontrib-serializinghtml-1.1.3 tornado-4.5.3 urllib3-1.24.2

[rtd-command-info] start-time: 2019-04-26T12:04:48.872518Z, end-time: 2019-04-26T12:04:48.939214Z, duration: 0, exit-code: 0
cat mkdocs.yml
copyright: Copyright &copy; 2019 Braghim Sistemas
docs_dir: /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/checkouts/version2.0/docs
extra_css:
- css/extra-style.css
- https://assets.readthedocs.org/static/css/badge_only.css
- https://assets.readthedocs.org/static/css/readthedocs-doc-embed.css
extra_javascript:
- readthedocs-data.js
- https://assets.readthedocs.org/static/core/js/readthedocs-doc-embed.js
- https://assets.readthedocs.org/static/javascript/readthedocs-analytics.js
google_analytics: null
nav:
- Introduction:
  - index.md
  - SuitUp 1 Compatibility: compatibility/index.md
- User Guide:
  - Getting Started: getting-started/index.md
- About:
  - License: about/LICENSE.md
plugins:
- search
repo_url: https://github.com/braghimsistemas/suitup-php
site_author: Braghim Sistemas
site_description: Awesome PHP Framework with high productivity
site_name: Suitup Framework
theme:
  highlightjs: true
  hljs_languages:
  - yaml
  - php
  name: readthedocs

[rtd-command-info] start-time: 2019-04-26T12:04:48.998580Z, end-time: 2019-04-26T12:04:49.473188Z, duration: 0, exit-code: 1
/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/bin/python -m mkdocs build --clean --site-dir _build/html --config-file /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/checkouts/version2.0/mkdocs.yml
WARNING -  Config value: 'nav'. Warning: Unrecognised configuration name: nav 
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/suitup-php/checkouts/version2.0/_build/html 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/mkdocs/nav.py", line 337, in _follow
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.7.1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.pyenv/versions/3.7.1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/mkdocs/__main__.py", line 194, in <module>
    cli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/mkdocs/commands/build.py", line 213, in build_pages
    site_navigation = nav.SiteNavigation(config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/mkdocs/nav.py", line 44, in __init__
    config, self.url_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/suitup-php/envs/version2.0/lib/python3.7/site-packages/mkdocs/nav.py", line 392, in _generate_site_navigation
    config_line, url_context, config):
RuntimeError: generator raised StopIteration
```

**Comment by waylan** [comment]
The `nav` config option is new as of version 1.0. Previously, it was called `pages`. My best guess is that the Read the Docs service is still using an older version of MkDocs. In fact, I see that `mkdocs==0.17.3` appears in your log message. I would suggest following up with them.

**Comment by marcobraghim** [comment]
It works, thanks. But I'm just little afraid now about do not be warned when it updates.

**Comment by waylan** [comment]
>  But I'm just little afraid now about do not be warned when it updates.

That is a reasonable concern, however, as explained in the [release notes][1] for 1.0 (emphasis added):

> In the current release, any configuration which includes a `pages` setting, but no `nav` setting, the `pages` configuration will be copied to `nav` and **a warning will be issued.** However, in a future release, that may no longer happen. If both `pages` and `nav` are defined, the `pages` setting will be ignored.

Therefore, if/when readthedocs upgrades, your builds will still build fine, but generate a warning, informing you to update your config.

[1]: https://www.mkdocs.org/about/release-notes/#internal-refactor-of-pages-files-and-navigation

**Comment by waylan** [comment]
Also, I believe there is a way to get readthedocs to use whichever version of MkDocs you set. You might want to try that and then you can upgrade now.
