### ISSUE TITLE
Issue with HTML to Markdown converted with pandoc --> ERROR   -  Error reading page 'index.md': Invalid IPv6 URL

### ISSUE THREAD

**Issue by Tset-Noitamotua** [mkdocs/mkdocs#1818]
I created an index.md file with pandoc (from html with url - example below) and started local dev server `mkdocs serve` which leaves me with the following error:

>    ERROR   -  Error reading page 'index.md': Invalid IPv6 URL

```
WARNING -  Documentation file 'index.md' contains a link to 'h | ge | /library/functions.html' which is not found in the documentation files. 
WARNING -  Documentation file 'index.md' contains a link to 'h | ttps | le | rg/library/functions.html' which is not found in the documentation files. 
ERROR   -  Error reading page 'index.md': Invalid IPv6 URL 
Traceback (most recent call last):
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/mkdocs/__main__.py", line 134, in serve_command
    livereload=livereload
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 119, in serve
    config = builder()
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 114, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/mkdocs/commands/build.py", line 177, in _populate_page
    page.render(config, files)
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/mkdocs/structure/pages.py", line 184, in render
    self.content = md.convert(self.markdown)
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/markdown/core.py", line 272, in convert
    newRoot = treeprocessor.run(root)
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/mkdocs/structure/pages.py", line 209, in run
    new_url = self.path_to_url(url)
  File "/home/learn/projects/GITHUB/mkdocs-rf-userguide/venv/lib/python3.7/site-packages/mkdocs/structure/pages.py", line 215, in path_to_url
    scheme, netloc, path, params, query, fragment = urlparse(url)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 368, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 456, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

Here is the command to create the same index.md I did and to reproduce the issue:
> requires latest [pandoc](https://github.com/jgm/pandoc/releases) to be installed

```
pandoc -f html -t markdown \
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html \
-o index.md --extract-media=media

# pandoc version
pandoc --version
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
```
here is example of result

![image](https://user-images.githubusercontent.com/5635462/59980724-15b42180-95fa-11e9-9882-6a62dc69c8f3.png)

Originally I reported this [issue](https://github.com/jgm/pandoc/issues/5614) on pandoc's issue tracker.

**Comment by waylan** [comment]
The error indicates that there is an invalid ipv6 URL in the Markdown. Have you tried narrowing down which URL results in the error? Could you provide an example of the URL.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tset-Noitamotua** [comment]
Nope. But the guys from pandoc suggested a [workaround](https://github.com/jgm/pandoc/issues/5614#issuecomment-504796571) that seems to work.

Disable pandocs grid table extension:
```
pandoc -f html -t markdown-grid_tables \
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html \
-o index.md --extract-media=media
```

`mkdocs serve` works with created .md file from above command.

I guess this does not help much to find what/where the failure happens that makes mkdocs fail. But as I am not really happy with the result of the conversion from html to markdown anyway I won't continue this path. So please feel free to close this issue.

**Comment by waylan** [comment]
Interesting. Yes, Pandoc's [grid-tables][0] are not supported by Python-Markdown. Only Pandoc's [pipe tables][1] are [supported][2]. If you need table support, you might want to try using Pandoc's pipe tables.

As disabling grid tables removed the problem, I'm assuming that the grid table syntax was confusing the Markdown parser, resulting in the error. However, without a sample document, its impossible to say for sure. I'm closing this due to a lack of relevant information. If the problem persists, feel free to leave a comment with the relevant information and we'll take another look.

[0]: https://pandoc.org/MANUAL.html#grid_tables
[1]: https://pandoc.org/MANUAL.html#extension-pipe_tables
[2]: https://python-markdown.github.io/extensions/

**Comment by waylan** [comment]
So I took another look at your original comment and noticed that you included a screenshot of a sample document. I ignored the screenshot before as they are generally not helpful (you should always provide the actual text in a code block). In any event, I see that the grid table contains a link which is broken into two lines. However, pipe tables do not support multi-line table cells so Markdown is not properly parsing the link, which is causing the error. Again, I expect that using pipe tables would resolve the issue.

**Comment by Tset-Noitamotua** [comment]
Find attached the example file (it's huge) which I generated with pandoc with the following command:

```
pandoc -f html -t markdown+pipe_tables \
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html \
-o index.md --extract-media=media
```

The `+pipe_tables` part tells pandoc to use pipe table. But I am not sure if this deactivates grid tables at the same time (I am not a pandoc expert - just started using it yesterday). Mkdocs fails to render the attached example files below with the above reported error:

[rf-userguid-converted-to-md-with-pandoc.zip](https://github.com/mkdocs/mkdocs/files/3322125/rf-userguid-converted-to-md-with-pandoc.zip)

Here is another command which deactivates grid tables for sure:
```
foobar
```
The next attached file is rendered by mkdocs without error.
[userguide-md-not-failing.zip](https://github.com/mkdocs/mkdocs/files/3322177/userguide-md-not-failing.zip)
