### ISSUE TITLE
markdown_extensions doesn't respect the indentation style

### ISSUE THREAD

**Issue by noraj** [mkdocs/mkdocs#1833]
## Description

I used two spaces for my mkdocs.yml config file:

```yaml
site_name: 'XXX'
site_description: ''
site_author: 'XXX'
site_url: 'XXX'
docs_dir: 'docs'

nav:
  - Home: 'index.md'
  - 'Cheat Sheets':
    - 'Cheat Sheets/index.md'
  - 'Tools':
    - 'Tools/index.md'
  - About: 'about.md'
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'green'
    accent: 'light green'
  logo: 'img/android-chrome-512x512.png'
  favicon: 'img/favicon.ico'
  feature:
    tabs: false

extra:
  manifest: 'site.webmanifest'

# Copyright
copyright: "XXX"
```

By adding this (4 spaces indentation) it works:

```yaml
markdown_extensions:
    - toc:
        permalink: True
```

But by adding this (2 spaces indentation) it doesn't work:

```yaml
markdown_extensions:
  - toc:
    permalink: True
```

I'm getting the following error from a cold start:

```
$ mkdocs serve
INFO    -  Building documentation... 
ERROR   -  Config value: 'markdown_extensions'. Error: Invalid Markdown Extensions configuration 

Aborted with 1 Configuration Errors!
```

or this error with livereload:

```
[E 190724 22:36:25 ioloop:801] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/tornado/ioloop.py", line 1229, in _run
        return self.callback()
      File "/usr/lib/python3.7/site-packages/livereload/handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/usr/lib/python3.7/site-packages/livereload/watcher.py", line 93, in examine
        func()
      File "/usr/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 107, in builder
        site_dir=site_dir
      File "/usr/lib/python3.7/site-packages/mkdocs/config/base.py", line 210, in load_config
        "Aborted with {0} Configuration Errors!".format(len(errors))
    mkdocs.exceptions.ConfigurationError: Aborted with 1 Configuration Errors!
```

## Environment

```
$ mkdocs --version
mkdocs, version 1.0.4 from /usr/lib/python3.7/site-packages/mkdocs (Python 3.7
```

**Comment by waylan** [comment]
This is an upstream issue. The YAML library returns difference result for each input:

```py
>>> y = '''
... markdown_extensions:
...     - toc:
...         permalink: True
... '''
>>> yaml_load(y)
{u'markdown_extensions': [{u'toc': {u'permalink': True}}]}
>>> y = '''
... markdown_extensions:
...   - toc:
...     permalink: True
... '''
>>> yaml_load(y)
{u'markdown_extensions': [{u'toc': None, u'permalink': True}]}
```

I expect that is probably the correct behavior according to the YAML spec. However, we only accept the first, not the second. As they are two different things, I don't see this as a bug.

**Comment by noraj** [comment]
Why is it (2 space indent) working, let's say for nav and not for markdown_extensions?

**Comment by waylan** [comment]
In the case of the `nav`, the nested item is also a list item (starts with a `-`), whereas in the extensions case, the nested item is not a list item (does not start with a `-`). In other words, the difference you are observing is a difference built into and defined by the YAML spec. We just use the PyYAML library which abides by the spec. This is not something we can change. If you want to change the behavior, you will need to take this upstream and propose a change to the YAML spec.

**Comment by noraj** [comment]
Ok, I didn't know that.

**Comment by philshem** [comment]
Issue is closed, but I had the same problem, and found putting `toc` before the other extensions worked.

Two working examples:

```yaml
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - codehilite
  - pymdownx.superfences
```

and


```yaml
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - codehilite
    - pymdownx.superfences
```

and my versions

```python
Python 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mkdocs
>>> print(mkdocs.__version__)
1.1.2
```

**Comment by ycd** [comment]
@philshem how did you fix it? I'm having the same problem.

**Comment by philshem** [comment]
Can you try copy/pasting my code snippets as they are?

Both should be working

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
