### ISSUE TITLE
 UnicodeDecodeError: 'utf-8' codec can't decode byte 

### ISSUE THREAD

**Issue by AiltonSilvaSC** [mkdocs/mkdocs#1892]
```
ERROR   -  Encoding error reading file: Lord of the Mysteries\Index.md
[E 191022 12:29:44 ioloop:909] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "c:\users\administrador\appdata\local\programs\python\python37-32\lib\site-packages\tornado\ioloop.py", line 907, in _run
        return self.callback()
      File "c:\users\administrador\appdata\local\programs\python\python37-32\lib\site-packages\livereload\handlers.py", line 69, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "c:\users\administrador\appdata\local\programs\python\python37-32\lib\site-packages\livereload\watcher.py", line 105, in examine
        func()
      File "c:\users\administrador\appdata\local\programs\python\python37-32\lib\site-packages\mkdocs\commands\serve.py", line 114, in builder
        build(config, live_server=live_server, dirty=dirty)
      File "c:\users\administrador\appdata\local\programs\python\python37-32\lib\site-packages\mkdocs\commands\build.py", line 274, in build
        _populate_page(file.page, config, files, dirty)
      File "c:\users\administrador\appdata\local\programs\python\python37-32\lib\site-packages\mkdocs\commands\build.py", line 170, in _populate_page
        page.read_source(config)
      File "c:\users\administrador\appdata\local\programs\python\python37-32\lib\site-packages\mkdocs\structure\pages.py", line 130, in read_source
        source = f.read()
      File "c:\users\administrador\appdata\local\programs\python\python37-32\lib\codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
      File "c:\users\administrador\appdata\local\programs\python\python37-32\lib\encodings\utf_8_sig.py", line 69, in _buffer_decode
        return codecs.utf_8_decode(input, errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 124: invalid continuation byte
[I 191022 12:30:40 server:318] Shutting down...

```

**Comment by waylan** [comment]
It would appear that you have not saved your file `Lord of the Mysteries\Index.md` as UTF-8. All documents must be saved as UTF-8 to ensure that MkDocs can read them properly. See the documentation for your editor for how to ensure your documents are properly encoded.

**Comment by AiltonSilvaSC** [comment]
thanks.

**Comment by MaximilianKohler** [comment]
I experienced this error after running the cmd `curl 'https://jaspervdj.be/lorem-markdownum/markdown.txt' > docs/about.md` during the getting started tut https://www.mkdocs.org/getting-started/#adding-pages. **Solution** was to delete the file that was automatically created and manually create my own. 

I just tested and if using notepad++ you can see under the `encoding` menu that when using the curl cmd it defaults the file to `UTF-16 BOM`, and the one I made myself is `UTF-8`. Not sure why it defaulted to the other type, but changing in that menu would probably solve the problem too.

**Comment by oprypin** [comment]
@MaximilianKohler Did you by chance use PowerShell on Windows for those operations?
Where `curl` is an alias to `Invoke-WebRequest`

**Comment by MaximilianKohler** [comment]
I did use PowerShell on Windows.

**Comment by oprypin** [comment]
OK so that's what produces UTF-16.
I don't think when those instructions were written, the author foresaw that the suggested command would "work" anywhere except Bash.
