### ISSUE TITLE
TypeError: Object of type 'date' is not JSON serializable when using mkdocs serve

### ISSUE THREAD

**Issue by BrianSidebotham** [mkdocs/mkdocs#1961]
```brian@brian-2920x:~/github/valvers/valvers-mkdocs$ /opt/wsl/bin/mkdocs --version
mkdocs, version 1.0.4 from /opt/wsl/lib/python3.6/site-packages/mkdocs (Python 3.6)
```
When generating the docs for my website (`mkdocs serve`) `mkdocs` barfs with the following stacktrace:

```
brian@brian-2920x:~/github/valvers/valvers-mkdocs$ /opt/wsl/bin/mkdocs serve
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - v6manta.md
  - open_software/index.md 
Traceback (most recent call last):
  File "/opt/wsl/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/wsl/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/wsl/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/wsl/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/wsl/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/wsl/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/wsl/lib/python3.6/site-packages/mkdocs/__main__.py", line 134, in serve_command
    livereload=livereload
  File "/opt/wsl/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 119, in serve
    config = builder()
  File "/opt/wsl/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 114, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/opt/wsl/lib/python3.6/site-packages/mkdocs/commands/build.py", line 298, in build
    config['plugins'].run_event('post_build', config)
  File "/opt/wsl/lib/python3.6/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/opt/wsl/lib/python3.6/site-packages/mkdocs/contrib/search/__init__.py", line 68, in on_post_build
    search_index = self.search_index.generate_search_index()
  File "/opt/wsl/lib/python3.6/site-packages/mkdocs/contrib/search/search_index.py", line 106, in generate_search_index
    data = json.dumps(page_dicts, sort_keys=True, separators=(',', ':'))
  File "/opt/wsl/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/wsl/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/wsl/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/wsl/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'date' is not JSON serializable
```

The `mkdocs.yml` configuration file looks a bit like (I've abbreviated it a bit):

```
brian@brian-2920x:~/github/valvers/valvers-mkdocs$ cat mkdocs.yml 
site_name: valvers.com
site_author: 'Brian Sidebotham'
site_url: 'https://www.valvers.com'
copyright: 'Copyright &copy; 2002-2020 Brian Sidebotham'

nav:
    - Home: index.md
    - 'V6 Manta':
        - Index: v6manta/index.md
        - 2003-07-28: v6manta/2003-07-28-.md
        ...

    - 'Open Software':
        ...
theme:
    name: material
    palette:
        primary: 'blue grey'
        accent: 'deep orange'
    feature:
        tabs: true
    markdown_extensions:
      - admonition
      - codehilite:
          guess_lang: false
      - toc:
```

**Comment by BrianSidebotham** [comment]
Quoting the date to ensure it's a string appears to fix this problem:

```
brian@brian-2920x:~/github/valvers/valvers-mkdocs$ cat mkdocs.yml 
site_name: valvers.com
site_author: 'Brian Sidebotham'
site_url: 'https://www.valvers.com'
copyright: 'Copyright &copy; 2002-2020 Brian Sidebotham'

nav:
    - Home: index.md
    - 'V6 Manta':
        - Index: v6manta/index.md
        - '2003-07-28': v6manta/2003-07-28-.md
        ...
```

**Comment by waylan** [comment]
Right, YAML infers types, so you need to force a string with quotes. This is working as it should.

Although, perhaps we should enforce titles being strings in the config validation and raise a validation error if not.

**Comment by oprypin** [comment]
Huh so the issue is doubly fixed now. Not only is there validation to accept only strings, as was mentioned,
but actually the issue was already fixed earlier: it seems that YAML no longer tries to recognize dates for some reason.

```bash
git bisect reset; git bisect start && git bisect new master && git bisect old 1.1.2 && git bisect run bash -c '! mkdocs build -f test.yml'
```
e1b77ab66e8305b5f0373b4842b50d2618390a96 is the first new commit

Not sure how that commit happens to fix it but it does.
Must be https://github.com/mkdocs/mkdocs/commit/e1b77ab66e8305b5f0373b4842b50d2618390a96#diff-c415bde0ad17e1a44da9e86aabf2f6ee0c21fd38ae9c459bea6589bcc61d0efbL102-R102
