### ISSUE TITLE
Specifying empty sub-categories under `nav` throws error

### ISSUE THREAD

**Issue by NobleDraconian** [mkdocs/mkdocs#1964]
Currently, as of mkdocs version `1.0.4`, having a config like this will cause the following error to occur:
```yaml
# Navigation
nav:
  - Home : index.md
  - API :
    - Server : 
      - Services : 
    - Client :
      - Controllers :
  - Test : Test.md
```
```
INFO    -  Building documentation...
INFO    -  Cleaning site directory
Traceback (most recent call last):
  File "c:\users\binar\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Binar\AppData\Local\Programs\Python\Python37\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\__main__.py", line 134, in serve_command
    livereload=livereload
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\serve.py", line 119, in serve
    config = builder()
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\serve.py", line 114, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\build.py", line 267, in build
    nav = get_navigation(files, config)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 104, in get_navigation
    items = _data_to_navigation(nav_config, files, config)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 162, in _data_to_navigation
    for item in data
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 162, in <listcomp>
    for item in data
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 155, in _data_to_navigation
    for key, value in data.items()
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 155, in <listcomp>
    for key, value in data.items()
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 162, in _data_to_navigation
    for item in data
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 162, in <listcomp>
    for item in data
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 155, in _data_to_navigation
    for key, value in data.items()
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 155, in <listcomp>
    for key, value in data.items()
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 162, in _data_to_navigation
    for item in data
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 162, in <listcomp>
    for item in data
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 155, in _data_to_navigation
    for key, value in data.items()
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 155, in <listcomp>
    for key, value in data.items()
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\nav.py", line 165, in _data_to_navigation
    file = files.get_file_from_path(path)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\structure\files.py", line 33, in get_file_from_path
    return self.src_paths.get(os.path.normpath(path))
  File "c:\users\binar\appdata\local\programs\python\python37\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I'm using python 3.7.6, Win10 x64.

**Comment by waylan** [comment]
Yes, that should throw an error. However, it should be throwing a `ValidationError` when we validate the config, not a `TypeError` later when we attempt to build the global navigation. A navigation (sub)section must contain a list of pages or subsections. It cannot contain a `None` value as two of yours does (specifically `Services` and `Controllers`).

**Comment by oprypin** [comment]
Huh so the issue is doubly fixed now. Not only is there validation to accept only strings, as was mentioned,
but actually the issue was already fixed earlier: it seems that YAML no longer tries to recognize dates for some reason.

```bash
git bisect reset; git bisect start && git bisect new master && git bisect old 1.1.2 && git bisect run bash -c '! mkdocs build -f test.yml'
```
e1b77ab66e8305b5f0373b4842b50d2618390a96 is the first new commit

Not sure how that commit happens to fix it but it does.

**Comment by oprypin** [comment]
Oops, I commented in the wrong place, will delete this comment

**Comment by oprypin** [comment]
Now the error is not a stacktrace but a proper error during validation:
```
Config value: 'nav'. Error: Expected nav to be a list, got None
```
