### ISSUE TITLE
Deploy mkdocs in IIS

### ISSUE THREAD

**Issue by virtualdvid** [mkdocs/mkdocs#1973]
Hi, Is there a way to deploy `mkdocs` in Windows IIS? I have been trying but I'm getting tons of error here the last one:

```
Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "G:\PPVMF\DEV\PYDOC\pydoc\.venv\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "G:\PPVMF\DEV\PYDOC\pydoc\.venv\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "G:\PPVMF\DEV\PYDOC\pydoc\.venv\Lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File ".\run.py", line 51, in <module>
  File "G:\PPVMF\DEV\PYDOC\pydoc\.venv\lib\site-packages\mkdocs\commands\serve.py", line 124, in serve
    _livereload(host, port, config, builder, site_dir)
  File "G:\PPVMF\DEV\PYDOC\pydoc\.venv\lib\site-packages\mkdocs\commands\serve.py", line 58, in _livereload
    server.serve(root=site_dir, host=host, port=port, restart_delay=0)
  File "G:\PPVMF\DEV\PYDOC\pydoc\.venv\lib\site-packages\livereload\server.py", line 299, in serve
    port, host, liveport=liveport, debug=debug, live_css=live_css)
  File "G:\PPVMF\DEV\PYDOC\pydoc\.venv\lib\site-packages\livereload\server.py", line 253, in application
    app.listen(port, address=host)
  File "G:\PPVMF\DEV\PYDOC\pydoc\.venv\lib\site-packages\tornado\web.py", line 2112, in listen
    server.listen(port, address)
  File "G:\PPVMF\DEV\PYDOC\pydoc\.venv\lib\site-packages\tornado\tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "G:\PPVMF\DEV\PYDOC\pydoc\.venv\lib\site-packages\tornado\netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

Is there a way to override the `port` in `from mkdocs.commands.serve import serve`?

I'm loss here. Thanks!!!

**Comment by waylan** [comment]
The included server is indented for development purposes only. It is not intended to be used as a production server. Proxying to the dev server is not supported. Instead, to deploy, you should be copying the built files (in the `site` dir) to your server's static file directory.

**Comment by virtualdvid** [comment]
@waylan Thanks for your soon replay!! Yeah I was doing it totally wrong. I have a question now. How suppose to be the folder structure to see the site. I have a Flask app already running. here the tree dir:

```
app
    -> app_core
        -> core
             -> static
                 ->site <-mkdocs files after build
             -> templates
         run.py
```
where should I locate the `docs` folder with the `.md` files, the html(s) (index, 404, search) and the `yml` file?

I put a route to `index.html` in `main/routes.py` but it is coming without the `css` format :(

**Comment by waylan** [comment]
You would keep your source files separate. When you are ready to deploy, you would run the `mkdocs build` command which would update the local `site` dir. Then to deploy, you would copy the contents of your local `site` dir to the `static` dir of your server. This is outlined in more detail in the [docs][1].

As a reminder, MkDocs is a *static site generator*. It is not intended to be run on the server.

[1]: https://www.mkdocs.org/user-guide/deploying-your-docs/#other-providers
