### ISSUE TITLE
Conflict between Markdown 3.2, pymdown extension and Material theme.

### ISSUE THREAD

**Issue by huseyin** [mkdocs/mkdocs#1976]
I have a documentation site with [this configurations](https://github.com/omu/nokul/blob/develop/.mkdocs.yml) on Netlify. In the recent deploys, I've started to get the following error during the build step.

```
12:19:33 PM: Traceback (most recent call last):
12:19:33 PM:   File "/opt/buildhome/python3.5/bin/mkdocs", line 10, in <module>
12:19:33 PM:     sys.exit(cli())
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/click/core.py", line 764, in __call__
12:19:33 PM:     return self.main(*args, **kwargs)
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/click/core.py", line 717, in main
12:19:33 PM:     rv = self.invoke(ctx)
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
12:19:33 PM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/click/core.py", line 956, in invoke
12:19:33 PM:     return ctx.invoke(self.callback, **ctx.params)
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/click/core.py", line 555, in invoke
12:19:33 PM:     return callback(*args, **kwargs)
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/mkdocs/__main__.py", line 162, in build_command
12:19:33 PM:     site_dir=site_dir
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/mkdocs/config/base.py", line 197, in load_config
12:19:33 PM:     errors, warnings = cfg.validate()
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/mkdocs/config/base.py", line 115, in validate
12:19:33 PM:     post_failed, post_warnings = self._post_validate()
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/mkdocs/config/base.py", line 95, in _post_validate
12:19:33 PM:     config_option.post_validation(self, key_name=key)
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/mkdocs/config/config_options.py", line 432, in post_validation
12:19:33 PM:     config[key_name] = theme.Theme(**theme_config)
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/mkdocs/theme.py", line 48, in __init__
12:19:33 PM:     self._load_theme_config(name)
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/mkdocs/theme.py", line 78, in _load_theme_config
12:19:33 PM:     theme_dir = utils.get_theme_dir(name)
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/mkdocs/utils/__init__.py", line 278, in get_theme_dir
12:19:33 PM:     return os.path.dirname(os.path.abspath(theme.load().__file__))
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2433, in load
12:19:33 PM:     self.require(*args, **kwargs)
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2456, in require
12:19:33 PM:     items = working_set.resolve(reqs, env, installer, extras=self.extras)
12:19:33 PM:   File "/opt/buildhome/python3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 791, in resolve
12:19:33 PM:     raise VersionConflict(dist, req).with_context(dependent_req)
12:19:33 PM: pkg_resources.VersionConflict: (Markdown 3.2 (/opt/buildhome/python3.5/lib/python3.5/site-packages), Requirement.parse('markdown<3.2'))
```

I'm not sure what the root cause of this unexpected behavior is. Also, It is not a reproducible error because I can't replicate it with the same configurations and versions in my local.

### Environment

- OS version: Ubuntu 16.04 Xenial
- Python version: 3.5
- Mkdocs version: 1.0.4

**Comment by facelessuser** [comment]
You are using the material theme, please see here: https://github.com/squidfunk/mkdocs-material/issues/1450.

**Comment by huseyin** [comment]
Thanks a lot @facelessuser That helped me.

**Comment by facelessuser** [comment]
No problem. While we tried to avoid hiccups, pip's bad dependency resolution caused an issue anyways...sigh. Glad this helped though.

**Comment by huseyin** [comment]
i completely agree with your thoughts on pip's dependency management. it could be much better

**Comment by waylan** [comment]
I've updated the title of this issue to better reflect the problem. Also, I am closing this as this is an issue to either the pymdown extension, the Material theme or both.
