### ISSUE TITLE
Error while executing gh-deploy on Windows

### ISSUE THREAD

**Issue by johnmeredith** [mkdocs/mkdocs#1987]
I fear this is a duplicate of ([#722](https://github.com/mkdocs/mkdocs/issues/722)) but this is hitting me now. I tried with Python 3.8 but got the error where MKDocs would not serve. Downgrade to 3.7 fixed that but the gh-deploy command will not work now. 

```
PS D:\repo\shared-meds-docs> mkdocs gh-deploy
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: D:\repo\shared-meds-docs\site
Traceback (most recent call last):
  File "c:\users\me\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\me\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\mkdocs\__main__.py", line 187, in gh_deploy_command
    gh_deploy.gh_deploy(cfg, message=message, force=force, ignore_version=ignore_version)
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\gh_deploy.py", line 82, in gh_deploy
    if not _is_cwd_git_repo():
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\gh_deploy.py", line 18, in _is_cwd_git_repo
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\users\me\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\me\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I've read Python 2.7 fixes all this but...it's version 2.7! ;-) Any ideas? 
Oh and this is Windows 10

**Comment by waylan** [comment]
It appears that the error occurs when MkDocs attempts to call git.  Do you have the git command line tool installed and available?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by johnmeredith** [comment]
No – but I have just installed via Choco and now get a different issue:

```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: D:\Projects\Shared-Medications-Record\site
ERROR   -  Cannot deploy - this directory does not appear to be a git repository
WARNING -  Version check skipped: No version specificed in previous deployment.
INFO    -  Copying 'D:\Projects\Shared-Medications-Record\site' to 'gh-pages' branch and pushing to GitHub.
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code exec(code, run_globals)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\click\core.py", line 764, in __call__return self.main(*args, **kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\click\core.py", line 717, in main rv = self.invoke(ctx)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\click\core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\click\core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\click\core.py", line 555, in invoke return callback(*args, **kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\__main__.py", line 187, in gh_deploy_command gh_deploy.gh_deploy(cfg, message=message, force=force, ignore_version=ignore_version)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\commands\gh_deploy.py", line 101, in gh_deploy remote_branch, force)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\utils\ghp_import.py", line 168, in ghp_import run_import(directory, branch, message, nojekyll)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\utils\ghp_import.py", line 152, in run_import add_file(pipe, fpath, gpath)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\utils\ghp_import.py", line 125, in add_file write(pipe, enc(data))
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\utils\ghp_import.py", line 44, in write pipe.stdin.write(data)
OSError: [Errno 22] Invalid argument
```
Thinking it could be device security, I ‘ve tried to do the same process on a different laptop hence why the path in the above is different.

**Comment by johnmeredith** [comment]
No – but I have just installed via Choco and now get a different issue:

```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: D:\Projects\Shared-Medications-Record\site
ERROR   -  Cannot deploy - this directory does not appear to be a git repository
WARNING -  Version check skipped: No version specificed in previous deployment.
INFO    -  Copying 'D:\Projects\Shared-Medications-Record\site' to 'gh-pages' branch and pushing to GitHub.
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code exec(code, run_globals)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\click\core.py", line 764, in __call__return self.main(*args, **kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\click\core.py", line 717, in main rv = self.invoke(ctx)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\click\core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\click\core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\click\core.py", line 555, in invoke return callback(*args, **kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\__main__.py", line 187, in gh_deploy_command gh_deploy.gh_deploy(cfg, message=message, force=force, ignore_version=ignore_version)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\commands\gh_deploy.py", line 101, in gh_deploy remote_branch, force)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\utils\ghp_import.py", line 168, in ghp_import run_import(directory, branch, message, nojekyll)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\utils\ghp_import.py", line 152, in run_import add_file(pipe, fpath, gpath)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\utils\ghp_import.py", line 125, in add_file write(pipe, enc(data))
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\mkdocs\utils\ghp_import.py", line 44, in write pipe.stdin.write(data)
OSError: [Errno 22] Invalid argument
```
Thinking it could be device security, I ‘ve tried to do the same process on a different laptop hence why the path in the above is different.

**Comment by waylan** [comment]
You need to have the git tool installed and then you must run the command from within a git repository which is properly configured with a remote. Once you have those requirements met, please report back with any issues you experience with the `mkdocs gh-deploy` command.

**Comment by Atlas-Night-Out** [comment]
I have the same issue but on using Git I get a different error now, fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by waylan** [comment]
Again, you need to have git properly configured and be able to push to the host before attempting to use our wrapper. Under the hood, we just call basic git commands, so if those commands won't work, then there is nothing we can do.

**Comment by Atlas-Night-Out** [comment]
thanks waylan but what is the process I have now added a ssh key correctly but unable to commit or should I say unable to get files made by MKdocs into github. keep getting this now and I do not understand it! ERROR   -  Failed to deploy to GitHub with error:
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by waylan** [comment]
`origin` is usually the name of the `remote`. You need to ensure your `remote` is configured correctly. If you have not set any remotes, then you need to do that first. If the remote is named something other than `origin` then you need to tell MkDocs what that is using the Mkdocs' `--remote` option. You can use the `git remote` command to obtain the existing config and make changes to it.

**Comment by Atlas-Night-Out** [comment]
not at all understanding you! Remote what is it where is it? I have never set anythign up in Github before this! I'm more in on web building then this! and found MKdocs really easy to do taht process but to get it to Github its a nightmare. I need a little more understand of what is going on. I would configure remote if I know what it was. I also do not know if this is a folder I need to make in my local MKdocs Project? `my-project/
    mkdocs.yml
    docs/
orgname.github.io/`

**Comment by pawamoy** [comment]
@Atlas-Night-Out hi! You should:

1. create a repository on GitHub using the web interface
2. [configure your SSH key for your account](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
3. clone your repository locally: `git clone git@github.com:Atlas-Night-Out/your-project.git`
4. use git and mkdocs normally

**Comment by Atlas-Night-Out** [comment]
@pawamoy Thank you for the help,on this! I have done this now just not sure where to copy my docs folder too on the clone? will it be within the .git folder?

**Comment by pawamoy** [comment]
You're welcome! Nope, the .git folders is used by git itself, you should not put arbitrary files into it. Just put your docs folder is your repository root (i.e. next to .git/).

**Comment by Atlas-Night-Out** [comment]
@pawamoy for your help and the help docs link you sent me is very helpful and useful starting to get a little more on things as I go along like the setup on the website too very easy and clear what to do! I'm not fully to what I want to learn on this process yet to be safe to carry on doing my docs files as I want to see I'm set up correctly first then progress! Thanks! I did at one point try adding the docs folder by hand but it did not run correctly so there must be more to it when we do the commands in Gitbash! I did start at first using Python so not sure which to use now both or just Bash :-)

**Comment by Atlas-Night-Out** [comment]
just noticed already the website needs updating as I tried the git switch experimental and it's changed to checkout experimental :-) love this site though!

**Comment by Atlas-Night-Out** [comment]
When I have done what you say how do I put it back to github in teh correct manner? My copy of it on Github page is nothing like my MKdocs server! when I look at the fills too on github when I look at teh code on Github tehy are not teh same as on my PC's folder. I have done the first process of getting a clone to my pc from github and I have copied teh docs folder over too it!

**Comment by pawamoy** [comment]
You need to learn the basis of git ^^

Now that you copied your folder in your local clone, commit and push it to GitHub:

```
git add .
git commit -m "Add docs folder"
git push
```

You can also deploy your site with `mkdocs gh-deploy`. The site will be served at http://username.github.io/project (where username and project are replaced by your username and the name of your project on GitHub).

**Comment by Atlas-Night-Out** [comment]
so doing it with mkdocs gh-deploy I have to add  the Http ? I'm not fully understanding the mkdoc way to do this but know its a better way if I can get the correct code to do? thanks @pawamoy

**Comment by Atlas-Night-Out** [comment]
@pawamoy 
I have done the process and it says all up to date but the GitHub page is still looking the same and no change in it! I went to the folder where the docs folder is and did a git commit and then a git push and all files have updated just not the GitHub page.

**Comment by Atlas-Night-Out** [comment]
@pawamoy   this is what its suppose to look like [https://cyb-netics.com/user-guide/Nightscout_update/](url) and this is what Gitbub gives me [https://atlas-night-out.github.io/Cyb-Netics-Docs/](url)

**Comment by pawamoy** [comment]
You must use `nav` instead of `pages` in your MkDocs configuration: https://github.com/Atlas-Night-Out/Cyb-Netics-Docs/blob/main/mkdocs.yml

Then your site seems to be a previous version built with another static site generator, or perhaps a builtin GitHub thing.
I guess your `mkdocs gh-deploy` command failed indeed, thus your site was not updated.

> when I try the mkdocs gh-deploy I get a error asking for (publickey) how do I add that?

Could you paste here the exact command you used and its output? There's no reason this command would fail if `git push` works.

**Comment by Atlas-Night-Out** [comment]
@pawamoy  Cyb-Netics-Docs>mkdocs gh-deploy

I have also renamed pages to nav in mkdocs and made no difference. 

Can this have anything to do with the issues?   site' to 'gh-pages' branch and pushing to GitHub. 

seems something like this (The problem was that my website was publishing from the gh-pages branch, but I was pushing my recent changes to the master branch. )

**Comment by Atlas-Night-Out** [comment]
@pawamoy I m trying with Github Desktop and still getting error for Autorcation and this keeps popping up! [https://drive.google.com/file/d/1d7tzvnYPgmnPufbewYuHC4Miq0Ut9VZx/view?usp=sharing](url)

**Comment by pawamoy** [comment]
`git push` seems to work when you are in git bash right? Can you run `mkdocs gh-deploy` in your local clone and *paste the output here* please?

> site' to 'gh-pages' branch and pushing to GitHub.

If the remote branch does not exist, git creates it, that's not the issue here.
And indeed, the *site* (the HTML pages that MkDocs builds) is pushed on the `gh-pages` branch, while your site *sources* (the `docs` folder and `mkdocs.yml`) are generally pushed to the `master` or `main` branch. Everything is correct here.

For the error shown by GitHub desktop, I'd say it's probably the last point: your SSH agent is not started, or the SSH key not added to it, or GitHub desktop doesn't know about it. But before troubleshooting that, we should make it work in git bash.

**Comment by Atlas-Night-Out** [comment]
@pawamoy  no nothing is working git push I get an error tried to clone it again went ok then I copied docs folder over and error again they are not the same at both ends! its not a good start for me learning this! :-)

**Comment by Atlas-Night-Out** [comment]
@pawamoy  I think it might be better deleting it all from GitHub as its never worked anyway but even that task I have not got a clue to removing it clean and then starting again. It seems to have too many errors and conflicts when on pc it's perfect!

**Comment by Atlas-Night-Out** [comment]
@pawamoy  Yes I can do both now with no errors!

**Comment by pawamoy** [comment]
You finally managed to get it to work :slightly_smiling_face:? Perseverance always pays!
If you need more help, please reach out to me on gitter.im or telegram (@pawamoy), as MkDocs is not concerned by git troubleshooting, and we're only generating noise for other contributors/maintainers here :slightly_smiling_face:

**Comment by Atlas-Night-Out** [comment]
@pawamoy no! the web page that GitHub does is nothing like the one I push to githum it's just doing the README.md
 file :-( 

what room in gitter.im is best to join? MKDOCS at a guess :-)  thanks!
