### ISSUE TITLE
Curly brace and hash is causing: Missing end of comment tag

### ISSUE THREAD

**Issue by adamklinkosz** [mkdocs/mkdocs#2033]
When I have a code block in markdown:

```html
<div th:unless="${#bean.method()}">
```

And try to build the mkdocs with `mkdocs build` I get an error:
```
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag
```

This is because of the `{#` sequence in the code block. I don't want to escape the characters because someone might get the example from the markdown, not the built docs, and such value would not work.

**Environment**
Python: `3.8`
MkDocs: `1.0.4` and `1.1`

**Full trace:**
```
ERROR   -  Error reading page 'some-file.md': Missing end of comment tag 
Traceback (most recent call last):
  File "mkdocs", line 10, in <module>
    sys.exit(cli())
  File ".../python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File ".../python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File ".../python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File ".../python3.8/site-packages/mkdocs/__main__.py", line 157, in build_command
    build.build(config.load_config(
  File ".../python3.8/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File ".../python3.8/site-packages/mkdocs/commands/build.py", line 173, in _populate_page
    page.markdown = config['plugins'].run_event(
  File ".../python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File ".../python3.8/site-packages/markdownextradata/plugin.py", line 89, in on_page_markdown
    md_template = Template(markdown)
  File ".../python3.8/site-packages/jinja2/environment.py", line 1031, in __new__
    return env.from_string(source, template_class=cls)
  File ".../python3.8/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File ".../python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File ".../python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File ".../python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 13, in template
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag
```

**Comment by waylan** [comment]
Hmm, the Markdown content is never passed to Jinja as a template. Not sure how that is generating such an error. Are you perhaps using a third party plugin which passes Markdown content through Jinja? In fact, reviewing the traceback I see that the error is called from within a plugin event (from `markdownextradata/plugin.py`). I would suggest taking the issue downstream to that plugin.
