### ISSUE TITLE
MkDocs build fail

### ISSUE THREAD

**Issue by jhfeng** [mkdocs/mkdocs#2052]
I have installed latest py3 MkDocs, but seeing this error. Any one has idea what is wrong ?

$ mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/jfeng/Projects/docs/site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - _snippets/links.md
  - assets/templates/rca-template.md
  - assets/templates/spec-template.md
  - assets/templates/standard-template.md
  - assets/templates/runbooks/alert-template.md
  - assets/templates/runbooks/info-template.md
  - assets/templates/runbooks/troubleshoot-template.md
  - compliance/bcdr/healthcheckv2.md
  - kmk/icd-failures.md
  - kmk/specs/byok.md
  - shared-services/expansion-checklist.md
  - shared-services/hsm-attestation.md
  - shared-services/hsm-ops/rotate-passwords.md
/Users/jfeng/projects/py3env/lib/python3.7/site-packages/pymdownx/superfences.py:634: PymdownxDeprecationWarning:
The tab option in SuperFences has been deprecated in favor of the general purpose 'pymdownx.tabbed' extension.
While you can continue to use this feature for now, it will be removed in the future.
Also be mindful of the class changes, if you require old style classes, please enable the 'legacy_tab_classes' option.

  warnings.warn(MSG_TAB_DEPRECATION, PymdownxDeprecationWarning)

Traceback (most recent call last):
  File "/Users/jfeng/projects/py3env/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/mkdocs/__main__.py", line 159, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/mkdocs/commands/build.py", line 288, in build
    _build_theme_template(template, env, files, config, nav)
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/mkdocs/commands/build.py", line 114, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/mkdocs/commands/build.py", line 93, in _build_template
    output = template.render(context)
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/material/404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/material/base.html", line 108, in top-level template code
    {% block header %}
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/material/base.html", line 109, in block "header"
    {% include "partials/header.html" %}
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/material/partials/header.html", line 7, in top-level template code
    {% include "partials/logo.html" %}
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/material/partials/logo.html", line 5, in top-level template code
    <img src="{{ config.theme.logo | url }}" alt="logo">
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/mkdocs/utils/filters.py", line 14, in url_filter
    return normalize_url(value, page=context['page'], base=context['base_url'])
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/mkdocs/utils/__init__.py", line 223, in normalize_url
    path = path_to_url(path or '.')
  File "/Users/jfeng/projects/py3env/lib/python3.7/site-packages/mkdocs/utils/__init__.py", line 251, in path_to_url
    return '/'.join(path.split('\\'))
AttributeError: 'dict' object has no attribute 'split'

**Comment by waylan** [comment]
It appears that the value passed to the `url` template filter in `material/partials/logo.html` is a `dict` but it should be a string. My best guess is that you have an error in your `theme` configuration in `mkdocs.yml`. Given that you appear to be using the Material theme, you might want to ask for help from that project.

**Comment by jhfeng** [comment]
thanks for the info. I'm closing this now.

**Comment by pawamoy** [comment]
I think it's indeed due to misconfiguration of the Material theme. Upgrade instructions available here: https://squidfunk.github.io/mkdocs-material/releases
