### ISSUE TITLE
TypeError using mkdocs serve with 1.1.1

### ISSUE THREAD

**Issue by mriedem** [mkdocs/mkdocs#2110]
I'm getting this when running `mkdocs serve` with the new 1.1.1 release:

```
Traceback (most recent call last):
  File "/home/osboxes/ibmq/cloud-deployment/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/osboxes/ibmq/cloud-deployment/.venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/osboxes/ibmq/cloud-deployment/.venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/osboxes/ibmq/cloud-deployment/.venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/osboxes/ibmq/cloud-deployment/.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/osboxes/ibmq/cloud-deployment/.venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/osboxes/ibmq/cloud-deployment/.venv/lib/python3.6/site-packages/mkdocs/__main__.py", line 136, in serve_command
    **kwargs
  File "/home/osboxes/ibmq/cloud-deployment/.venv/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 146, in serve
    _livereload(host, port, config, builder, site_dir)
  File "/home/osboxes/ibmq/cloud-deployment/.venv/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 76, in _livereload
    server = config['plugins'].run_event('serve', server, config=config, builder=builder)
  File "/home/osboxes/ibmq/cloud-deployment/.venv/lib/python3.6/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
TypeError: on_serve() got an unexpected keyword argument 'builder'
```

These are the mkdocs package versions in my environment:

```
$ pip freeze | grep mkdocs
mkdocs==1.1.1
mkdocs-git-revision-date-localized-plugin==0.5.2
mkdocs-macros-plugin==0.4.7
mkdocs-material==5.1.5
mkdocs-material-extensions==1.0
```

**Comment by mriedem** [comment]
When I downgraded mkdocs to 1.1 then the error goes away.

**Comment by waylan** [comment]
This is related to #2071. One of your plugins was not created with a forward-thinking approach. We added the `builder` argument, but apparently the plugin did not include `**kwargs` in the list of arguments it accepts. I suggest determining which plugin is the culprit and reporting the bug to them.

**Comment by waylan** [comment]
I just checking the documentation and found [this statement][1]:

> It is good practice to accept keyword arguments as `**kwargs`. In the event that additional keywords are provided to an event in a future version of MkDocs, there will be no need to alter your plugin.

That statement is followed by an example which includes the `**kwargs` argument.

My point is that we can't be responsible for plugin developers failing to follow best practices.

[1]: https://www.mkdocs.org/user-guide/plugins/#on_event_name

**Comment by mriedem** [comment]
@waylan ack thanks for the pointer, looks like this is the plugin we're using that's breaking us:

https://github.com/fralau/mkdocs_macros_plugin/blob/02683b3c4e13a8dd2487ae4834d34553f0e45fcb/macros/plugin.py#L386

I'll move the issue there.

**Comment by mriedem** [comment]
> I'll move the issue there.

In case anyone else comes here it looks like there is already an issue:

https://github.com/fralau/mkdocs_macros_plugin/issues/33

**Comment by fralau** [comment]
The issue on mkdocs/macros is now fixed.

fralau/mkdocs_macros_plugin#33
