### ISSUE TITLE
How to resolve theme name conflict?

### ISSUE THREAD

**Issue by epogrebnyak** [mkdocs/mkdocs#2114]
mkdocs 1.1.2 pick some theme name conflict on Windows. Anyone had a similar issue?

I think the issue materialised after I upgraded dependencies from mkdocs-material requirements.txt

```
d:\github\mkdocs-material>pip show mkdocs
Name: mkdocs
Version: 1.1.2
Summary: Project documentation with Markdown.
Home-page: https://www.mkdocs.org
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: d:\anaconda3\lib\site-packages
Requires: Markdown, livereload, click, Jinja2, tornado, lunr, PyYAML
Required-by: portray, mkdocs-minify-plugin, mkdocs-material

d:\github\mkdocs-material>mkdocs --help
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\mkdocs.exe\__main__.py", line 4, in <module>
  File "d:\anaconda3\lib\site-packages\mkdocs\__main__.py", line 45, in <module>
    theme_choices = utils.get_theme_names()
  File "d:\anaconda3\lib\site-packages\mkdocs\utils\__init__.py", line 327, in get_theme_names
    return get_themes().keys()
  File "d:\anaconda3\lib\site-packages\mkdocs\utils\__init__.py", line 311, in get_themes
    "with the same name".format(theme.name, theme.dist.key))
mkdocs.exceptions.ConfigurationError: The theme mkdocs is a builtin theme but -kdocs provides a theme with the same name
```

**Comment by epogrebnyak** [comment]
`mkdocs` works fine in isolated environment, so where is a point for intersection with other themes?

**Comment by epogrebnyak** [comment]
Here is what I have in my global environment:

```python
for theme in pkg_resources.iter_entry_points(group='mkdocs.themes'): 
   print(theme.dist.key, theme)
-kdocs mkdocs = mkdocs.themes.mkdocs
-kdocs readthedocs = mkdocs.themes.readthedocs
mkdocs mkdocs = mkdocs.themes.mkdocs
mkdocs readthedocs = mkdocs.themes.readthedocs
mkdocs-material material = material
```

How do I get rid of `-kdocs` on my computer?

**Comment by epogrebnyak** [comment]
Looks like I needed to delete `~kdocs` from `d:\anaconda3\lib\site-packages`
