### ISSUE TITLE
mkdocs serve Exception

### ISSUE THREAD

**Issue by ldelaprade** [mkdocs/mkdocs#2122]
attached a short index.md which cause mkdocs serve crash.
[index.md.txt](https://github.com/mkdocs/mkdocs/files/4750711/index.md.txt)

You can still mkdocs build, then cd to site, then python -m http.server.
But when using mkdocs serve, you get
```
λ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - index.md
INFO    -  Documentation built in 0.41 seconds
[I 200609 09:53:56 server:296] Serving on http://127.0.0.1:3000
INFO    -  Serving on http://127.0.0.1:3000
[I 200609 09:53:56 handlers:62] Start watching changes
INFO    -  Start watching changes
[I 200609 09:53:56 handlers:64] Start detecting changes
INFO    -  Start detecting changes
[E 200609 09:54:00 web:1788] Uncaught exception GET / (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "g:\applis\python383\lib\site-packages\tornado\web.py", line 1703, in _execute
        result = await result
      File "g:\applis\python383\lib\site-packages\tornado\web.py", line 2653, in get
        await self.flush()
      File "g:\applis\python383\lib\site-packages\tornado\web.py", line 1093, in flush
        return self.request.connection.write_headers(
      File "g:\applis\python383\lib\site-packages\tornado\http1connection.py", line 462, in write_headers
        data += self._format_chunk(chunk)
      File "g:\applis\python383\lib\site-packages\tornado\http1connection.py", line 473, in _format_chunk
        raise httputil.HTTPOutputError(
    tornado.httputil.HTTPOutputError: Tried to write more data than Content-Length
```

**Comment by oprypin** [comment]
Implementation of `serve` changed since then
