### ISSUE TITLE
mkdocs serve: ValueError: The language 'arabic' is not supported.

### ISSUE THREAD

**Issue by ronnydw** [mkdocs/mkdocs#2149]
$ mkdocs serve
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/Users/ronny/anaconda/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/__main__.py", line 136, in serve_command
    **kwargs
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 129, in builder
    **kwargs
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/config/config_options.py", line 131, in validate
    return self.run_validation(value)
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/config/config_options.py", line 609, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/config/config_options.py", line 617, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2341, in load
    return self.resolve()
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2347, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/contrib/search/__init__.py", line 6, in <module>
    from mkdocs.contrib.search.search_index import SearchIndex
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/mkdocs/contrib/search/search_index.py", line 7, in <module>
    from lunr import lunr
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/lunr/__init__.py", line 5, in <module>
    from lunr.__main__ import lunr
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/lunr/__main__.py", line 6, in <module>
    from lunr import languages as lang
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/lunr/languages/__init__.py", line 104, in <module>
    register_languages()
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/lunr/languages/__init__.py", line 95, in register_languages
    language_stemmer = partial(nltk_stemmer, get_language_stemmer(language))
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/lunr/languages/stemmer.py", line 10, in get_language_stemmer
    return SnowballStemmer(SUPPORTED_LANGUAGES[language])
  File "/Users/ronny/anaconda/lib/python3.6/site-packages/nltk/stem/snowball.py", line 90, in __init__
    raise ValueError("The language '{0}' is not supported.".format(language))
ValueError: The language 'arabic' is not supported.

**Comment by facelessuser** [comment]
This looks to be a problem with lunr (upstream) not MkDocs.

**Comment by ronnydw** [comment]
I created an issue for lunr as well https://github.com/olivernn/lunr.js/issues/473
