### ISSUE TITLE
nltk dependency is missing when installing mkdocs with Poetry

### ISSUE THREAD

**Issue by roipoussiere** [mkdocs/mkdocs#2150]
I use [Poetry](https://python-poetry.org/) in my project.

After installed mkdocs with `poetry add --dev mkdocs` (same as pip install mkdocs), I tried to build my doc with `poetry run mkdocs build` (run mkdocs in the virtualenv), but I got this error:

```
Traceback (most recent call last):
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 131, in validate
    return self.run_validation(value)
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 609, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 617, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/nath/.cache/pypoetry/virtualenvs/amethyst-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'nltk>=3.2.5; python_version > "2.7" and extra == "languages"' distribution was not found and is required by lunr
```

The error disappeared after adding the `nltk` module with `poetry add --dev nltk`

**Comment by waylan** [comment]
I have no idea what poetry is. As the commands are all calling poetry I can only assume this is an issue for poetry.
