### ISSUE TITLE
Serve or Build commands getting hung up on no file_match?

### ISSUE THREAD

**Issue by stmcallister** [mkdocs/mkdocs#2187]
I'm getting a `StopIteration` error when running `mkdocs serve` or `build`. This is on a fresh MkDocs project. I've installed MkDocs, ran `mkdocs new my-project` and then `mkdocs serve`. 

It appears the `file_match` variable is empty on line 345 of `config_options.py` but I can't figure out what populates `file_match`. Is there an additional step between installing MkDocs and then using it that I'm missing? 

Thanks for any help. My full stack trace is below.  

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 345, in walk_docs_dir
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 110, in serve_command
    serve.serve(
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 78, in serve
    config = builder()
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 67, in builder
    config = load_config(
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 151, in load_config
    errors, warnings = cfg.validate()
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 84, in validate
    self._post_validate()
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 73, in _post_validate
    config_option.post_validation(self, key_name=key)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 370, in post_validation
    for filename in self.walk_docs_dir(config['docs_dir']):
RuntimeError: generator raised StopIteration
```

**Comment by waylan** [comment]
The last line of the traceback clearly indicates that the error occurs when trying to walk the files in the `docs_dir` config setting. Have you provided a custom value for that setting or are you relying on the default value (`docs`)? Does the setting point to a directory that exists (relative to the config file) and does that directory have any files in it?

**Comment by oprypin** [comment]
This commit removes the mentioned piece of code entirely.
https://github.com/mkdocs/mkdocs/commit/d0c67b849cd6f03cda87624eab93096e9bc41c9c#diff-685a203254588194fa9c3c97a67d1b8b5609f807541cea23b9f8cd25baa67cec
So this is almost surely not reproducible now
