### ISSUE TITLE
mkdocs does not support trio library

### ISSUE THREAD

**Issue by lewoudar** [mkdocs/mkdocs#2208]
Hi,
I'm working on a library using [trio](https://trio.readthedocs.io/en/stable/) and when I want to build the documentation, I have the bad surprise that the backend is not supported.
My environment:
Ubuntu 18.04 LTS
Python 3.6
Mkdocs 1.1.2

My traceback

```python
mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/kevin/PycharmProjects/open_source/scalpel/site 
ERROR   -  Error reading page 'api.md': unsupported platform 
Traceback (most recent call last):
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/mkdocs/commands/build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/mkdocs/commands/build.py", line 171, in _populate_page
    page.render(config, files)
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/markdown/core.py", line 263, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/mkautodoc/extension.py", line 153, in run
    item = import_from_string(import_string)
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/mkautodoc/extension.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/kevin/.pyenv/versions/3.6.10/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kevin/PycharmProjects/open_source/scalpel/scalpel/trionic/__init__.py", line 1, in <module>
    from .files import read_mp, write_mp
  File "/home/kevin/PycharmProjects/open_source/scalpel/scalpel/trionic/files.py", line 6, in <module>
    import trio
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/trio/__init__.py", line 18, in <module>
    from ._core import (
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/trio/_core/__init__.py", line 27, in <module>
    from ._run import (
  File "/home/kevin/.cache/pypoetry/virtualenvs/scalpel-WzXLQS4X-py3.6/lib/python3.6/site-packages/trio/_core/_run.py", line 2325, in <module>
    raise NotImplementedError("unsupported platform")
NotImplementedError: unsupported platform
```

Tell me if you want more information.

Best regards

**Comment by waylan** [comment]
I'm note sure what relationship you think MkDocs should have with trio (which I never heard of until now). MkDocs simply builds a static site. There is no need to async functionality.

**Comment by lewoudar** [comment]
Hi @waylan thinking about it, it's not so much mkdocs the problem but the _mkautodoc_ plugin, so I think this issue can be closed

**Comment by waylan** [comment]
Ah, that makes more sense. Yes, I would suggest reporting this issue to the plugin directly.
