### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'end'

### ISSUE THREAD

**Issue by TimWolla** [mkdocs/mkdocs#2277]
I am running

```
$ mkdocs --version
mkdocs, version 1.1.2 from /usr/local/lib/python3.9/site-packages/mkdocs (Python 3.9)
```

within a `python:3` Docker container. I installed it using `pip3 install -qq mkdocs`.

My mkdocs.yml is as follows:

```yml
site_name: Something
```

I have a single `.md` file as follows:

```markdown
# Something

## <span>xxx</span> `xxx`

xxx xxx.

something `]]]]><![CDATA[>`.

## <span>yyy</span> `yyy`
```

When I attempt to `mkdocs build` I am receiving an `AttributeError`:

```
command >>>mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /pwd/site 
ERROR   -  Error reading page 'crasher.md': 'NoneType' object has no attribute 'end' 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 171, in _populate_page
    page.render(config, files)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 261, in convert
    self.lines = prep.run(self.lines)
  File "/usr/local/lib/python3.9/site-packages/markdown/preprocessors.py", line 81, in run
    parser.close()
  File "/usr/local/lib/python3.9/site-packages/markdown/htmlparser.py", line 78, in close
    super().close()
  File "/usr/local/lib/python3.9/html/parser.py", line 114, in close
    self.goahead(1)
  File "/usr/local/lib/python3.9/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
  File "/usr/local/lib/python3.9/html/parser.py", line 420, in parse_endtag
    self.handle_endtag(elem)
  File "/usr/local/lib/python3.9/site-packages/markdown/htmlparser.py", line 148, in handle_endtag
    text = self.get_endtag_text(tag)
  File "/usr/local/lib/python3.9/site-packages/markdown/htmlparser.py", line 118, in get_endtag_text
    start = self.line_offset + self.offset
  File "/usr/local/lib/python3.9/site-packages/markdown/htmlparser.py", line 95, in line_offset
    return re.match(r'([^\n]*\n){{{}}}'.format(self.lineno-1), self.rawdata).end()
AttributeError: 'NoneType' object has no attribute 'end'
```

My full session transcript is as follows:

<details><summary>Click to uncollapse</summary>

```
command >>>apt-get update -qqqqq && apt-get install -yy -qqqqqqqq tree > /dev/null 2>&1
command >>>pip3 install -qq mkdocs
command >>>mkdocs --version
mkdocs, version 1.1.2 from /usr/local/lib/python3.9/site-packages/mkdocs (Python 3.9)
command >>>echo; tree; echo

.
├── docs
│   └── crasher.md
└── mkdocs.yml

1 directory, 2 files

command >>>echo; cat mkdocs.yml; echo

site_name: Something

command >>>echo; cat docs/crasher.md; echo

# Something

## <span>xxx</span> `xxx`

xxx xxx.

something `]]]]><![CDATA[>`.

## <span>yyy</span> `yyy`


command >>>mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /pwd/site 
ERROR   -  Error reading page 'crasher.md': 'NoneType' object has no attribute 'end' 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 171, in _populate_page
    page.render(config, files)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 261, in convert
    self.lines = prep.run(self.lines)
  File "/usr/local/lib/python3.9/site-packages/markdown/preprocessors.py", line 81, in run
    parser.close()
  File "/usr/local/lib/python3.9/site-packages/markdown/htmlparser.py", line 78, in close
    super().close()
  File "/usr/local/lib/python3.9/html/parser.py", line 114, in close
    self.goahead(1)
  File "/usr/local/lib/python3.9/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
  File "/usr/local/lib/python3.9/html/parser.py", line 420, in parse_endtag
    self.handle_endtag(elem)
  File "/usr/local/lib/python3.9/site-packages/markdown/htmlparser.py", line 148, in handle_endtag
    text = self.get_endtag_text(tag)
  File "/usr/local/lib/python3.9/site-packages/markdown/htmlparser.py", line 118, in get_endtag_text
    start = self.line_offset + self.offset
  File "/usr/local/lib/python3.9/site-packages/markdown/htmlparser.py", line 95, in line_offset
    return re.match(r'([^\n]*\n){{{}}}'.format(self.lineno-1), self.rawdata).end()
AttributeError: 'NoneType' object has no attribute 'end'
```
</details>

I'm aware that the issue does not appear to be in mkdocs itself and instead in the markdown library you use, but since I am not a Python expert I am reporting it here, because mkdocs is **what I can reproduce** this issue with. Please kindly forward the issue upstream with an updated reproducer if you are unable to handle this on your end.

The markdown file is my minimal reproducer. The issue appears to be related to the `<span>` in the headlines (in my real world example they have some `class`es to format them as badges) and the escaped `CDATA` example between them. Apparently that somehow messed up the parser.

I'm happy to answer any further questions in case anything about this is unclear. I'm also happy to hear some workaround if you have a good idea :smiley:

**Comment by TimWolla** [comment]
This might or might not be a duplicate of this fixed upstream issue: https://github.com/Python-Markdown/markdown/issues/1066

**Comment by waylan** [comment]
> This might or might not be a duplicate of this fixed upstream issue: Python-Markdown/markdown#1066

It most certainly is.
