### ISSUE TITLE
mkdocs serve Error. Exception raised.

### ISSUE THREAD

**Issue by HUGHNew** [mkdocs/mkdocs#2307]
config  
- wsl2(Ubuntu 18.04) 
- mkdocs(ver: 0.16.3)

I follow the steps and encounter the unexpected problem

`$ mkdocs serve`
```
INFO    -  Building documentation...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mkdocs/config/config_options.py", line 366, in walk_docs_dir
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 11, in <module>
    load_entry_point('mkdocs==0.16.3', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/usr/lib/python3/dist-packages/mkdocs/commands/serve.py", line 110, in serve
    config = builder()
  File "/usr/lib/python3/dist-packages/mkdocs/commands/serve.py", line 101, in builder
    theme_dir=theme_dir
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 181, in load_config
    errors, warnings = cfg.validate()
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 105, in validate
    post_failed, post_warnings = self._post_validate()
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 85, in _post_validate
    config_option.post_validation(self, key_name=key)
  File "/usr/lib/python3/dist-packages/mkdocs/config/config_options.py", line 391, in post_validation
    for filename in self.walk_docs_dir(config['docs_dir']):
RuntimeError: generator raised StopIteration
```

**Comment by waylan** [comment]
> mkdocs(ver: 0.16.3)

The current version of MkDocs is 1.1.2. I suggest upgrading.

My guess is that you are running an older version of MkDocs on a newer version of Python. Starting with Python 3.7, [PEP 479][1] is enabled by default, which would explain the error. MkDocs 0.16.3 was not tested against any Python version higher than 3.5.

As this involves an unsupported version, I am closing this.

[1]: https://www.python.org/dev/peps/pep-0479/
