### ISSUE TITLE
livereload tests, symlinks and Windows

### ISSUE THREAD

**Issue by waylan** [mkdocs/mkdocs#2445]
Apparently, I hadn't run the test locally until today after merging the new server. On my local Windows machine I'm getting the following failures:

```
$ tox -e py38-unittests
GLOB sdist-make: C:\code\mkdocs\setup.py
py38-unittests inst-nodeps: C:\code\mkdocs\.tox\.tmp\package\1\mkdocs-1.2.zip
py38-unittests installed: Babel==2.9.1,click==8.0.1,colorama==0.4.4,coverage==5.5,flake8==3.9.2,ghp-import==2.0.1,importlib-metadata==4.5.0,Jinja2==3.0.1,Markdown==3.3.4,MarkupSafe==2.0.1,mccabe==0.6.1,mdx-gh-links==0.2,mergedeep==1.3.4,mkdocs @ file:///C:/code/mkdocs/.tox/.tmp/package/1/mkdocs-1.2.zip,mkdocs-redirects==1.0.3,packaging==20.9,pycodestyle==2.7.0,pyflakes==2.3.1,pyparsing==2.4.7,python-dateutil==2.8.1,pytz==2021.1,PyYAML==5.4.1,pyyaml-env-tag==0.1,six==1.16.0,watchdog==2.1.2,zipp==3.4.1
py38-unittests run-test-pre: PYTHONHASHSEED='895'
py38-unittests run-test: commands[0] | 'C:\code\mkdocs\.tox\py38-unittests\Scripts\python' --version
Python 3.8.1
py38-unittests run-test: commands[1] | 'C:\code\mkdocs\.tox\py38-unittests\Scripts/coverage' run --source=mkdocs --omit 'mkdocs/tests/*' -m unittest discover -p '*tests.py' mkdocs
..................................................................................................................................................s........................................................................................................................EEEE.....................................................s.................................................................................................................................................................................
======================================================================
ERROR: test_watch_with_broken_symlinks (tests.livereload_tests.BuildTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\code\mkdocs\mkdocs\tests\base.py", line 82, in wrapper
    return fn(self, td, *args)
  File "C:\code\mkdocs\mkdocs\tests\livereload_tests.py", line 530, in test_watch_with_broken_symlinks
    Path(docs_dir, "broken_1").symlink_to(Path(docs_dir, "oh no"))
  File "C:\Users\wlimberg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1376, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\wlimberg\\AppData\\Local\\Temp\\mkdocs_test-p__7vszc\\oh no' -> 'C:\\Users\\wlimberg\\AppData\\Local\\Temp\\mkdocs_test-p__7vszc\\broken_1'

======================================================================
ERROR: test_watches_direct_symlinks (tests.livereload_tests.BuildTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\code\mkdocs\mkdocs\tests\base.py", line 82, in wrapper
    return fn(self, td, *args)
  File "C:\code\mkdocs\mkdocs\tests\base.py", line 82, in wrapper
    return fn(self, td, *args)
  File "C:\code\mkdocs\mkdocs\tests\base.py", line 82, in wrapper
    return fn(self, td, *args)
  File "C:\code\mkdocs\mkdocs\tests\livereload_tests.py", line 432, in test_watches_direct_symlinks
    Path(origin_dir, "docs").symlink_to(dest_docs_dir, target_is_directory=True)
  File "C:\Users\wlimberg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1376, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\wlimberg\\AppData\\Local\\Temp\\mkdocs_test-dest_docs_dirpig62xf9' -> 'C:\\Users\\wlimberg\\AppData\\Local\\Temp\\mkdocs_test-origin_dircnu2iexj\\docs'

======================================================================
ERROR: test_watches_through_relative_symlinks (tests.livereload_tests.BuildTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\code\mkdocs\mkdocs\tests\base.py", line 82, in wrapper
    return fn(self, td, *args)
  File "C:\code\mkdocs\mkdocs\tests\base.py", line 82, in wrapper
    return fn(self, td, *args)
  File "C:\code\mkdocs\mkdocs\tests\livereload_tests.py", line 507, in test_watches_through_relative_symlinks
    Path(docs_dir, "README.md").symlink_to(Path("..", "README.md"))
  File "C:\Users\wlimberg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1376, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: '..\\README.md' -> 'C:\\Users\\wlimberg\\AppData\\Local\\Temp\\mkdocs_test-origin_dir3vgeql_g\\docs\\README.md'

======================================================================
ERROR: test_watches_through_symlinks (tests.livereload_tests.BuildTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\code\mkdocs\mkdocs\tests\base.py", line 82, in wrapper
    return fn(self, td, *args)
  File "C:\code\mkdocs\mkdocs\tests\base.py", line 82, in wrapper
    return fn(self, td, *args)
  File "C:\code\mkdocs\mkdocs\tests\base.py", line 82, in wrapper
    return fn(self, td, *args)
  File "C:\code\mkdocs\mkdocs\tests\livereload_tests.py", line 465, in test_watches_through_symlinks
    Path(docs_dir, "link1.md").symlink_to(Path(tmp_dir, "file_dest_1.md"))
  File "C:\Users\wlimberg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1376, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\wlimberg\\AppData\\Local\\Temp\\mkdocs_test-tmp_dir2clm6pp6\\file_dest_1.md' -> 'C:\\Users\\wlimberg\\AppData\\Local\\Temp\\mkdocs_test-czhuhfqe\\link1.md'

----------------------------------------------------------------------
Ran 502 tests in 14.540s

FAILED (errors=4, skipped=2)
ERROR: InvocationError for command 'C:\code\mkdocs\.tox\py38-unittests\Scripts/coverage' run --source=mkdocs --omit 'mkdocs/tests/*' -m unittest discover -p '*tests.py' mkdocs (exited with code 1)
______________________________________ summary _______________________________________ 
ERROR:   py38-unittests: commands failed
```

**Comment by oprypin** [comment]
Yes, people who want to run the tests on Windows should enable symlink support in Windows.
It would also be possible to bail out on inability to create a symlink, but that opens up a path for the test to silently stop checking anything.

**Comment by waylan** [comment]
> should enable symlink support in Windows

Ah, I guess I hadn't realized this was an option that needed to be enabled. As this is not enabled by default, I would expect these tests to get skipped if the option is not enabled. Is there an easy way to detect that?

**Comment by pawamoy** [comment]
We expect developers to setup a proper development environment for working on MkDocs, so we'll close this as not planned. Feel free to comment further!
