### ISSUE TITLE
New version causes livereload failures

### ISSUE THREAD

**Issue by yi2020** [mkdocs/mkdocs#2448]
`mkdocs build` was working fine in our CI (GitHub Actions), until the recent release:

```
Successfully installed Jinja2-3.0.1 Markdown-3.3.4 MarkupSafe-2.0.1 Pygments-2.9.0 click-8.0.1 ghp-import-2.0.1 importlib-metadata-4.5.0 mergedeep-1.3.4 mkdocs-1.2 mkdocs-autorefs-0.2.1 mkdocs-material-7.1.7 mkdocs-material-extensions-1.0.1 mkdocstrings-0.15.1 packaging-20.9 pymdown-extensions-8.2 pytkdocs-0.11.1 pyyaml-env-tag-0.1 watchdog-2.1.2 zipp-3.4.1
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.5/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/mkdocs/__main__.py", line 183, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/mkdocs/config/base.py", line 214, in load_config
    errors, warnings = cfg.validate()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/mkdocs/config/base.py", line 108, in validate
    run_failed, run_warnings = self._validate()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/mkdocs/config/base.py", line 63, in _validate
    self[key] = config_option.validate(value)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 130, in validate
    return self.run_validation(value)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 655, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 668, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/mkdocstrings/plugin.py", line 18, in <module>
    from livereload import Server
ModuleNotFoundError: No module named 'livereload'
```

**Comment by yi2020** [comment]
It seems that the removal of the dependency of `livereload` from mkdocs flushed out an issue in `mkdocstrings` where it doesn't have the dependency spelled out correctly? See: https://github.com/mkdocstrings/mkdocstrings/issues/295

**Comment by oprypin** [comment]
Yes, this is purely https://github.com/mkdocstrings/mkdocstrings/issues/295 and the fix for it is already pending review.

I think *this* issue can be closed.

**Comment by jaceklaskowski** [comment]
I had to pin `mkdocs==1.1.2` in [mkdocs-material/requirements.txt](https://github.com/squidfunk/mkdocs-material/blob/master/requirements.txt#L22) and build the theme locally to work it around. Just FYI.

**Comment by squidfunk** [comment]
@jaceklaskowski You could just add `mkdocs<1.2` to your project's `requirements.txt` when installing via `pip`, which is compatible with Material for MkDocs' `mkdocs>=1.1`, so you don't need to patch the `requirements.txt` of Material itself.

`requirements.txt`:

```
mkdocs-material
mkdocs<1.2
```

**Comment by waylan** [comment]
I'm closing this as an upstream issue.
