### ISSUE TITLE
Travis authentication error even with GITHUB_TOKEN configured as the environment variable

### ISSUE THREAD

**Issue by jeffchi** [mkdocs/mkdocs#2462]
I'm testing the Travis CI with mkdocs in this repo https://github.com/jeffchi/mkdocs-test, and ran into this weird error constantly.   Any suggestion?

My `.travis.yml` file is like this:
```
language: Python
python: 3.7
sudo: false
branches: master
script: true
install:
    - pip install mkdocs mkdocs-material pymdown-extensions pygments
before_deploy:
  - mkdocs build
deploy:
  skip_cleanup: true
  provider: script
  target_branch: gh-pages
  script: mkdocs gh-deploy --force
  on:
    branch: master
```

And the environment variables are configured as the following:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/5237126/122079249-ce9b4880-ce2f-11eb-92cd-3644457bdc83.png">

The Travis CI can be kicked off successfully, however,  the log reports:
```
....
Deploying application
WARNING  -  Config value: 'site_url'. Warning: This option is now required. Set to a valid URL or an empty string to avoid an error in a future release.
WARNING  -  Config value: 'site_url'. Warning: The 'use_directory_urls' option has been disabled because 'site_url' contains an empty value. Either define a valid URL for 'site_url' or set 'use_directory_urls' to False.
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/travis/build/[secure]/mkdocs-test/site
INFO     -  Documentation built in 0.07 seconds
WARNING  -  Version check skipped: No version specified in previous deployment.
INFO     -  Copying '/home/travis/build/[secure]/mkdocs-test/site' to 'gh-pages' branch and pushing to GitHub.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/[secure]/mkdocs-test.git/'
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/mkdocs/__main__.py", line 205, in gh_deploy_command
    gh_deploy.gh_deploy(cfg, message=message, force=force, ignore_version=ignore_version, shell=shell)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/mkdocs/commands/gh_deploy.py", line 116, in gh_deploy
    nojekyll=True
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/ghp_import.py", line 261, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'], '--force')
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/ghp_import.py", line 121, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/opt/python/3.7.1/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages', '--force']' returned non-zero exit status 128.
Script failed with status 1
failed to deploy
```

**Comment by pawamoy** [comment]
"GITHUB_TOKEM"?

**Comment by jeffchi** [comment]
> "GITHUB_TOKEM"?

Fixed just now.  `GITHUB_TOKEN' doesn't work either.

**Comment by oprypin** [comment]
I don't understand what this issue is about. There is not a single mention of `GITHUB_TOKEN` in the entire MkDocs repository. So first, could you please show why you think this variable should mean anything to MkDocs?
