### ISSUE TITLE
Cannot install mkdocs in vietual env

### ISSUE THREAD

**Issue by bluemiaomiao** [mkdocs/mkdocs#2516]
I'm trying to run the following command in Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64(Python2.7 & Python 3.5 & Python 3.9):

```bash
virtualenv venv
source venv/bin/activate
pip install mkdocs
```

The error details (Python2):

```bash
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting mkdocs
  Using cached mkdocs-1.0.4-py2.py3-none-any.whl (1.2 MB)
Processing /root/.cache/pip/wheels/f2/a1/fa/00775311351a48f78b4a0e40588eefdd6f2731cc8115d6957d/livereload-2.6.3-py2.py3-none-any.whl
Collecting Markdown>=2.3.1
  Using cached Markdown-3.1.1-py2.py3-none-any.whl (87 kB)
Collecting Jinja2>=2.7.1
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting click>=3.3
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Processing /root/.cache/pip/wheels/6d/e1/ce/f4ee2fa420cc6b940123c64992b81047816d0a9fad6b879325/tornado-5.1.1-cp27-cp27mu-linux_x86_64.whl
Collecting PyYAML>=3.10
  Using cached PyYAML-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl (574 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: setuptools>=36 in ./venv/lib/python2.7/site-packages (from Markdown>=2.3.1->mkdocs) (45.0.0)
ERROR: Package 'setuptools' requires a different Python: 2.7.13 not in '>=3.5'
(venv) ➜  root newbie 
```

Then:

```bash
virtualenv --python=/usr/bin/python3.5 venv
➜  root ~ source venv/bin/activate
(venv) ➜  root ~ pip install mkdocs
Traceback (most recent call last):
  File "/root/venv/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/root/venv/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 58
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
(venv) ➜  root ~ pip3 install mkdocs
Traceback (most recent call last):
  File "/root/venv/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/root/venv/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 58
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

Help me~

**Comment by oprypin** [comment]
Neither Python 2.7 nor Python 3.5 are supported by MkDocs. They are also generally end-of-life Python releases. Please upgrade your Python.
