### ISSUE TITLE
using DTL in overriding templates causes error

### ISSUE THREAD

**Issue by mehrnazd** [mkdocs/mkdocs#2579]
I integrated Django 3 with mkdocs. means instead of Mkdocs serve, I'm using Django to run `mkdocs serve`, in order to use Django authentication. Everything is fine so far. my main problem is the documentation building part. I'm overriding the `mian.html` using [customized blocks](https://www.mkdocs.org/user-guide/customizing-your-theme/#overriding-template-blocks). I want to hide one of the tabs if the user is not a superuser. 
```
#main.html

    {% if user.is_superuser %}
      <li class="md-tabs__item">
        <a href="admin/state/" class="md-tabs__link">
          Admin
        </a>
      </li>
    {% endif %}
```

but I'm getting this error:

```
mkdocs_1      | INFO     -  Cleaning site directory
mkdocs_1      | INFO     -  Building documentation to directory: /docs/docs/static/mkdocs_build
mkdocs_1      | WARNING  -  Documentation file 'first-page.md' contains a link to 'img/my-pic.png' which is not found in the documentation files.
mkdocs_1      | Traceback (most recent call last):
mkdocs_1      |   File "/usr/local/bin/mkdocs", line 8, in <module>
mkdocs_1      |     sys.exit(cli())
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
mkdocs_1      |     return self.main(*args, **kwargs)
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
mkdocs_1      |     rv = self.invoke(ctx)
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
mkdocs_1      |     return _process_result(sub_ctx.command.invoke(sub_ctx))
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
mkdocs_1      |     return ctx.invoke(self.callback, **ctx.params)
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
mkdocs_1      |     return __callback(*args, **kwargs)
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 183, in build_command
mkdocs_1      |     build.build(config.load_config(**kwargs), dirty=not clean)
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 298, in build
mkdocs_1      |     _build_theme_template(template, env, files, config, nav)
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 111, in _build_theme_template
mkdocs_1      |     output = _build_template(template_name, template, files, config, nav)
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 90, in _build_template
mkdocs_1      |     output = template.render(context)
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
mkdocs_1      |     self.environment.handle_exception()
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
mkdocs_1      |     raise rewrite_traceback_stack(source=source)
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/material/404.html", line 4, in top-level template code
mkdocs_1      |     {% extends "main.html" %}
mkdocs_1      |   File "/docs/overrides/main.html", line 1, in top-level template code
mkdocs_1      |     {% extends "base.html" %}
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/material/base.html", line 121, in top-level template code
mkdocs_1      |     {% block tabs %}
mkdocs_1      |   File "/docs/overrides/main.html", line 145, in block 'tabs'
mkdocs_1      |     {% if user.is_superuser %}
mkdocs_1      |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
mkdocs_1      |     return getattr(obj, attribute)
mkdocs_1      | jinja2.exceptions.UndefinedError: 'user' is undefined
```
is there a way to fix this error?

**Comment by oprypin** [comment]
Umm then seems you haven't actually fully integrated Django, because it's not touched at all when rendering the template. It's Jinja2 instead, which only looks somewhat similar. But indeed the Jinja2 template engine has no awareness of any "user". You'd have to pass such objects to the template. Which you would just need to modify the code for.
https://github.com/mkdocs/mkdocs/blob/fd0e9dedd27e4cb628ab98ff2723165110b38ed2/mkdocs/commands/build.py#L90
Or maybe would be enough to add a MkDocs plugin with `on_template_context` which would somehow pull those objects from Django?

Anyway... seems that if you're taking up such an advanced project, you basically should know better than anyone who could try to help you here. It's also not really in scope and not really an issue, so I'm inclined to close it. Well, I'll move it to a discussion.
