### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by projettajr** [mkdocs/mkdocs#2648]
any tips on how to solve? I've searched a lot but I have no idea where to find the solution

```
Run mkdocs gh-deploy --force
INFO     -  Cleaning site directory
PDF export is disabled (set environment variable CI to 1 to enable)
INFO     -  Building documentation to directory: /home/runner/work/projetos/projetos/site
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - manuais/plotagem-e-extracao-de-memoriais-qibuilder.md
  - manuais/plotagem-em-revit.md
  - manuais/requisitos-qualidade-arquitetonico.md
WARNING:root:
                [git-revision-date-localized-plugin] Running on GitHub Actions might lead to wrong
                Git revision dates due to a shallow git fetch depth.

                Try setting fetch-depth to 0 in your GitHub Action
                (see https://github.com/actions/checkout).
                
WARNING:root:
                [git-revision-date-localized-plugin] Running on bitbucket pipelines might lead to wrong
                Git revision dates due to a shallow git fetch depth.

                Try setting "clone: depth" to "full" in your pipeline
                (see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
                and search 'depth').
                
WARNING:root:
                [git-revision-date-localized-plugin] Running on GitHub Actions might lead to wrong
                Git revision dates due to a shallow git fetch depth.

                Try setting fetch-depth to 0 in your GitHub Action
                (see https://github.com/actions/checkout).
                
WARNING:root:
                [git-revision-date-localized-plugin] Running on bitbucket pipelines might lead to wrong
                Git revision dates due to a shallow git fetch depth.

                Try setting "clone: depth" to "full" in your pipeline
                (see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
                and search 'depth').
                
WARNING:root:
                [git-revision-date-localized-plugin] Running on GitHub Actions might lead to wrong
                Git revision dates due to a shallow git fetch depth.

                Try setting fetch-depth to 0 in your GitHub Action
                (see https://github.com/actions/checkout).
                
WARNING:root:
                [git-revision-date-localized-plugin] Running on bitbucket pipelines might lead to wrong
                Git revision dates due to a shallow git fetch depth.

                Try setting "clone: depth" to "full" in your pipeline
                (see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
                and search 'depth').
                
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.0/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 208, in gh_deploy_command
    build.build(cfg, dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 306, in build
    _build_theme_template(template, env, files, config, nav)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 111, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 90, in _build_template
    output = template.render(context)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/material/404.html", line 4, in <module>
    {% extends "main.html" %}
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/material/main.html", line 4, in <module>
    {% extends "base.html" %}
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/material/base.html", line 116, in <module>
    {% block header %}
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/material/base.html", line 117, in <module>
    {% include "partials/header.html" %}
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/material/partials/header.html", line 36, in <module>
    {% for option in config.theme.palette %}
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/jinja2/runtime.py", line 468, in __init__
    self._iterator = self._to_iterator(iterable)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/jinja2/runtime.py", line 476, in _to_iterator
    return iter(iterable)
TypeError: 'NoneType' object is not iterable
Error: Process completed with exit code 1.
```

**Comment by oprypin** [comment]
You must specify more details.
The bug is due to your config.
Please at the very least show your `mkdocs.yml`.

I can only guess here that the problem is in the config
```yaml
theme: 
  palette: null
```
something like that

**Comment by oprypin** [comment]
> ```yaml
> theme:
> 
>   palette:
>     # scheme: preference
> ```

is indeed the same as

> ```yaml
> theme: 
>   palette: null
> ```

Don't specify it as null, and also you can report to mkdocs-material theme that it should degrade gracefully in case pallette is specified as null.
