### ISSUE TITLE
documentation build fails with TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by zimmy87** [mkdocs/mkdocs#2811]
Hi, the GitHub Pages for our project [here](https://github.com/microsoft/AirSim) is failing to build with the following output:

```
Run ./build_docs.sh
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/runner/work/AirSim/AirSim/build_docs
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.[7](https://github.com/microsoft/AirSim/runs/5774848151?check_suite_focus=true#step:6:7).12/x64/bin/mkdocs", line [8](https://github.com/microsoft/AirSim/runs/5774848151?check_suite_focus=true#step:6:8), in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mkdocs/__main__.py", line 1[9](https://github.com/microsoft/AirSim/runs/5774848151?check_suite_focus=true#step:6:9)2, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mkdocs/commands/build.py", line 306, in build
    _build_theme_template(template, env, files, config, nav)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mkdocs/commands/build.py", line [11](https://github.com/microsoft/AirSim/runs/5774848151?check_suite_focus=true#step:6:11)1, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/opt/hostedtoolcache/Python/3.7.[12](https://github.com/microsoft/AirSim/runs/5774848151?check_suite_focus=true#step:6:12)/x64/lib/python3.7/site-packages/mkdocs/commands/build.py", line 90, in _build_template
    output = template.render(context)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jinja2/environment.py", line 9[25](https://github.com/microsoft/AirSim/runs/5774848151?check_suite_focus=true#step:6:25), in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mkdocs/themes/readthedocs/search.html", line 1, in top-level template code
    {% extends "main.html" %}
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mkdocs/themes/readthedocs/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mkdocs/themes/readthedocs/base.html", line 90, in top-level template code
    {%- block site_name %}
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mkdocs/themes/readthedocs/base.html", line 97, in block 'site_name'
    <img src="{{ config.theme.logo|url }}" class="logo" alt="{% trans %}Logo{% endtrans %}"/>
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mkdocs/utils/filters.py", line 12, in url_filter
    return normalize_url(value, page=context['page'], base=context['base_url'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mkdocs/utils/__init__.py", line [28](https://github.com/microsoft/AirSim/runs/5774848151?check_suite_focus=true#step:6:28)2, in normalize_url
    path, is_abs = _get_norm_url(path)
TypeError: unhashable type: 'dict'
```

Our mkdocs.yml is defined as:

```
site_name: AirSim
site_dir: build_docs
repo_url: https://github.com/microsoft/airsim
site_description: 'Open source simulator based on Unreal Engine for autonomous vehicles from Microsoft AI & Research'

markdown_extensions:
    - toc:
        permalink: "#"
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.extra:
    - admonition

remote_branch: gh-pages

theme:
  name: 'readthedocs'
  logo:
    icon: ' '

extra:
  highlightjs: true
  version: 1.3.1
  feature:
      tabs: true
  palette:
  social:
      - type: facebook
        link: https://www.facebook.com/groups/1225832467530667/
      - type: github-alt
        link: https://github.com/Microsoft/AirSim

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2021 Microsoft Research

nav:
  - "Home":
    - "Home": 'README.md'
  - "Changelog": 'CHANGELOG.md'
  - "Building AirSim":
    - "Download Binaries": 'use_precompiled.md'
    - "Build on Windows": 'build_windows.md'
    - "Build on Linux": 'build_linux.md'
    - "Build on macOS": 'build_macos.md'
    - "Docker on Linux": 'docker_ubuntu.md'
    - "AirSim on Azure": 'azure.md'
    - "Custom Unreal Environment": 'unreal_custenv.md'
    - "AirSim with Unity": "Unity.md"
    - "Custom Unity Environment": "custom_unity_environments.md"
    - "Unity APIs": "unity_api_support.md"
    - "FAQ": 'build_faq.md'
  - "Using AirSim":
    - "Core APIs": 'apis.md'
    - "Image APIs": 'image_apis.md'
    - "C++ APIs": 'apis_cpp.md'
    - "API Reference Docs": 'api_docs/html/index.html'
    - "Development Workflow": 'dev_workflow.md'
    - "Settings": 'settings.md'
    - "Camera Views": 'camera_views.md'
    - "Car Mode": 'using_car.md'
    - "Remote Control": 'remote_control.md'
    - "XBox Controller": 'xbox_controller.md'
    - "Steering Wheel": 'steering_wheel_installation.md'
    - "Multiple Vehicles": 'multi_vehicle.md'
    - "Sensors":
      - "Sensors": 'sensors.md'
      - "LIDAR": 'lidar.md'
      - "Distance Sensor": 'distance_sensor.md'
      - "Infrared Camera": "InfraredCamera.md"
    - "ROS: AirSim ROS Wrapper": "airsim_ros_pkgs.md"
    - "ROS: AirSim Tutorial Packages": "airsim_tutorial_pkgs.md"
    - "Import Gazebo models": "gazebo_drone.md"
    - "Domain Randomization": "retexturing.md"
    - "Mesh Vertex Buffers": "meshes.md"
    - "Playing Logs": 'playback.md'
    - "Voxel Grid Generator": "voxel_grid.md"
    - "Event camera" : "event_sim.md"
  - "Design":
    - "Architecture": 'design.md'
    - "Code Structure": 'code_structure.md'
    - "Adding new APIs": 'adding_new_apis.md'
    - "Modifying Recording Data": 'modify_recording_data.md'
    - "Coding Guidelines": 'coding_guidelines.md'
    - "Flight Controller": 'flight_controller.md'
    - "Simple Flight": 'simple_flight.md'
    - "Hello Drone": 'hello_drone.md'
  - "External Flight Controllers":
    - "MavLink and PX4":
      - "PX4 Setup for AirSim": 'px4_setup.md'
      - "PX4 in SITL": 'px4_sitl.md'
      - "PX4 SITL with WSL 2": 'px4_sitl_wsl2.md'
      - "PX4 Lockstep": 'px4_lockstep.md'
      - "PX4 Multi-vehicle in SITL": 'px4_multi_vehicle.md'
      - "AirSim with Pixhawk": 'https://youtu.be/1oY8Qu5maQQ'
      - "PX4 Setup with AirSim": 'https://youtu.be/HNWdYrtw3f0'
      - "Debugging Attitude Estimation": 'https://www.youtube.com/watch?v=d_FyjKDWQfc&feature=youtu.be'
      - "Intercepting MavLink Messages": 'https://github.com/Microsoft/AirSim/wiki/Intercepting-MavLink-messages'
      - "Rapid Descent on PX4 Drones": 'https://github.com/Microsoft/AirSim/wiki/Rapid-Descent-on-PX4-drones'
      - "Building PX4": "px4_build.md"
      - "PX4/MavLink Logging": 'px4_logging.md'
      - "MavLink LogViewer": "log_viewer.md"
      - "MavLinkCom": 'mavlinkcom.md'
      - "MavLink MoCap": 'mavlinkcom_mocap.md'
    - "ArduPilot":
      - "ArduPilot SITL Setup": "https://ardupilot.org/dev/docs/building-the-code.html"
      - "AirSim & ArduPilot": "https://ardupilot.org/dev/docs/sitl-with-airsim.html"
  - "Upgrading":
    - "Upgrading Unreal": 'unreal_upgrade.md'
    - "Upgrading APIs": 'upgrade_apis.md'
    - "Upgrading Settings": 'upgrade_settings.md'
  - "Contributed Tutorials":
    - "Reinforcement Learning": 'reinforcement_learning.md'
    - "Using Environments from Marketplace": 'https://www.youtube.com/watch?v=y09VbdQWvQY'
    - "Simple Collision Avoidance": 'https://github.com/simondlevy/AirSimTensorFlow'
    - "Autonomous Driving on Azure": 'https://aka.ms/AutonomousDrivingCookbook'
    - "Building Hexacopter": 'https://github.com/Microsoft/AirSim/wiki/hexacopter'
    - "Moving on Path Demo": 'https://github.com/Microsoft/AirSim/wiki/moveOnPath-demo'
    - "Building Point Clouds": 'point_clouds.md'
    - "Surveying Using Drone": 'drone_survey.md'
    - "Orbit Trajectory": "orbit.md"
    - "Importing a custom multirotor mesh": 'https://youtu.be/Bp86WiLUC80'
    - "Object Detection": "object_detection.md"
  - "Misc":
    - "AirSim on Real Drones": 'custom_drone.md'
    - "Installing cmake on Linux": 'cmake_linux.md'
    - "Tips for Busy HDD": 'hard_drive.md'
    - "pfm format": 'pfm.md'
    - "Setting up Unreal Environment": 'unreal_proj.md'
    - "Blocks Environment": 'unreal_blocks.md'
    - "Who is Using AirSim": 'who_is_using.md'
    - "Working with UE Plugin Contents": 'working_with_plugin_contents.md'
    - "Formula Student Technion Self-drive": 'https://github.com/Microsoft/AirSim/wiki/technion'
  - "Support":
    - "FAQ": 'faq.md'
    - "Support": 'SUPPORT.md'
    - "Create Issue": 'create_issue.md'
    - "Contribute": 'CONTRIBUTING.md'
```

Does anyone know what would be causing this error? We haven't updated our docs in the past 6 days, and this started happening yesterday, so we think this is due to a change in a dependency.

We also don't see this error when doing a `mkdocs build` or `mkdocs serve` locally, this only happens with our GitHub action.

**Comment by oprypin** [comment]
I confirm that this changed with the release 1.3.0. Will continue looking.

**Comment by oprypin** [comment]
fa52d3ae71251ae1c760cbe9b31caced816573d1 is the first commit with this behavior

This is the minimal reproduction:

```yaml
site_name: foo
theme:
  name: 'readthedocs'
  logo:
    icon: ''
```

However!

Previously the `logo` config was nonexistent for this theme so was ignored. But since release 1.3.0 `logo` is expected to be a string (path), but in your case it's a dict `{icon: ' '}`

https://www.mkdocs.org/user-guide/choosing-your-theme/#readthedocs  -see `logo`

So I think this is expected
