### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'github' is undefined (escape issue)

### ISSUE THREAD

**Issue by Minipada** [mkdocs/mkdocs#2829]
I am having an escape issue trying to enter this block:

\`\`\`bash
CCACHE_DIR: ${{ github.workspace }}/.ccache
\`\`\`

I get:
```
ERROR    -  Error reading page 'ci/introduction.md': 'github' is undefined
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 177, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 54, in serve
    config = builder()
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 49, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 170, in _populate_page
    page.markdown = config['plugins'].run_event(
  File "/usr/local/lib/python3.9/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/markdownextradata/plugin.py", line 98, in on_page_markdown
    return self.apply_template(markdown)
  File "/usr/local/lib/python3.9/site-packages/markdownextradata/plugin.py", line 110, in apply_template
    return md_template.render({**self.mkdocsConfig, **self.mkdocsConfig.get("extra")})
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 73, in top-level template code
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'github' is undefined
```

I tried escaping with backslahes and so, but it then displays it like this
![image](https://user-images.githubusercontent.com/1220912/165587751-d454fe86-0927-4960-9d20-8c5667f1a2a0.png)

What would be the proper way here?

Thanks

**Comment by pawamoy** [comment]
Are you using extensions/plugins that add another layer of Jinja2 rendering? You could try to wrap your problematic code block in `{% raw %}...{% endraw %}` blocks.

**Comment by Minipada** [comment]
Thanks for the prompt answer @pawamoy . It works

{% raw %}
\`\`\`bash
    CCACHE_DIR: ${{ github.workspace }}/.ccache
\`\`\`
{% endraw %}
