### ISSUE TITLE
Error on mkdocs build

### ISSUE THREAD

**Issue by petrocino** [mkdocs/mkdocs#2855]
Any ideas of what can be this kind of problem??

First, what I have installed...

```
root@SERVER [ /root/github_repositories/pcs_power_docs ]: uname -a
Linux SERVER 4.18.0-305.19.1.el8_4.ppc64le #1 SMP Tue Sep 7 06:49:25 EDT 2021 ppc64le ppc64le ppc64le GNU/Linux

root@SERVER [ /root/github_repositories/pcs_power_docs ]: pip3 list | grep mkdoc
mkdocs (1.3.0)
mkdocs-add-number-plugin (1.2.2)
mkdocs-awesome-pages-plugin (2.7.0)
mkdocs-git-authors-plugin (0.6.4)
mkdocs-git-revision-date-localized-plugin (1.0.1)
mkdocs-material (8.2.8)
mkdocs-material-extensions (1.0.3)
mkdocs-table-reader-plugin (1.0.0)

```

AND... THE ERROR

```
root@SERVER [ /root/github_repositories/pcs_power_docs ]: mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /root/github_repositories/pcs_power_docs/site
ERROR    -  Error reading page 'Documentation Guides/markdown_mkdocs_cheatsheet.md': format()
            argument must be a formatter instance, not a class
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/pygments/__init__.py", line 61, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib64/python3.6/site-packages/pygments/formatter.py", line 94, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib64/python3.6/site-packages/pygments/formatters/html.py", line 981, in format_unencoded
    source = self.wrap(source)
TypeError: wrap() missing 1 required positional argument: 'outfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/usr/local/lib/python3.6/site-packages/markdown/core.py", line 268, in convert
    newRoot = treeprocessor.run(root)
  File "/usr/local/lib/python3.6/site-packages/pymdownx/highlight.py", line 483, in run
    code_block_count=self.ext.pygments_code_block
  File "/usr/local/lib/python3.6/site-packages/pymdownx/highlight.py", line 381, in highlight
    code = highlight(src, lexer, formatter)
  File "/usr/local/lib64/python3.6/site-packages/pygments/__init__.py", line 82, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib64/python3.6/site-packages/pygments/__init__.py", line 69, in format
    raise TypeError('format() argument must be a formatter instance, '
TypeError: format() argument must be a formatter instance, not a class
```

**Comment by dantreiman** [comment]
@petrocino I had the same error with `mkdocs-material=8.2.1` and it resolved after updating `mkdocs-material`.  Working for me with `mkdocs=1.3.0  mkdocs-material=8.2.15`

**Comment by petrocino** [comment]
I'll try this approach. Tks a lot!

**Comment by allenyllee** [comment]
I am running under python 3.6.15, below version without issue: 
```
portray==1.7.0 
mkdocs==1.2.4 
mkdocs-material==7.3.0 
pymdown-extensions==7.1 
pygments==2.11.0
```
The error appear when `pygments>=2.12.0`, so I just stick to `2.11.0`
