### ISSUE TITLE
Installation fails on MacOS Yosemite

### ISSUE THREAD

**Issue by smaret** [mkdocs/mkdocs#303]
On MacOS Yosemite (10.10.1), `mkdocs` installation fails with the following message:

```shell
% sudo pip install mkdocs
```
```python
Exception:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/commands/install.py", line 339, in run
    requirement_set.prepare_files(finder)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/req/req_set.py", line 229, in prepare_files
    req_to_install.check_if_exists()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/req/req_install.py", line 928, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 461, in get_distribution
    dist = get_provider(dist)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 341, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 870, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 740, in resolve
    env = Environment(self.entries)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 927, in __init__
    self.scan(search_path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 957, in scan
    self.add(dist)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 977, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
TypeError: unorderable types: str() < NoneType()
```

I use `pip 6.0.2` and `Python 3.4` from [MacPorts](http://macports.org):

```shell
% pip --version
pip 6.0.2 from /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (python 3.4)
```

**Comment by d0ugal** [comment]
I guessed incorrectly, this isn't a general pip version 6 issue. I've been unable to reproduce it, I do see that pip version 6.0.3 has been released, it may be that this would fix it for you.

**Comment by smaret** [comment]
`pip 6.0.3` is not available in MacPorts yet, but I will try as soon as it is available.

**Comment by statmobile** [comment]
I also had this issue with pip 6.0.6 on MacPorts on OS X (10.10.1).  I also went back to pip 1.5.6 and it worked.

**Comment by d0ugal** [comment]
Very odd. I can't figure out how I could possibly reproduce this.

**Comment by d0ugal** [comment]
The only connection I see between you both is MacPorts. I use homebrew on my mac and things work fine on Yosemite. I'd suggest asking upstream with them or trying homebrew, or another Python. If you still have issues then I'm happy to try and help looking at this again.

**Comment by drKnoxy** [comment]
not entirely sure this was it, as i'm hitting this issue with pip 7.0.3

**Comment by waylan** [comment]
I'm confused. Why are people relying on a system level package management system? Pip is a python package. why not install it from PyPI. In fact it can even update itself from PyPI. No need to rely in MacPorts or any other package management system to be updated.

    pip install -U pip
