### ISSUE TITLE
mkdocs serve UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by diana19921105** [mkdocs/mkdocs#3049]
```
	Traceback (most recent call last):
  File "frozen runpy", line 198, in _run_module_as_main
  File "frozen runpy", line 88, in _run_code
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\serve.py", line 86, in serve
    server = LiveReloadServer(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\livereload\__init__.py", line 91, in __init__
    super().__init__((host, port), _Handler, **kwargs)
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 456, in __init__
    self.server_bind()
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\wsgiref\simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\http\server.py", line 137, in server_bind
    self.server_name = socket.getfqdn(host)
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szanto.diana\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 793, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
                                 ^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 0: invalid start byte
```

**Comment by MaximilianKohler** [comment]
#1892 ?

**Comment by tomchristie** [comment]
I don't think the report here meets the standards I'd expect from someone asking for a maintainers time.

(Flip side is we haven't given it any time. Closing as stale either way.)
