### ISSUE TITLE
deploy hangs

### ISSUE THREAD

**Issue by miguelriemoliveira** [mkdocs/mkdocs#3142]
Hi all,

I am doing the 

    mkdocs gh-deploy

I add the login and pass and the code seems to push, but then hangs for a 2 or 3 mins until it aborts with the following error.

```
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/mike/catkin_ws/src/calibration/atom_documentation/site
INFO     -  Documentation built in 0.22 seconds
INFO     -  Copying '/home/mike/catkin_ws/src/calibration/atom_documentation/site' to 'gh-pages' branch and pushing to GitHub.
Username for 'https://github.com': miguelriemoliveira
Password for 'https://miguelriemoliveira@github.com': 
Enumerating objects: 125, done.
Counting objects: 100% (125/125), done.
Delta compression using up to 16 threads
Compressing objects: 100% (96/96), done.
Writing objects: 100% (107/107), 125.62 MiB | 209.85 MiB/s, done.
Total 107 (delta 15), reused 75 (delta 5), pack-reused 0
error: RPC failed; HTTP 408 curl 22 The requested URL returned error: 408
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mkdocs/__main__.py", line 280, in gh_deploy_command
    gh_deploy.gh_deploy(
  File "/usr/local/lib/python3.10/dist-packages/mkdocs/commands/gh_deploy.py", line 127, in gh_deploy
    ghp_import.ghp_import(
  File "/usr/local/lib/python3.10/dist-packages/ghp_import.py", line 283, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'], '--force')
  File "/usr/local/lib/python3.10/dist-packages/ghp_import.py", line 119, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages', '--force']' returned non-zero exit status 1.
```

I have tried the clean and the force options, but nothing worked.
Any ideas? 

Thanks in advance,
Miguel

**Comment by miguelriemoliveira** [comment]
Ooops. Changed wifi network and it works now. 

Sorry about that.
