### ISSUE TITLE
ImportError: cannot import name 'MkDocsConfig' from 'mkdocs.config.defaults

### ISSUE THREAD

**Issue by whinee** [mkdocs/mkdocs#3172]
Running `mkdocs build` spits out the following traceback: 

```text
Traceback (most recent call last):
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/mkdocs/config/base.py", line 224, in load_config
    errors, warnings = cfg.validate()
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/mkdocs/config/base.py", line 108, in validate
    run_failed, run_warnings = self._validate()
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/mkdocs/config/base.py", line 63, in _validate
    self[key] = config_option.validate(value)
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 130, in validate
    return self.run_validation(value)
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 679, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 692, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/mkdocs_minify_plugin/plugin.py", line 12, in <module>
    from mkdocs.config.defaults import MkDocsConfig
ImportError: cannot import name 'MkDocsConfig' from 'mkdocs.config.defaults' (/home/whine/whi_ne/3/projects/personal/tools/md2pdf-rewrite/pyenv/lib/python3.10/site-packages/mkdocs/config/defaults.py)
```

## Info

OS: Arch Linux (6.2.2-arch1-1)
Python: 3.10.9 (Virtual Environment)
Mkdocs: 1.3.0
`mkdocs.yml`:

```yml
# Do Not Modify!
# info start
site_name: md2pdf
site_url: https://m2p.whinyaan.xyz
repo_url: https://github.com/whinee/md2pdf
site_description: None
site_author: whi~nyaan!
copyright: Copyright &copy; 2023 whi~nyaan!

# info end

site_dir: dev/site

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  locale: en
  include_search_page: false
  search_index_only: true
  language: en
  favicon: assets/favicon.png
  logo: assets/images/icons/logo-min.svg

  font:
    text: Roboto
    code: Roboto Mono

  static_templates:
    - 404.html

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

  palette:
    -
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    -
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        -
          name: mermaid
          class: mermaid
  - toc:
      toc_depth : "1-1"

extra:
  social:
    -
      icon: fontawesome/brands/twitter
      link: https://twitter.com/whi_nyaan

plugins:
  - search
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true

nav:
  - Home: /
  - Frequently Asked Questions: /faq
  - License Agreement: /license
  - Changelog: /changelog
  - Latest Bump: /latest-bump
  - Latest Commit: /latest-commit
  - Notes to self: /notes-to-self

  # Do Not Modify!
  - Documentation:
  # nav docs start
    - 0.0 (Current): docs/0/0
  # nav docs end
  ```

**Comment by whinee** [comment]
Having checked the latest commit in this repository, and seeing that it is from 5 months ago, my heart dropped. In any case, removing the following lines from the `mkdocs.yml` fixed it:

```yml
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
```

**Comment by ultrabug** [comment]
Which I guess means that the minify plugin is requiring a newer mkdocs than what you have : 1.3.0

I suggest you also upgrade to that "latest commit" to get an actually newer version of what you're using right now mate.

**Comment by whinee** [comment]
Thank youuu!
