### ISSUE TITLE
Error - '<' not supported between instances of 'TagReference' and 'TagReference'

### ISSUE THREAD

**Issue by nopeitsnothing** [mkdocs/mkdocs#3354]
I have no idea. I'm just gonna throw up my errors and hope someone can weigh in.

Full stack trace:

```sh
$ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
ERROR   -  Error reading page 'index.md': '<' not supported between instances of 'TagReference' and 'TagReference'
Traceback (most recent call last):
  File "/home/user/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 171, in _populate_page
    page.markdown = config.plugins.on_page_markdown(
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/plugins.py", line 575, in on_page_markdown
    return self.run_event('page_markdown', markdown, page=page, config=config, files=files)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs_latest_release_plugin/plugin.py", line 16, in on_page_markdown
    latest_git_tag = self.get_latest_tag(tags)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs_latest_release_plugin/plugin.py", line 48, in get_latest_tag
    return natsorted(matching_tags)[-1]
  File "/home/user/.local/lib/python3.10/site-packages/natsort/natsort.py", line 293, in natsorted
    return sorted(seq, reverse=reverse, key=natsort_keygen(key, alg))
TypeError: '<' not supported between instances of 'TagReference' and 'TagReference'
```

**Comment by pawamoy** [comment]
The error seems to come from the `mkdocs_latest_release_plugin` plugin. You would have better luck opening an issue with this stacktrace on their bugtracker :slightly_smiling_face:

**Comment by nopeitsnothing** [comment]
Thanks for looking into this. My temp solution is to `pip uninstall mkdocs-latest-release-plugin`.
