### ISSUE TITLE
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by msoutopico** [mkdocs/mkdocs#3617]
When deploying to Github pages after updating mkdocs version to 1.5.3 (as well as some extensions' versions too), I get this error: 

```
INFO    -  Documentation built in 3.74 seconds
INFO    -  Copying '/home/souto/Repos/capstanlqc/omegat-guides/site' to 'gh-pages' branch and pushing to GitHub.
Enumerating objects: 932, done.
Counting objects: 100% (932/932), done.
Delta compression using up to 12 threads
Compressing objects: 100% (33/33), done.
Writing objects: 100% (718/718), 964.89 KiB | 192.98 MiB/s, done.
Total 718 (delta 353), reused 714 (delta 350), pack-reused 0 (from 0)
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date
Traceback (most recent call last):
  File "/home/souto/.cache/pypoetry/virtualenvs/omegat-guides-3pPVScJG-py3.11/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/souto/.cache/pypoetry/virtualenvs/omegat-guides-3pPVScJG-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/souto/.cache/pypoetry/virtualenvs/omegat-guides-3pPVScJG-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/souto/.cache/pypoetry/virtualenvs/omegat-guides-3pPVScJG-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/souto/.cache/pypoetry/virtualenvs/omegat-guides-3pPVScJG-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/souto/.cache/pypoetry/virtualenvs/omegat-guides-3pPVScJG-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/souto/.cache/pypoetry/virtualenvs/omegat-guides-3pPVScJG-py3.11/lib/python3.11/site-packages/mkdocs/__main__.py", line 316, in gh_deploy_command
    gh_deploy.gh_deploy(
  File "/home/souto/.cache/pypoetry/virtualenvs/omegat-guides-3pPVScJG-py3.11/lib/python3.11/site-packages/mkdocs/commands/gh_deploy.py", line 129, in gh_deploy
    ghp_import.ghp_import(
  File "/home/souto/.cache/pypoetry/virtualenvs/omegat-guides-3pPVScJG-py3.11/lib/python3.11/site-packages/ghp_import.py", line 285, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'])
  File "/home/souto/.cache/pypoetry/virtualenvs/omegat-guides-3pPVScJG-py3.11/lib/python3.11/site-packages/ghp_import.py", line 119, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 1.
```

In a nutshell, I can't deploy anymore.

Here's my project: https://github.com/capstanlqc/omegat-guides/blob/master/pyproject.toml

What am I doing wrong? 
Thanks.

**Comment by msoutopico** [comment]
It seems I could deploy from another fresh clone from another computer. Closing this ticket, then.
