### ISSUE TITLE
Plugin typed configuration error: "TypeError: Subscripted generics cannot be used with class and instance checks"

### ISSUE THREAD

**Issue by Guts** [mkdocs/mkdocs#3753]
Hi there,

I'm the developer of the RSS plugin and recently I've been working on modernizing the plugin's configuration to fit typed and subtyped configuration started with Mkdocs 1.4: https://github.com/Guts/mkdocs-rss-plugin/blob/main/mkdocs_rss_plugin/config.py

But then I'm facing an issue with the compatibility with Python < 3.10. Something in options validation seems to rely on Python 3.10 features.

To reproduce it locally, I use the following Docker compose from my repo root with `docker build -f tests/fixtures/test-build-min-python.dockerfile -t mkdocs-plugins/rss-py38 .` :

```yml
FROM python:3.8.19

COPY . .

RUN python3 -m pip install --no-cache-dir -U pip setuptools wheel \
    && python3 -m pip install --no-cache-dir -U -r requirements/documentation.txt \
    && python3 -m pip install --no-cache-dir .

RUN mkdocs build
```

Here comes the log error:

```python
0.783 Traceback (most recent call last):                                                                                                                                                   
0.783   File "/usr/local/bin/mkdocs", line 8, in <module>                                                                                                                                  
0.783     sys.exit(cli())                                                                                                                                                                  
0.783   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__                                                                                                
0.783     return self.main(*args, **kwargs)
0.783   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
0.783     rv = self.invoke(ctx)
0.783   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
0.783     return _process_result(sub_ctx.command.invoke(sub_ctx))
0.783   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
0.783     return ctx.invoke(self.callback, **ctx.params)
0.783   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
0.783     return __callback(*args, **kwargs)
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 281, in build_command
0.783     cfg = config.load_config(**kwargs)
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 374, in load_config
0.783     errors, warnings = cfg.validate()
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 231, in validate
0.783     run_failed, run_warnings = self._validate()
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 188, in _validate
0.783     self[key] = config_option.validate(value)
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 186, in validate
0.783     return self.run_validation(value)
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1075, in run_validation
0.783     self.load_plugin_with_namespace(name, cfg)
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1113, in load_plugin_with_namespace
0.783     return (name, self.load_plugin(name, config))
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1161, in load_plugin
0.783     errors, warns = plugin.load_config(
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/plugins.py", line 96, in load_config
0.783     return self.config.validate()
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 231, in validate
0.783     run_failed, run_warnings = self._validate()
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 188, in _validate
0.783     self[key] = config_option.validate(value)
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 55, in validate
0.783     return self.run_validation(value)
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 110, in run_validation
0.783     failed, warnings = config.validate()
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 231, in validate
0.783     run_failed, run_warnings = self._validate()
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 188, in _validate
0.783     self[key] = config_option.validate(value)
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 186, in validate
0.783     return self.run_validation(value)
0.783   File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 344, in run_validation
0.783     if not isinstance(value, self._type):
0.783   File "/usr/local/lib/python3.8/typing.py", line 769, in __instancecheck__
0.783     return self.__subclasscheck__(type(obj))
0.783   File "/usr/local/lib/python3.8/typing.py", line 777, in __subclasscheck__
0.783     raise TypeError("Subscripted generics cannot be used with"
0.783 TypeError: Subscripted generics cannot be used with class and instance checks
```

To move on quickly, I've removed Python 3.8 and 3.9 support but I would like it to be temporary (especially for 3.9, 3.8 reaching EOL in few months). End-users who are using a build system where they can't select the Python version are stucked as @brabster reported it for Netlify (https://github.com/Guts/mkdocs-rss-plugin/issues/292). To restore this support, I've created a PR where I can track the failing tests: https://github.com/Guts/mkdocs-rss-plugin/pull/304.

But until now, I can't figure out where I went wrong on my plugin side.

**Comment by pawamoy** [comment]
Yep, `Union[bool, str]` cannot be used as an option type below 3.10. Not sure what way forward we have. I'm not familiar at all with the validation system. I wonder if MkDocs couldn't simply rely on Pydantic. If not, maybe plugins can, by allowing any option, and validating them at the earliest time with Pydantic.

**Comment by Guts** [comment]
Thanks a lot @pawamoy, I totally missed it! On closer inspection, I had actually removed the possibility of passing a bool to these options when I modernized the code. So all I had to do was remove this useless typing!
