### ISSUE TITLE
Build with SOURCE_DATE_EPOCH=0 fails

### ISSUE THREAD

**Issue by vedranmiletic** [mkdocs/mkdocs#3788]
FreeBSD 14.1, Python 3.11, MkDocs 1.6.0. I get the following:

```
% mkdocs new foo
INFO    -  Creating project directory: foo
INFO    -  Writing config file: foo/mkdocs.yml
INFO    -  Writing initial docs: foo/docs/index.md
% cd foo/
% env SOURCE_DATE_EPOCH=0 mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/vedran/foo/site
Traceback (most recent call last):
File "/usr/local/bin/mkdocs", line 8, in <module>
sys.exit(cli())
^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 284, in build_command
build.build(cfg, dirty=not clean)
File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 328, in build
_build_theme_template(template, env, files, config, nav)
File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 116, in _build_theme_template
with gzip.GzipFile(
^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/gzip.py", line 213, in __init__
self._write_gzip_header(compresslevel)
File "/usr/local/lib/python3.11/gzip.py", line 260, in _write_gzip_header
write32u(self.fileobj, int(mtime))
File "/usr/local/lib/python3.11/gzip.py", line 73, in write32u
output.write(struct.pack("<L", value))
^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: argument out of range
```

**Comment by vedranmiletic** [comment]
I also noticed that the `timestamp` in `gzip.GzipFile(..., mtime=timestamp)` is set to `-3600`. The timezone this machine uses is CEST.
