### ISSUE TITLE
mkdocs 0.12.1 traceback

### ISSUE THREAD

**Issue by mickeyl** [mkdocs/mkdocs#458]
```
/usr/local/bin/mkdocs build	--clean
Cleaning site directory
Building documentation to directory: site
ERROR - Error building page index.md
[E 150416 17:26:17 build:221] Error building page index.md
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.12.1', 'console_scripts', 'mkdocs')()
  File "/usr/local/lib/python3.4/dist-packages/mkdocs/main.py", line 77, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "/usr/local/lib/python3.4/dist-packages/mkdocs/main.py", line 52, in main
    build(config, clean_site_dir=clean_site_dir)
  File "/usr/local/lib/python3.4/dist-packages/mkdocs/build.py", line 252, in build
    build_pages(config)
  File "/usr/local/lib/python3.4/dist-packages/mkdocs/build.py", line 219, in build_pages
    _build_page(page, config, site_navigation, env, dump_json)
  File "/usr/local/lib/python3.4/dist-packages/mkdocs/build.py", line 173, in _build_page
    extensions=config['markdown_extensions'], strict=config['strict']
  File "/usr/local/lib/python3.4/dist-packages/mkdocs/build.py", line 36, in convert_markdown
    extensions=extensions
  File "/usr/local/lib/python3.4/dist-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/local/lib/python3.4/dist-packages/markdown/__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/local/lib/python3.4/dist-packages/markdown/__init__.py", line 291, in build_extension
    return module.makeExtension(**configs)
  File "/usr/local/lib/python3.4/dist-packages/mdx_smartypants/core.py", line 52, in makeExtension
    return SmartypantsExt(configs=configs)
  File "/usr/local/lib/python3.4/dist-packages/mdx_smartypants/core.py", line 41, in __init__
    self.configs = dict(configs)
TypeError: 'NoneType' object is not iterable
```

**Comment by mickeyl** [comment]
Oh, sorry, I've just seen that it's actually a traceback in mdx_smartypants.

**Comment by waylan** [comment]
Looks like you have an error in your `markdown_extensions` config value. What does that look like?

**Comment by mickeyl** [comment]
```markdown_extensions: [smartypants]```

I fixed it blindly by changing said part in ```/usr/local/lib/python3.4/dist-packages/mdx_smartypants/core.py``` to

```
if configs is not None:
   self.configs = dict(configs)
else:
   self.configs = {}
```

and with that it worked for me.

**Comment by waylan** [comment]
Ah, this is a bug in smartypants. They need to change their [`makeExtension`][1] function to:

```python
def makeExtension(**kwargs):
    return SomeExtension(**kwargs)
```

See Python-Markdown's [release notes][2] for more info.

By the way, a smartypants extension ships with recent versions of Python-Markdown called [smarty][3]. It will always work with the version of Python-Markdown it ships with.

[1]: https://bitbucket.org/jeunice/mdx_smartypants/src/3894e71c987bf0b554c1bf5a628c19fd045fd6f2/mdx_smartypants/core.py?at=default#cl-48
[2]: https://pythonhosted.org/Markdown/release-2.6.html#the-configs-keyword-is-deprecated
[3]: https://pythonhosted.org/Markdown/extensions/smarty.html
