### ISSUE TITLE
Regression when building docs

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#461]
I got this when building the Django REST Framework docs with 0.12.1

    $ mkdocs build 
    Building documentation to directory: site
    Directory site contains stale files. Use --clean to remove them.
    Traceback (most recent call last):
      File "/home/dougalmatthews/.virtualenvs/mkdocs/bin/mkdocs", line 9, in <module>
        load_entry_point('mkdocs==0.12.1', 'console_scripts', 'mkdocs')()
      File "/home/dougalmatthews/.virtualenvs/mkdocs/lib/python2.7/site-packages/mkdocs/main.py", line 77, in run_main
        main(cmd, args=sys.argv[2:], options=dict(opts))
      File "/home/dougalmatthews/.virtualenvs/mkdocs/lib/python2.7/site-packages/mkdocs/main.py", line 52, in main
        build(config, clean_site_dir=clean_site_dir)
      File "/home/dougalmatthews/.virtualenvs/mkdocs/lib/python2.7/site-packages/mkdocs/build.py", line 252, in build
        build_pages(config)
      File "/home/dougalmatthews/.virtualenvs/mkdocs/lib/python2.7/site-packages/mkdocs/build.py", line 209, in build_pages
        site_navigation = nav.SiteNavigation(config['pages'], config['use_directory_urls'])
      File "/home/dougalmatthews/.virtualenvs/mkdocs/lib/python2.7/site-packages/mkdocs/nav.py", line 37, in __init__
        _generate_site_navigation(pages_config, self.url_context, use_directory_urls)
      File "/home/dougalmatthews/.virtualenvs/mkdocs/lib/python2.7/site-packages/mkdocs/nav.py", line 243, in _generate_site_navigation
        header.children.append(page)
    AttributeError: 'Page' object has no attribute 'children'

**Comment by d0ugal** [comment]
The issue is when you don't specify the title for some pages but do for others. For example:

     - ['topics/ajax-csrf-cors.md', 'Topics', 'AJAX, CSRF & CORS']
     - ['topics/browser-enhancements.md', 'Topics', ]
     - ['topics/browsable-api.md', 'Topics', 'The Browsable API']

The build fails on `topics/browser-enhancements.md`

**Comment by d0ugal** [comment]
Fixing this is actually kinda gross. The issue is with turning a flat structure into a tree intelligently. Hopefully a new pages config will remove some of this hackyness eventually.
