### ISSUE TITLE
Doesn't work on Mac OS X Yosemite?

### ISSUE THREAD

**Issue by kud** [mkdocs/mkdocs#465]
```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.12.1', 'console_scripts', 'mkdocs')()
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 468, in load_entry_point
    else:
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 2563, in load_entry_point
    '.dist-info': DistInfoDistribution,
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 2254, in load
    return self.hashcmp >= other.hashcmp
  File "/usr/local/lib/python2.7/site-packages/mkdocs/main.py", line 14, in <module>
    from mkdocs.serve import serve
  File "/usr/local/lib/python2.7/site-packages/mkdocs/serve.py", line 3, in <module>
    from livereload import Server
  File "/usr/local/lib/python2.7/site-packages/livereload/__init__.py", line 14, in <module>
    from .server import Server, shell
  File "/usr/local/lib/python2.7/site-packages/livereload/server.py", line 16, in <module>
    import webbrowser
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/webbrowser.py", line 669, in <module>
    cmd = _synthesize(cmdline, -1)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/webbrowser.py", line 94, in _synthesize
    if controller and name.lower() == controller.basename:
AttributeError: 'MacOSXOSAScript' object has no attribute 'basename'
```

**Comment by d0ugal** [comment]
Strange. That error is coming from the Python module webbrowser. I've never known it to error like that before.

**Comment by d0ugal** [comment]
@kud does running this command from your shell work?

    python -c 'import webbrowser; webbrowser.open("http://www.mkdocs.org")'

**Comment by d0ugal** [comment]
It looks to me like there is something wrong with your python install, perhaps an issue with homebrew. I can't see how this is related to MkDocs.

**Comment by d0ugal** [comment]
Googling the error finds a wide array of people getting the error - no obvious fix for it tho' but they are all unrelated to MkDocs. Closing this for now, but let me know what you get with the command I provided above and I'll try tomorrow when I'm near my macbook.

**Comment by d0ugal** [comment]
FWIW, I've tested now on Yosometie with MkDocs `0.12.1` and everything worked fine. I tested building and serving a couple of projects and I tested the webbrowser module directly.

**Comment by kud** [comment]
```
python -c 'import webbrowser; webbrowser.open("http://www.mkdocs.org")'                                                                                              ⬆
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/webbrowser.py", line 669, in <module>
    cmd = _synthesize(cmdline, -1)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/webbrowser.py", line 94, in _synthesize
    if controller and name.lower() == controller.basename:
AttributeError: 'MacOSXOSAScript' object has no attribute 'basename'
```

**Comment by kud** [comment]
It could be indeed a trouble with python on homebrew. I'll check that.

**Comment by kud** [comment]
Related https://bugzilla.mozilla.org/show_bug.cgi?id=1012443

**Comment by drKnoxy** [comment]
fyi i have this bug, default python install. and running `python -c 'import webbrowser; webbrowser.open("http://www.mkdocs.org")'` just opened a browser like it was supposed to.

**Comment by kud** [comment]
Yep!

**Comment by d0ugal** [comment]
This is an issue with you Python environment/install, not MkDocs. If you installed with homebrew or another package manager, try following up with them. If you used the Python installer, try python itself for support.

**Comment by kud** [comment]
http://diary.kud.io/en/python-and-browser-environment-variable-are-not-friends-yet/

poke @drKnoxy

**Comment by meain** [comment]
For anyone still looking for an answer, just set `BROWESR` env variable in your shell to empty.
```sh
export BROWSER=   # balnk value
```
