### ISSUE TITLE
Why cant i use my modified Readthedocs theme without error?

### ISSUE THREAD

**Issue by Collizo4sky** [mkdocs/mkdocs#473]
I downloaded the readthedoc theme https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/readthedocs added it to my project root and modified the `base.html` to include disqus.

I added `theme_dir: 'readthedocs'` to mkdocs.yml file.

Even without the disqus code i.e unmodified, i get the following error when i try building the doc.

```
Traceback (most recent call last):
  File "c:\Python34\Scripts\mkdocs-script.py", line 9, in <module>
    load_entry_point('mkdocs==0.11.1', 'console_scripts', 'mkdocs')()
  File "c:\Python34\lib\site-packages\mkdocs\main.py", line 60, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "c:\Python34\lib\site-packages\mkdocs\main.py", line 36, in main
    build(config, clean_site_dir=clean_site_dir)
  File "c:\Python34\lib\site-packages\mkdocs\build.py", line 266, in build
    build_pages(config)
  File "c:\Python34\lib\site-packages\mkdocs\build.py", line 201, in build_pages

    build_404(config, env, site_navigation)
  File "c:\Python34\lib\site-packages\mkdocs\build.py", line 188, in build_404
    output_content = template.render(global_context)
  File "c:\Python34\lib\site-packages\jinja2\environment.py", line 969, in rende
r
    return self.environment.handle_exception(exc_info, True)
  File "c:\Python34\lib\site-packages\jinja2\environment.py", line 742, in handl
e_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Python34\lib\site-packages\jinja2\_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "c:\Python34\lib\site-packages\mkdocs\themes\mkdocs\404.html", line 1, in
 <module>
    {% extends "base.html" %}
  File "readthedocs\base.html", line 75, in <module>
    {% include "breadcrumbs.html" %}
  File "readthedocs\breadcrumbs.html", line 4, in <module>
    {% for doc in current_page.ancestors %}
  File "c:\Python34\lib\site-packages\jinja2\environment.py", line 397, in getat
tr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'current_page' is undefined
```

My question is, where does mkdocs download the readthedocs theme used in building the documentation when `theme` config is set to `readthedocs` ?

cc @d0ugal

**Comment by d0ugal** [comment]
I'm not sure - it is probably a conflict between the version of MkDocs you are using and the theme in GitHub. Use the github tag to get the same version as your mkdocs and try that?

**Comment by d0ugal** [comment]
Otherwise, can you link me to the documentation to have a look?

**Comment by Collizo4sky** [comment]
@d0ugal  I upgraded mkdocs and used the readthedocs theme bundled in o.12.2 which is the same as that of the master branch.

Everything is fine except that mkdocs is having problem parsing reathedocs' `css/theme.css` file.

Here is the error.

```
Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\tornado\web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "c:\Python34\lib\site-packages\livereload\handlers.py", line 195, in get
    data = f.read()
  File "c:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 9360: character maps to <undefined>
```



Mind you, when the site is built via `mkdocs build --clean` the css works and the design is perfect. but serving the documenation via `mkdocs serve` the css is broken obviously because mkdocs can't parse `css/theme.css`

**Comment by d0ugal** [comment]
Hmm, this appears to be some sort of Windows specific encoding issue with python-livereload

**Comment by Collizo4sky** [comment]
Is it something that is fix-able?

**Comment by d0ugal** [comment]
Yeah, so I'm 95% this is an issue with [python-livereload](https://github.com/lepture/python-livereload). The only idea I have for now is to try their development version, it seems the area the error is coming from has been changed lately - that may fix the issues. It looks like they fixed it here but have not done a release: https://github.com/lepture/python-livereload/pull/79

Otherwise I guess you need #445

**Comment by d0ugal** [comment]
I've asked upstream about a new release - we should follow up with them. https://github.com/lepture/python-livereload/issues/104

**Comment by Collizo4sky** [comment]
After running the command `mkdocs serve --no-rebuild`

Each time i load the documentation page, i get this error in CMD with the css obviously broken.

```
$ mkdocs serve --no-rebuild
Serving on http://127.0.0.1:8000
[I 150425 11:59:55 handlers:109] Browser Connected: http://127.0.0.1:8000/
[I 150425 11:59:55 handlers:118] Start watching changes
[I 150425 11:59:56 handlers:74] Reload 1 waiters: None
[I 150425 11:59:56 web:1825] 200 GET / (127.0.0.1) 57.06ms
[E 150425 11:59:56 web:1421] Uncaught exception GET /css/theme.css (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri=
'/css/theme.css', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Cache-Con
trol': 'max-age=0', 'Referer': 'http://127.0.0.1:8000/', 'Connection': 'keep-ali
ve', 'Host': '127.0.0.1:8000', 'Accept-Language': 'en-US,en;q=0.8', 'User-Agent'
: 'Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41
.0.2272.118 Safari/537.36 OPR/28.0.1750.51', 'Dnt': '1', 'Accept-Encoding': 'gzi
p, deflate, lzma, sdch', 'Accept': 'text/css,*/*;q=0.1'})
    Traceback (most recent call last):
      File "c:\Python34\lib\site-packages\tornado\web.py", line 1346, in _execut
e
        result = method(*self.path_args, **self.path_kwargs)
      File "c:\Python34\lib\site-packages\livereload\handlers.py", line 195, in
get
        data = f.read()
      File "c:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 9371:
 character maps to <undefined>
[E 150425 11:59:56 web:1825] 500 GET /css/theme.css (127.0.0.1) 11.01ms
[I 150425 11:59:56 web:1825] 200 GET /css/highlight.css (127.0.0.1) 2.00ms
[I 150425 11:59:56 web:1825] 200 GET /js/jquery-2.1.1.min.js (127.0.0.1) 50.26ms

[I 150425 11:59:56 web:1825] 200 GET /js/modernizr-2.8.3.min.js (127.0.0.1) 14.0
1ms
[I 150425 11:59:56 web:1825] 200 GET /js/highlight.pack.js (127.0.0.1) 98.06ms
[I 150425 11:59:56 web:1825] 200 GET /css/theme_extra.css (127.0.0.1) 5.00ms
[I 150425 11:59:56 web:1825] 304 GET /livereload.js (127.0.0.1) 1.00ms
[I 150425 11:59:56 web:1825] 200 GET /js/theme.js (127.0.0.1) 12.01ms
[I 150425 11:59:56 handlers:62] Ignore: docs\img\wp-profile-contact.png
[I 150425 11:59:57 web:1825] 304 GET /livereload.js (127.0.0.1) 1.00ms
[I 150425 11:59:57 handlers:109] Browser Connected: http://127.0.0.1:8000/
[I 150425 12:01:16 web:1825] 200 GET / (127.0.0.1) 2.00ms
[E 150425 12:01:16 web:1421] Uncaught exception GET /css/theme.css (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri=
'/css/theme.css', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Referer':
 'http://127.0.0.1:8000/', 'Connection': 'keep-alive', 'Host': '127.0.0.1:8000',
 'Accept-Language': 'en-US,en;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3
) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36 OPR/
28.0.1750.51', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, lzma, sdch', 'Acce
pt': 'text/css,*/*;q=0.1'})
    Traceback (most recent call last):
      File "c:\Python34\lib\site-packages\tornado\web.py", line 1346, in _execut
e
        result = method(*self.path_args, **self.path_kwargs)
      File "c:\Python34\lib\site-packages\livereload\handlers.py", line 195, in
get
        data = f.read()
      File "c:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 9371:
 character maps to <undefined>
[E 150425 12:01:17 web:1825] 500 GET /css/theme.css (127.0.0.1) 11.01ms
[I 150425 12:01:17 web:1825] 200 GET /css/highlight.css (127.0.0.1) 4.00ms
[I 150425 12:01:17 web:1825] 200 GET /css/theme_extra.css (127.0.0.1) 2.00ms
[I 150425 12:01:17 web:1825] 200 GET /js/jquery-2.1.1.min.js (127.0.0.1) 5.00ms
[I 150425 12:01:17 web:1825] 200 GET /js/modernizr-2.8.3.min.js (127.0.0.1) 2.00
ms
[I 150425 12:01:17 web:1825] 200 GET /js/highlight.pack.js (127.0.0.1) 8.01ms
[I 150425 12:01:17 web:1825] 200 GET /js/theme.js (127.0.0.1) 3.00ms
[I 150425 12:01:17 web:1825] 304 GET /livereload.js (127.0.0.1) 3.00ms
[I 150425 12:01:18 handlers:109] Browser Connected: http://127.0.0.1:8000/
[E 150425 12:01:32 web:1421] Uncaught exception GET /css/theme.css (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri=
'/css/theme.css', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Referer':
 'http://127.0.0.1:8000/', 'Connection': 'keep-alive', 'Host': '127.0.0.1:8000',
 'Accept-Language': 'en-US,en;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3
) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36 OPR/
28.0.1750.51', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, lzma, sdch', 'Acce
pt': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
'})
    Traceback (most recent call last):
      File "c:\Python34\lib\site-packages\tornado\web.py", line 1346, in _execut
e
        result = method(*self.path_args, **self.path_kwargs)
      File "c:\Python34\lib\site-packages\livereload\handlers.py", line 195, in
get
        data = f.read()
      File "c:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 9371:
 character maps to <undefined>
[E 150425 12:01:32 web:1825] 500 GET /css/theme.css (127.0.0.1) 10.01ms
```

**Comment by d0ugal** [comment]
--no-rebuild

Thus isn't a valid option, the issue I referenced is about a new possible feature. It doesn't exist yet.

So the error is just the same as you had before.

**Comment by Collizo4sky** [comment]
Ok. I hope it get resolved soonest.                                                                                                                                                                                                                                                                           Regards.Agbonghama Collins.                                                                                                                                                                                                                                         From: Dougal MatthewsSent: Saturday, 25 April 2015 12:16 PMTo: mkdocs/mkdocsReply To: mkdocs/mkdocsCc: Agbonghama CollinsSubject: Re: [mkdocs] Why cant i use my modified Readthedocs theme without error? (#473)--no-rebuild


Thus isn't a valid option, the issue I referenced is about a new possible feature. It doesn't exist yet.

So the error is just the same as you had before.

—Reply to this email directly or view it on GitHub.

**Comment by d0ugal** [comment]
Downgrading to MkDocs 0.11 may help you until it does.

**Comment by Collizo4sky** [comment]
Will do that right away and let you know how it goes.                                                                                                                                                                                                                                                                           Regards.Agbonghama Collins.                                                                                                                                                                                                                                         From: Dougal MatthewsSent: Saturday, 25 April 2015 1:15 PMTo: mkdocs/mkdocsReply To: mkdocs/mkdocsCc: Agbonghama CollinsSubject: Re: [mkdocs] Why cant i use my modified Readthedocs theme without error? (#473)Downgrading to MkDocs 0.11 may help you until it does.

—Reply to this email directly or view it on GitHub.

**Comment by lepture** [comment]
@d0ugal python-livereload is using tornado's default StaticHandler now. FYI.

**Comment by d0ugal** [comment]
@lepture Awesome, thanks!
