### ISSUE TITLE
Unicode Errors with livereload (Windows/Python 3)

### ISSUE THREAD

**Issue by bwmarrin** [mkdocs/mkdocs#518]
I'm testing mkdocs on my Windows computer.  I installed Python 3.4 using Chocolatey per the mkdocs instructions.  I then installed mkdocs using pip.  

If I set the theme to readthedocs and use mkdocs serve I get an unstyled page and on my console window there are errors indicating that it cannot find the css/js files.

I may very well be doing something wrong as I am new to mkdocs :)

**Comment by d0ugal** [comment]
Interesting. It certainly sounds like you are doing it right. Is there anything in the terminal that looks like an error? Can you send a screenshot of the unstyled page? I want to see if it looks like the right HTML.

**Comment by bwmarrin** [comment]
console errors 

```
[E 150512 11:51:38 web:1421] Uncaught exception GET /css/theme.css (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/css/theme.css', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Accept': 'text/css,*/*;q=0.1', 'Accept-Language': 'en-US,en;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36', 'Host': '127.0.0.1:8000', 'Referer': 'http://127.0.0.1:8000/', 'Accept-Encoding': 'gzip, deflate, sdch'})
    Traceback (most recent call last):
      File "C:\tools\python\lib\site-packages\tornado\web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\tools\python\lib\site-packages\livereload\handlers.py", line 195, in get
        data = f.read()
      File "C:\tools\python\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 9360: character maps to <undefined>
[E 150512 11:51:38 web:1825] 500 GET /css/theme.css (127.0.0.1) 3.00ms
```

Screenshot..

![mkdocs-readthedocs](https://cloud.githubusercontent.com/assets/7683654/7593190/e10d452c-f89d-11e4-84d9-6f7fb18febd4.png)

**Comment by waylan** [comment]
Hmm, interesting. Based upon the error message, it appears that the CSS file is causing a UnicodeDecodeError because it is using the wrong codec (probably because you are on Windows). Unfortunately, the error is being raised when LiveReload tries to read the CSS file to serve it. And I'm not aware of any way to tell LiveReload which codec to use.

Actually, I took a look at the source code for LiveReload and in their most recent change to their handlers, they completely ripped out the offending code (see [f4c31d823a][1]) and fall back on Tornado for this. I suspect Tornado will act correctly here. Unfortunately, that change won't be available until the next release unless you are comfortable using the dev version of LiveReload from GitHub. I'm not aware of any other workarounds in the interim other than don't use Windows.

[1]: https://github.com/lepture/python-livereload/commit/f4c31d823a2236b9c898246c115444b88ff41aba

**Comment by bwmarrin** [comment]
Well, that's depressing news.  Okay, maybe not that depressing.  I don't really like Windows - just I'm a bit stuck using it occasionally and it would be handy for MkDocs to work on it. 

Thanks for looking into it.

**Comment by d0ugal** [comment]
@bwmarrin There are a few options here, so don't get too depressed! :smile: 

1. You could try using the previous MkDocs release, before we added python-livereload.

    pip install mkdocs==0.11.1

2. Try the development version of python-livereload as they are [very close to a release ](https://github.com/lepture/python-livereload/issues/105).

    pip install https://github.com/lepture/python-livereload/archive/master.zip

3. Try the development version of MkDocs, I have added a way to disable livereload. You can install it like you did with the stable release, but directly point to github. I'm building up towards a release, so hopefully you wont need to run this way for long. The downside of this approach is that it wont automatically rebuild the docs, so you need to restart the server after each edit which is a pain.

    pip install https://github.com/mkdocs/mkdocs/archive/master.zip
    mkdocs serve --no-livereload

I'd be interested to know if any of these work for you! **Personally, I'd try 2, then 3, then 1.**

**Comment by d0ugal** [comment]
I've just been speaking to somebody else on IRC that is also running into this issue.

**Comment by bwmarrin** [comment]
Okay, Option 2: 
```
 pip install https://github.com/lepture/python-livereload/archive/master.zip
Collecting https://github.com/lepture/python-livereload/archive/master.zip
  Downloading https://github.com/lepture/python-livereload/archive/master.zip
     / 32kB 420kB/s
Requirement already satisfied (use --upgrade to upgrade): tornado in c:\tools\python\lib\site-packages (from livereload==2.4)
Requirement already satisfied (use --upgrade to upgrade): six in c:\tools\python\lib\site-packages (from livereload==2.4)
Requirement already satisfied (use --upgrade to upgrade): certifi in c:\tools\python\lib\site-packages (from tornado->livereload==2.4)
Installing collected packages: livereload
  Found existing installation: livereload 2.3.2
    Uninstalling livereload-2.3.2:
      Successfully uninstalled livereload-2.3.2
  Running setup.py install for livereload
Successfully installed livereload-2.4
```

Load up mkdocs and open the website.  I get the below error:
```
 mkdocs serve
Serving on http://127.0.0.1:8000
ERROR:tornado.application:Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0', 'Accept-Language': 'en-US,en;q=0.5', 'X-Clickoncesupport': '( .NET CLR 3.5.30729; .NET4.0E)', 'Host': '127.0.0.1:8000', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "C:\tools\python\lib\site-packages\tornado\web.py", line 1348, in _execute
    result = yield result
  File "C:\tools\python\lib\site-packages\tornado\gen.py", line 807, in run
    value = future.result()
  File "C:\tools\python\lib\site-packages\tornado\concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\tools\python\lib\site-packages\tornado\gen.py", line 212, in wrapper
    yielded = next(result)
  File "C:\tools\python\lib\site-packages\tornado\web.py", line 2189, in get
    yield self.flush()
  File "C:\tools\python\lib\site-packages\tornado\web.py", line 832, in flush
    self._status_code, self._headers, chunk, include_footers)
  File "C:\tools\python\lib\site-packages\livereload\server.py", line 89, in transform_first_chunk
    chunk = chunk.replace(HEAD_END, self.script + HEAD_END)
TypeError: Can't convert 'bytes' object to str implicitly
ERROR:tornado.general:Cannot send error response after headers written
```

Guess the dev master isn't quite in a stable state?

**Comment by d0ugal** [comment]
@bwmarrin I guess not - `pip install python-livereload==2.3.2` will revert it back to the released version

**Comment by bwmarrin** [comment]
Option 3: 

Works :)  the readthedocs theme looks just fine and normal.

**Comment by d0ugal** [comment]
Great, that's good to know. I reported your error upstream with python-livereload.

**Comment by d0ugal** [comment]
I'm keeping this open to track the problem, as it has come up a few times. However, as it is upstream we can't really fix it. So bumping to the next milestone, it shouldn't block us releasing.

**Comment by lepture** [comment]
It should be fixed now: https://github.com/lepture/python-livereload/commit/1d850ab11d7229dec2431ee20654a35262f6c30d

**Comment by d0ugal** [comment]
@lepture Thanks!

@bwmarrin You may want to try updating livereload, I guess you are using MkDocs dev with `--no-livereload`?

**Comment by bwmarrin** [comment]
Hmn, I tried with the "master" of both livereload and mkdocs but I get an error when I run mkdocs serve.

```
INFO    -  Building documentation...
Serving on http://127.0.0.1:8000
Traceback (most recent call last):
  File "C:\tools\python\Scripts\mkdocs-script.py", line 9, in <module>
    load_entry_point('mkdocs==0.13.0.dev0', 'console_scripts', 'mkdocs')()
  File "C:\tools\python\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "C:\tools\python\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\tools\python\lib\site-packages\click\core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\tools\python\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\tools\python\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "C:\tools\python\lib\site-packages\mkdocs\cli.py", line 75, in serve_command
    livereload=livereload,
  File "C:\tools\python\lib\site-packages\mkdocs\serve.py", line 83, in serve
    _livereload(host, port, config, builder, tempdir)
  File "C:\tools\python\lib\site-packages\mkdocs\serve.py", line 26, in _livereload
    server.serve(root=site_dir, host=host, port=int(port), restart_delay=0)
  File "C:\tools\python\lib\site-packages\livereload\server.py", line 276, in serve
    self.application(port, host, liveport=liveport, debug=debug)
  File "C:\tools\python\lib\site-packages\livereload\server.py", line 220, in application
    b'<script src="http://{host}:{port}/livereload.js"></script>'
AttributeError: 'bytes' object has no attribute 'format'
```

Maybe I need to try something other than "master" ?

If I use the no-livereload option, it does run even with both master branches installed

```
 mkdocs serve --no-livereload
INFO    -  Building documentation...
INFO    -  Running at: http://127.0.0.1:8000/
INFO    -  Hold ctrl+c to quit.
```

**Comment by d0ugal** [comment]
@bwmarrin Thanks, that does look related to @lepture's change.

**Comment by lepture** [comment]
yeah. @bwmarrin Are you using Python 3 on Windows?

**Comment by lepture** [comment]
@d0ugal Do you know any way to write tests for the server part?

**Comment by d0ugal** [comment]
> I'm testing mkdocs on my Windows computer. I installed Python 3.4 using Chocolatey per the mkdocs instructions. I then installed mkdocs using pip.

@lepture Yup, @bwmarrin is using Windows and Python 3. Would you suggest we recommend users use Python 2 on Windows?

**Comment by d0ugal** [comment]
@lepture Which bit is missing tests exactly> I could try and take a look.

**Comment by lepture** [comment]
@d0ugal You can't force them to use a specified version. I've updated the master with `tornado.escape.utf8` it should works on windows now.

**Comment by d0ugal** [comment]
True, we can't force a version but I can recommend one :)

@bwmarrin Would you mind testing again? Would be really useful for us!

**Comment by bwmarrin** [comment]
Sure, I don't mind at all.  So, install both from master and test again, right?

**Comment by bwmarrin** [comment]
Looks good,

```
PS Microsoft.PowerShell.Core\FileSystem::\\fs0\Portal\Docs\docs\Documentation> pip install https://github.com/lepture/python-livereload/archive/master.zip
Collecting https://github.com/lepture/python-livereload/archive/master.zip
  Downloading https://github.com/lepture/python-livereload/archive/master.zip
Requirement already satisfied (use --upgrade to upgrade): tornado in c:\tools\python\lib\site-packages (from livereload==2.4)
Requirement already satisfied (use --upgrade to upgrade): six in c:\tools\python\lib\site-packages (from livereload==2.4)
Requirement already satisfied (use --upgrade to upgrade): certifi in c:\tools\python\lib\site-packages (from tornado->livereload==2.4)
Installing collected packages: livereload
  Running setup.py install for livereload
Successfully installed livereload-2.4
PS Microsoft.PowerShell.Core\FileSystem::\\fs0\Portal\Docs\docs\Documentation> pip install https://github.com/mkdocs/mkdocs/archive/master.zip
Collecting https://github.com/mkdocs/mkdocs/archive/master.zip
  Downloading https://github.com/mkdocs/mkdocs/archive/master.zip
     \ 6.3MB 2.6MB/s
Requirement already satisfied (use --upgrade to upgrade): click>=4.0 in c:\tools\python\lib\site-packages (from mkdocs==0.13.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): ghp-import>=0.4.1 in c:\tools\python\lib\site-packages (from mkdocs==0.13.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.7.1 in c:\tools\python\lib\site-packages (from mkdocs==0.13.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): livereload>=2.3.2 in c:\tools\python\lib\site-packages (from mkdocs==0.13.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): Markdown>=2.3.1 in c:\tools\python\lib\site-packages (from mkdocs==0.13.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in c:\tools\python\lib\site-packages (from mkdocs==0.13.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in c:\tools\python\lib\site-packages (from mkdocs==0.13.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.1 in c:\tools\python\lib\site-packages (from mkdocs==0.13.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in c:\tools\python\lib\site-packages (from Jinja2>=2.7.1->mkdocs==0.13.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): certifi in c:\tools\python\lib\site-packages (from tornado>=4.1->mkdocs==0.13.0.dev0)
Installing collected packages: mkdocs
  Running setup.py install for mkdocs
Successfully installed mkdocs-0.13.0.dev0
PS Microsoft.PowerShell.Core\FileSystem::\\fs0\Portal\Docs\docs\Documentation>
PS Microsoft.PowerShell.Core\FileSystem::\\fs0\Portal\Docs\docs\Documentation>
PS Microsoft.PowerShell.Core\FileSystem::\\fs0\Portal\Docs\docs\Documentation> mkdocs serve
INFO    -  Building documentation...
Serving on http://127.0.0.1:8000
INFO:livereload:Browser Connected: http://127.0.0.1:8000/
INFO:livereload:Start watching changes
INFO:livereload:Reload 1 waiters: None
INFO:livereload:Browser Connected: http://127.0.0.1:8000/
INFO:livereload:Ignore: \\fs0\Portal\Docs\docs\Documentation\docs\Projects\Portal.md
INFO:livereload:Browser Connected: http://127.0.0.1:8000/test/
INFO:livereload:Browser Connected: http://127.0.0.1:8000/Projects/Portal/
INFO:livereload:Browser Connected: http://127.0.0.1:8000/
INFO    -  Building documentation...
INFO:livereload:Reload 1 waiters: \\fs0\Portal\Docs\docs\Documentation\docs\test.md
INFO:livereload:Browser Connected: http://127.0.0.1:8000/
INFO:livereload:Ignore: \\fs0\Portal\Docs\docs\Documentation\docs\test.md~
```

**Comment by bwmarrin** [comment]
As a side note, if you ever need some future Windows testing - I'm happy to help.

**Comment by d0ugal** [comment]
Awesome, that does look good!

Also, I'll probably take you up on that offer, I find Windows support tricky as I don't run it.

**Comment by d0ugal** [comment]
Closing this as it should be followed up here: https://github.com/lepture/python-livereload/issues/105
