### ISSUE TITLE
Install broken

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#548]
It looks like the addition of a [unicode filename](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/tests/integration/unicode/docs/%E6%B5%8B%E8%AF%95.md) has broken pip.

    Exception:
    Traceback (most recent call last):
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
        status = self.run(options, args)
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/commands/install.py", line 280, in run
        requirement_set.prepare_files(finder)
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/req/req_set.py", line 317, in prepare_files
        functools.partial(self._prepare_file, finder))
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/req/req_set.py", line 304, in _walk_req_to_install
        more_reqs = handler(req_to_install)
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/req/req_set.py", line 469, in _prepare_file
        session=self.session)
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
        session,
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/download.py", line 677, in unpack_http_url
        unpack_file(from_path, location, content_type, link)
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/utils/__init__.py", line 644, in unpack_file
        flatten=not filename.endswith('.whl')
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/utils/__init__.py", line 531, in unzip_file
        leading = has_leading_dir(zip.namelist()) and flatten
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/utils/__init__.py", line 246, in has_leading_dir
        prefix, rest = split_leading_dir(path)
      File "/home/dougalmatthews/.virtualenvs/mkdocs-versioned/lib/python2.7/site-packages/pip/utils/__init__.py", line 230, in split_leading_dir
        path = str(path)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 52-53: ordinal not in range(128)

**Comment by d0ugal** [comment]
Hmm, this appears to be a bug/limitation with archive installs only.

This fails:

    pip install -UI https://github.com/mkdocs/mkdocs/archive/master.zip

This works:

    pip install git+https://github.com/mkdocs/mkdocs.git

**Comment by waylan** [comment]
What about wheels (see #469)?

I don't know the answer, just wondering if that helps.

**Comment by d0ugal** [comment]
Good question. I am curious to know that too. It may not even be an issue generally, but unfortunately I have been telling beta testers to install this way so I don't need to check they have git installed.

Excluding the file in the manifest may help too.

**Comment by ProfYaffle** [comment]
FWIW, I can confirm that the zip method does indeed fail and the git method seems to work. And yes, I have git installed.

Only posting so this perhaps goes up Google's search ranking :)

**Comment by d0ugal** [comment]
It looks like the upstream bug is https://github.com/pypa/pip/issues/1140 and a posslbe fix can be found at https://github.com/pypa/pip/pull/1473

**Comment by d0ugal** [comment]
Interestingly the `.tar.gz` seems work fine. Will this work on Windows?

    pip install https://github.com/mkdocs/mkdocs/archive/master.tar.gz

**Comment by d0ugal** [comment]
It looks like they use tarfile, so it should work fine.
