### ISSUE TITLE
pip install fails on windows

### ISSUE THREAD

**Issue by AmazingHorse** [mkdocs/mkdocs#567]
Hello!

I am trying to install mkdocs on a w7 box, x64, powershell as admin, python installed via choco per the guide.

I ran the following commands and get one of two below results:

Result 1:
```
PS C:\tools> python --version
Python 3.4.3
PS C:\tools> pip --version
pip 6.0.8 from C:\tools\python\lib\site-packages (python 3.4)
PS C:\tools> pip install mkdocs
You are using pip version 6.0.8, however version 7.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting mkdocs
  Using cached mkdocs-0.13.1-py2.py3-none-any.whl
Collecting ghp-import>=0.4.1 (from mkdocs)
  Using cached ghp-import-0.4.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): livereload>=2.3.2 in c:\tools\python\lib\site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.1 in c:\tools\python\lib\site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.7.1 in c:\tools\python\lib\site-packages (from mkdocs)
Collecting click>=4.0 (from mkdocs)
  Using cached click-4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in c:\tools\python\lib\site-packages (from mkdocs)
Collecting six>=1.9.0 (from mkdocs)
  Using cached six-1.9.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): Markdown>=2.3.1 in c:\tools\python\lib\site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in c:\tools\python\lib\site-packages (from Jinja2>=2.7.1->mkdocs)
Installing collected packages: six, click, ghp-import, mkdocs

  Exception:
  Traceback (most recent call last):
    File "C:\tools\python\lib\site-packages\pip\basecommand.py", line 232, in main
      status = self.run(options, args)
    File "C:\tools\python\lib\site-packages\pip\commands\install.py", line 347, in run
      root=options.root_path,
    File "C:\tools\python\lib\site-packages\pip\req\req_set.py", line 549, in install
      **kwargs
    File "C:\tools\python\lib\site-packages\pip\req\req_install.py", line 754, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "C:\tools\python\lib\site-packages\pip\req\req_install.py", line 963, in move_wheel_files
      isolated=self.isolated,
    File "C:\tools\python\lib\site-packages\pip\wheel.py", line 234, in move_wheel_files
      clobber(source, lib_dir, True)
    File "C:\tools\python\lib\site-packages\pip\wheel.py", line 212, in clobber
      shutil.copyfile(srcfile, destfile)
    File "C:\tools\python\lib\shutil.py", line 109, in copyfile
      with open(dst, 'wb') as fdst:
  PermissionError: [Errno 13] Permission denied: 'C:\\tools\\python\\Lib\\site-packages\\__pycache__\\six.cpython-34.pyc'
```

Result 2 (snipped for brevity):
```
PS C:\tools> python --version
Python 3.4.3
PS C:\tools> pip --version
pip 6.0.8 from C:\tools\python\lib\site-packages (python 3.4)
PS C:\tools> pip install mkdocs
You are using pip version 6.0.8, however version 7.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting mkdocs
  Using cached mkdocs-0.13.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in c:\tools\python\lib\site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): Markdown>=2.3.1 in c:\tools\python\lib\site-packages (from mkdocs)
Collecting click>=4.0 (from mkdocs)
  Using cached click-4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.1 in c:\tools\python\lib\site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): livereload>=2.3.2 in c:\tools\python\lib\site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.7.1 in c:\tools\python\lib\site-packages (from mkdocs)
Collecting ghp-import>=0.4.1 (from mkdocs)
  Using cached ghp-import-0.4.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in c:\tools\python\lib\site-packages (from mkdocs)

Requirement already satisfied (use --upgrade to upgrade): markupsafe in c:\tools\python\lib\site-packages (from Jinja2>=2.7.1->mkdocs)
Installing collected packages: ghp-import, click, mkdocs
  Running setup.py install for ghp-import

<<<<snip>>>>

       Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "C:\Users\Administrator\AppData\Local\Temp\pip-build-yeq7_z8w\ghp-import\setup.py", line 32, in <module>

        scripts = ['ghp-import']

      File "C:\tools\python\lib\distutils\core.py", line 148, in setup

        dist.run_commands()

      File "C:\tools\python\lib\distutils\dist.py", line 955, in run_commands

        self.run_command(cmd)

      File "C:\tools\python\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\tools\python\lib\site-packages\setuptools\command\install.py", line 61, in run

        return orig.install.run(self)

      File "C:\tools\python\lib\distutils\command\install.py", line 551, in run

        self.run_command(cmd_name)

      File "C:\tools\python\lib\distutils\cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "C:\tools\python\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\tools\python\lib\site-packages\setuptools\command\install_scripts.py", line 16, in run

        import setuptools.command.easy_install as ei

      File "C:\tools\python\lib\site-packages\setuptools\command\easy_install.py", line 47, in <module>

        from setuptools.package_index import PackageIndex

      File "C:\tools\python\lib\site-packages\setuptools\package_index.py", line 16, in <module>

        from setuptools import ssl_support

      File "C:\tools\python\lib\site-packages\setuptools\ssl_support.py", line 38, in <module>

        exec("from %s import %s" % (module, what))

      File "<string>", line 1, in <module

    ----------------------------------------
    Command "C:\tools\python\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-build-yeq7_z8w\\ghp-import\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Administrator\AppData\Local\Temp\pip-j83m884o-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Administrator\AppData\Local\Temp\pip-build-yeq7_z8w\ghp-import
```

Note I've cached some of the packages as I have run through the install multiple times to verify if it is reproducible.

Any thoughts as to what I'm doing wrong here, and why I might be getting two different results?

Cheers!

**Comment by d0ugal** [comment]
Can you show me the output of a `pip freeze`? It might be that updating to a new setuptools would help.

**Comment by AmazingHorse** [comment]
@dougal:

```
PS C:\tools\python\Lib\site-packages\pip-6.0.8.dist-info> pip freeze
You are using pip version 6.0.8, however version 7.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
eagle-automation==0.0.1
ghp-import==0.4.1
Jinja2==2.7.3
livereload==2.3.2
Markdown==2.6.2
MarkupSafe==0.23
mercurial==2.3
pathtools==0.1.2
PyYAML==3.11
six==1.9.0
tornado==4.2
```

That being said, I tried pip again after a day and restarting my admin powershell...and now it works. So I guess this should be closed. Damnit windows. >:(

**Comment by d0ugal** [comment]
Haha, yeah, windows does seem to have the weirdest Python bugs. Glad it works now!
