### ISSUE TITLE
Exception after fresh install

### ISSUE THREAD

**Issue by AndyBehr** [mkdocs/mkdocs#570]
I installed mkdocs using (on Mac OS Yosemite)
```
$ sudo pip install mkdocs 
...(standard progress bars, didn't see anything strange here)...
Successfully installed Jinja2-2.7.3 Markdown-2.6.2 PyYAML-3.11 backports.ssl-match-hostname-3.4.0.2 certifi-2015.4.28 click-4.0 ghp-import-0.4.1 livereload-2.4.0 markupsafe-0.23 mkdocs-0.13.1 six-1.9.0 tornado-4.2
```

I get this error call mkdocs from the cli:
```
$ mkdocs
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 7, in <module>
    from mkdocs.cli import cli
  File "/Library/Python/2.7/site-packages/mkdocs/cli.py", line 11, in <module>
    from mkdocs import serve
  File "/Library/Python/2.7/site-packages/mkdocs/serve.py", line 6, in <module>
    from mkdocs.config import load_config
  File "/Library/Python/2.7/site-packages/mkdocs/config/__init__.py", line 1, in <module>
    from mkdocs.config.base import load_config
  File "/Library/Python/2.7/site-packages/mkdocs/config/base.py", line 17, in <module>
    class Config(six.moves.UserDict):
AttributeError: '_MovedItems' object has no attribute 'UserDict'
```

Python version
```
$ python --version
Python 2.7.6
```

Any idea what this could be?

Andy

**Comment by d0ugal** [comment]
This is an odd one. I'm really not sure. Does this display a similar error?

    python -c 'import six; six.moves.UserDict'

**Comment by AndyBehr** [comment]
Yes that results in the same error...
```
$ python -c 'import six; six.moves.UserDict'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: '_MovedItems' object has no attribute 'UserDict'
```
But that gave me an idea. I seems there is another version of six installed somewhere and that version is preferred:
```
$ python -c 'import six; print six.__version__'
1.4.1
```
Strange. I will get rid of the old version.

**Comment by d0ugal** [comment]
@AndyBehr aha, yes, that'll be it. It sounds like you have something a bit strange in your environment. The output you provided above shows six 1.9.0. So I guess it is likely to be a PYTHONPATH issue.

Closing this as it doesn't seem to be MkDocs related but feel free to follow up if you still have issues!

**Comment by Collizo4sky** [comment]
Same here. on fresh upgrade, i got this error

```
$ pip install -U mkdocs
←[33mYou are using pip version 6.1.1, however version 7.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.←[0m
Collecting mkdocs
  Downloading mkdocs-0.13.1-py2.py3-none-any.whl (5.5MB)
←[K    100% |################################| 5.5MB 34kB/s eta 0:00:01
Requirement already up-to-date: six>=1.9.0 in c:\python34\lib\site-packages (fro
m mkdocs)
Collecting tornado>=4.1 (from mkdocs)
  Downloading tornado-4.2.tar.gz (433kB)
←[K    89% |############################    | 389kB 108kB/s eta 0:00:01←[31m  Ex
ception:
  Traceback (most recent call last):
    File "c:\Python34\lib\site-packages\pip\_vendor\requests\packages\urllib3\re
sponse.py", line 203, in read
      data = self._fp.read(amt)
    File "c:\Python34\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py"
, line 49, in read
      data = self.__fp.read(amt)
    File "c:\Python34\lib\http\client.py", line 500, in read
      return super(HTTPResponse, self).read(amt)
    File "c:\Python34\lib\http\client.py", line 539, in readinto
      n = self.fp.readinto(b)
    File "c:\Python34\lib\socket.py", line 374, in readinto
      return self._sock.recv_into(b)
    File "c:\Python34\lib\ssl.py", line 751, in recv_into
      return self.read(nbytes, buffer)
    File "c:\Python34\lib\ssl.py", line 623, in read
      v = self._sslobj.read(len, buffer)
  socket.timeout: The read operation timed out

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "c:\Python34\lib\site-packages\pip\basecommand.py", line 246, in main
      status = self.run(options, args)
    File "c:\Python34\lib\site-packages\pip\commands\install.py", line 342, in r
un
      requirement_set.prepare_files(finder)
    File "c:\Python34\lib\site-packages\pip\req\req_set.py", line 345, in prepar
e_files
      functools.partial(self._prepare_file, finder))
    File "c:\Python34\lib\site-packages\pip\req\req_set.py", line 290, in _walk_
req_to_install
      more_reqs = handler(req_to_install)
    File "c:\Python34\lib\site-packages\pip\req\req_set.py", line 487, in _prepa
re_file
      download_dir, do_download, session=self.session,
    File "c:\Python34\lib\site-packages\pip\download.py", line 827, in unpack_ur
l
      session,
    File "c:\Python34\lib\site-packages\pip\download.py", line 673, in unpack_ht
tp_url
      from_path, content_type = _download_http_url(link, session, temp_dir)
    File "c:\Python34\lib\site-packages\pip\download.py", line 888, in _download
_http_url
      _download_url(resp, link, content_file)
    File "c:\Python34\lib\site-packages\pip\download.py", line 621, in _download
_url
      for chunk in progress_indicator(resp_read(4096), 4096):
    File "c:\Python34\lib\site-packages\pip\utils\ui.py", line 133, in iter
      for x in it:
    File "c:\Python34\lib\site-packages\pip\download.py", line 586, in resp_read

      decode_content=False):
    File "c:\Python34\lib\site-packages\pip\_vendor\requests\packages\urllib3\re
sponse.py", line 273, in stream
      data = self.read(amt=amt, decode_content=decode_content)
    File "c:\Python34\lib\site-packages\pip\_vendor\requests\packages\urllib3\re
sponse.py", line 218, in read
      raise ReadTimeoutError(self._pool, None, 'Read timed out.')
  pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnec
tionPool(host='pypi.python.org', port=443): Read timed out.
←[0m
```

**Comment by waylan** [comment]
Actually @Collizo4sky that is a connection time out error. Either you have (or had) a bad connection or the server failed while you were downloading the various packages. That is not related to mkdocs at all.

**Comment by d0ugal** [comment]
Agreed. @Collizo4sky try again, it should work. pip should really give a nicer error for that case.
