### ISSUE TITLE
0.13.2 not installing in OSX

### ISSUE THREAD

**Issue by lbenet** [mkdocs/mkdocs#577]
A new fresh install of mkdocs is not working. Here is the output
```
> pip install mkdocs
Downloading/unpacking mkdocs
  Downloading mkdocs-0.13.2-py2.py3-none-any.whl (5.6MB): 5.6MB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1265, in prepare_files
    req_to_install.extras):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 2506, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 2476, in _parsed_pkg_info
    self._pkg_info = Parser().parsestr(self.get_metadata(self.PKG_INFO))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 1361, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 1470, in _get
    stream = open(path, 'rb')
IOError: [Errno 2] No such file or directory: '/private/var/folders/rj/4bjl_08n3vndl5l7ln00kktm0000gn/T/pip_build_benet/mkdocs/mkdocs-0.13.1.dist-info/METADATA'

Storing debug log for failure in /Users/benet/.pip/pip.log
```

I think this is unrelated to #576  (or #570) since
```
python -c 'import six; print(six.__version__); print(six.__file__)'
1.9.0
/usr/local/Cellar/matplotlib/1.4.3/libexec/lib/python2.7/site-packages/six.pyc
```

Best,
Luis

**Comment by waylan** [comment]
This looks like a problem with the wheel file. The error is saying that it can't find the METADATA file (which should have been auto-generated when the wheel was created) in the wheel.

As a workaround, you could try downloading the source file instead:

    pip install https://pypi.python.org/packages/source/m/mkdocs/mkdocs-0.13.2.tar.gx

**Comment by d0ugal** [comment]
Very odd, I've installed the wheel a bunch of times now.

**Comment by lbenet** [comment]
The link above didn't quite work, but the following does:
https://pypi.python.org/packages/source/m/mkdocs/mkdocs-0.13.2.tar.gz#md5=91cf6e3dc48d42209440e2ab22f4bce1

Thanks a lot!

**Comment by d0ugal** [comment]
I updated @waylan's comment - it should work now too. It should be .tar.gz not .tar.gx

**Comment by lbenet** [comment]
Thanks a lot again.
Shall I close this issue?

**Comment by d0ugal** [comment]
I'll close it. If this comes up again I'll worry about a problem with the wheel.
