### ISSUE TITLE
mkdocs throws python errors after first build regarding bad unicode in mkdocs.yml

### ISSUE THREAD

**Issue by brianjking** [mkdocs/mkdocs#742]
```
brianjking@bk-mbp13  ~/documents/dev/dockdogs/dockdogs-scheduling   master ●  mkdocs serve
/usr/local/lib/python2.7/site-packages/mkdocs/cli.py:86: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/site-packages/mkdocs/cli.py:100: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/site-packages/mkdocs/cli.py:125: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/site-packages/mkdocs/cli.py:145: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/site-packages/mkdocs/cli.py:176: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/usr/local/lib/python2.7/site-packages/mkdocs/cli.py:194: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
INFO    -  Building documentation...
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/cli.py", line 112, in serve_command
    livereload=livereload,
  File "/usr/local/lib/python2.7/site-packages/mkdocs/serve.py", line 78, in serve
    config = builder()
  File "/usr/local/lib/python2.7/site-packages/mkdocs/serve.py", line 71, in builder
    theme=theme,
  File "/usr/local/lib/python2.7/site-packages/mkdocs/config/base.py", line 143, in load_config
    cfg.load_file(config_file)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/config/base.py", line 96, in load_file
    return self.load_dict(utils.yaml_load(config_file))
  File "/usr/local/lib/python2.7/site-packages/mkdocs/utils/__init__.py", line 58, in yaml_load
    return yaml.load(source, Loader)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 403, in parse_indentless_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/usr/local/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/Users/brianjking/Documents/Dev/DockDogs/dockdogs-scheduling/mkdocs.yml", line 5, column 1
```

## mkdocs.yml

```
site_name: DockDogs Scheduling
pages:
- Home: index.md
- Getting Started
        - Basics and Introduction: getting started/Basics and Introduction.md
        - Status Icon Legend: getting started/Status Icon Legend.md
        - FAQS: getting started/FAQs.md
- Reporting
        - Reporting Basics: Reporting Basics.md
        - Creating A New Report: reporting/Creating A New Report.md
        - Pre-Built Sponsors Report: Pre-Built Sponsors Report.md
- Notifications
        - Pre-Built Notifications: notifications/Pre-Built Notifications.md
        - Notification Basics: notifications/Notifications Basics.md
theme: readthedocs
```

**Comment by brianjking** [comment]
Noticed I was missing a colon after each section header, still getting an error though. My new mkdocs.yml fie is below:

```yaml
site_name: DockDogs Scheduling
pages:
- Home: index.md
- Basics:
	- Basics and Introduction: getting-started/basics-and-introduction.md 
	- Status Icon Legend: getting-started/status-icon-legend.md
	- FAQS: getting-started/FAQs.md
- Reporting:
	- Reporting Basics: reporting/reporting-basics.md 
	- Creating A New Report: reporting/creating-a-new-report.md
	- Pre-Built Sponsors Report: reporting/pre-built-sponsors-report.md 
- Notifications:
	- Pre-Built Notifications: notifications/pre-built-notifications.md
	- Notification Basics: notifications/notifications-basics.md
theme: readthedocs
```

**Comment by waylan** [comment]
This error is being raised by the YAML parser. Therefore it is not a bug with MkDocs. A few possibilities:

1. Check that your YAML file is properly encoded as UTF-8. You will probably need to check the settings in the text editor that you are using.

2. The error is actually tripping up over a tab character (note the penultimate line of the error message: "found character '\t' that cannot start any token"). Try replacing each tab character with four spaces in your YAML doc and see if that resolves the problem. You might want to configure your text editor to do this automatically each time you type a tab. It makes for more consistent Markdown formatting as well.

The specifics of how to do either of the above will depend on the text editor you are using. You will need to consult the documentation for your editor of choice. And please, report back here with the results.

**Comment by waylan** [comment]
@brianjking I see you closed this issue. Does that mean you were able to resolve it? If so, how? It would help to know so that we have a clear answer if/when others encounter this problem. And it may help to provide better documentation.

**Comment by brianjking** [comment]
@waylan I followed both of your steps and it's working now. 

In regards to the UTF-8 encoding I went through and re-saved every markdown file used in ```docs``` as well as ````mkdocs.yml```` so I'm not sure if it was one or all of these that was a problem, however, I'm happy to report that it's working now.

Thanks for the prompt support!
