### ISSUE TITLE
Test are failing with python3.5

### ISSUE THREAD

**Issue by williamjmorenor** [mkdocs/mkdocs#751]
Hi

I want to report than test are failing with python3.5

Full log is here
https://kojipkgs.fedoraproject.org//work/tasks/4427/11844427/build.log

**Comment by waylan** [comment]
I can confirm this as well. The relevant bits from the tests:

```
$ tox -e py35-min-req
GLOB sdist-make: /home/waylan/code/mkdocs/setup.py
py35-min-req create: /home/waylan/code/mkdocs/.tox/py35-min-req
py35-min-req installdeps: -rrequirements/project-min.txt, -rrequirements/test.txt
py35-min-req inst: /home/waylan/code/mkdocs/.tox/dist/mkdocs-0.15.0.dev0.zip
py35-min-req installed: certifi==2015.9.6.2,click==4.0,coverage==4.0.2,flake8==2.5.0,Jinja2==2.7.1,livereload==2.3.2,Markdown==2.5,MarkupSafe==0.23,mccabe==0.3.1,mkdocs==0.15.0.dev0,mkdocs-bootstrap==0.1.1,mkdocs-bootswatch==0.1.0,mock==1.0.1,nose==1.3.7,pep8==1.5.7,pyflakes==1.0.0,PyYAML==3.10,tornado==4.1,wheel==0.24.0
py35-min-req runtests: PYTHONHASHSEED='1147804715'
py35-min-req runtests: commands[0] | /home/waylan/code/mkdocs/.tox/py35-min-req/bin/nosetests --with-coverage --cover-package mkdocs mkdocs
..............................................................................................................................................FFF....F.......
======================================================================
FAIL: test_content_parser (mkdocs.tests.search_tests.SearchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/waylan/code/mkdocs/mkdocs/tests/search_tests.py", line 35, in test_content_parser
    title="Title"
AssertionError: Lists differ: [<mkdocs.search.ContentSection object at 0x7fe466d2e710>] != [<mkdocs.search.ContentSection object at 0x7fe466d2e5c0>]

First differing element 0:
<mkdocs.search.ContentSection object at 0x7fe466d2e710>
<mkdocs.search.ContentSection object at 0x7fe466d2e5c0>

- [<mkdocs.search.ContentSection object at 0x7fe466d2e710>]
?                                                     ^^

+ [<mkdocs.search.ContentSection object at 0x7fe466d2e5c0>]
?                                                     ^^


======================================================================
FAIL: test_content_parser_content_before_header (mkdocs.tests.search_tests.SearchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/waylan/code/mkdocs/mkdocs/tests/search_tests.py", line 59, in test_content_parser_content_before_header
    title="Title"
AssertionError: Lists differ: [<mkdocs.search.ContentSection object at 0x7fe466d2e6d8>] != [<mkdocs.search.ContentSection object at 0x7fe466d2e748>]

First differing element 0:
<mkdocs.search.ContentSection object at 0x7fe466d2e6d8>
<mkdocs.search.ContentSection object at 0x7fe466d2e748>

- [<mkdocs.search.ContentSection object at 0x7fe466d2e6d8>]
?                                                     ^^

+ [<mkdocs.search.ContentSection object at 0x7fe466d2e748>]
?                                                     ^^


======================================================================
FAIL: test_content_parser_no_id (mkdocs.tests.search_tests.SearchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/waylan/code/mkdocs/mkdocs/tests/search_tests.py", line 47, in test_content_parser_no_id
    title="Title"
AssertionError: Lists differ: [<mkdocs.search.ContentSection object at 0x7fe466d2e668>] != [<mkdocs.search.ContentSection object at 0x7fe466d2e5c0>]

First differing element 0:
<mkdocs.search.ContentSection object at 0x7fe466d2e668>
<mkdocs.search.ContentSection object at 0x7fe466d2e5c0>

- [<mkdocs.search.ContentSection object at 0x7fe466d2e668>]
?                                                     ^^^

+ [<mkdocs.search.ContentSection object at 0x7fe466d2e5c0>]
?                                                     ^^^


======================================================================
FAIL: test_entityref (mkdocs.tests.toc_tests.TableOfContentsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/waylan/code/mkdocs/mkdocs/tests/toc_tests.py", line 134, in test_entityref
    self.assertEqual(str(toc).strip(), expected)
AssertionError: 'Heading & 1 - #heading-1\n    Heading > 2 - #headi[34 chars]ng-3' != 'Heading &amp; 1 - #heading-1\n    Heading &gt; 2 -[44 chars]ng-3'
- Heading & 1 - #heading-1
+ Heading &amp; 1 - #heading-1
?          ++++
-     Heading > 2 - #heading-2
?             ^
+     Heading &gt; 2 - #heading-2
?             ^^^^
-         Heading < 3 - #heading-3?                 ^
+         Heading &lt; 3 - #heading-3?                 ^^^^
```

and 

```
$ tox -e py35-unittests
GLOB sdist-make: /home/waylan/code/mkdocs/setup.py
py35-unittests inst-nodeps: /home/waylan/code/mkdocs/.tox/dist/mkdocs-0.15.0.dev0.zip
py35-unittests installed: click==5.1,coverage==4.0.2,flake8==2.5.0,Jinja2==2.8,livereload==2.4.0,Markdown==2.6.4,MarkupSafe==0.23,mccabe==0.3.1,mkdocs==0.15.0.dev0,mkdocs-bootstrap==0.1.1,mkdocs-bootswatch==0.1.0,mock==1.0.1,nose==1.3.7,pep8==1.5.7,pyflakes==1.0.0,PyYAML==3.11,six==1.10.0,tornado==4.3,wheel==0.24.0
py35-unittests runtests: PYTHONHASHSEED='1220622584'
py35-unittests runtests: commands[0] | /home/waylan/code/mkdocs/.tox/py35-unittests/bin/nosetests --with-coverage --cover-package mkdocs mkdocs
..............................................................................................................................................FFF....F.......
======================================================================
FAIL: test_content_parser (mkdocs.tests.search_tests.SearchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/waylan/code/mkdocs/mkdocs/tests/search_tests.py", line 35, in test_content_parser
    title="Title"
AssertionError: Lists differ: [<mkdocs.search.ContentSection object at 0x7f615fb77898>] != [<mkdocs.search.ContentSection object at 0x7f615fb777f0>]

First differing element 0:
<mkdocs.search.ContentSection object at 0x7f615fb77898>
<mkdocs.search.ContentSection object at 0x7f615fb777f0>

- [<mkdocs.search.ContentSection object at 0x7f615fb77898>]
?                                                     ^^^

+ [<mkdocs.search.ContentSection object at 0x7f615fb777f0>]
?                                                     ^^^


======================================================================
FAIL: test_content_parser_content_before_header (mkdocs.tests.search_tests.SearchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/waylan/code/mkdocs/mkdocs/tests/search_tests.py", line 59, in test_content_parser_content_before_header
    title="Title"
AssertionError: Lists differ: [<mkdocs.search.ContentSection object at 0x7f615fb77898>] != [<mkdocs.search.ContentSection object at 0x7f615fb777f0>]

First differing element 0:
<mkdocs.search.ContentSection object at 0x7f615fb77898>
<mkdocs.search.ContentSection object at 0x7f615fb777f0>

- [<mkdocs.search.ContentSection object at 0x7f615fb77898>]
?                                                     ^^^

+ [<mkdocs.search.ContentSection object at 0x7f615fb777f0>]
?                                                     ^^^


======================================================================
FAIL: test_content_parser_no_id (mkdocs.tests.search_tests.SearchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/waylan/code/mkdocs/mkdocs/tests/search_tests.py", line 47, in test_content_parser_no_id
    title="Title"
AssertionError: Lists differ: [<mkdocs.search.ContentSection object at 0x7f615fb77fd0>] != [<mkdocs.search.ContentSection object at 0x7f615fb777f0>]

First differing element 0:
<mkdocs.search.ContentSection object at 0x7f615fb77fd0>
<mkdocs.search.ContentSection object at 0x7f615fb777f0>

- [<mkdocs.search.ContentSection object at 0x7f615fb77fd0>]
?                                                      -

+ [<mkdocs.search.ContentSection object at 0x7f615fb777f0>]
?                                                     +


======================================================================
FAIL: test_entityref (mkdocs.tests.toc_tests.TableOfContentsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/waylan/code/mkdocs/mkdocs/tests/toc_tests.py", line 134, in test_entityref
    self.assertEqual(str(toc).strip(), expected)
AssertionError: 'Heading & 1 - #heading-1\n    Heading > 2 - #headi[34 chars]ng-3' != 'Heading &amp; 1 - #heading-1\n    Heading &gt; 2 -[44 chars]ng-3'
- Heading & 1 - #heading-1
+ Heading &amp; 1 - #heading-1
?          ++++
-     Heading > 2 - #heading-2
?             ^
+     Heading &gt; 2 - #heading-2
?             ^^^^
-         Heading < 3 - #heading-3?                 ^
+         Heading &lt; 3 - #heading-3?                 ^^^^
```

All other tests pass. As far as I can tell the "min-req" and "unititests" are both the same set of tests (not sure why they both exist) so that means a total of four tests are failing which appear to be caused by, at most, two separate issues (3 of the four are clearly repeats of the same issue).

**Comment by waylan** [comment]
In case it wasn't obvious, to runt he above mentioned tests, I made the following changes to the `tox.ini` file first:

```diff
diff --git a/tox.ini b/tox.ini
index d042476..d271241 100644
--- a/tox.ini
+++ b/tox.ini
@@ -1,17 +1,17 @@
 [tox]
 envlist =
-    py{26,27,33,34}-{unittests,integration,min-req},
+    py{26,27,33,34,35}-{unittests,integration,min-req},
     flake8
 
 [testenv]
 passenv = LANG
 deps=
-    py{26,27,33,34,py,py3}-{unittests,integration}: -rrequirements/project.txt
-    py{26,27,33,34,py,py3}-min-req: -rrequirements/project-min.txt
-    py{26,27,33,34,py,py3}-{unittests,min-req}: -rrequirements/test.txt
+    py{26,27,33,34,35,py,py3}-{unittests,integration}: -rrequirements/project.t
+    py{26,27,33,34,35,py,py3}-min-req: -rrequirements/project-min.txt
+    py{26,27,33,34,35,py,py3}-{unittests,min-req}: -rrequirements/test.txt
 commands=
-    py{26,27,33,34,py,py3}-{unittests,min-req}: {envbindir}/nosetests --with-co
-    py{26,27,33,34,py,py3}-integration: {envpython} -m mkdocs.tests.integration
+    py{26,27,33,34,35,py,py3}-{unittests,min-req}: {envbindir}/nosetests --with
+    py{26,27,33,34,35,py,py3}-integration: {envpython} -m mkdocs.tests.integrat
 
 [testenv:flake8]
 deps=-rrequirements/test.txt
```

**Comment by waylan** [comment]
Ok, so I'm working through the one issue (regarding entities) and this is what I found:

```py
Python 3.5.0 (default, Sep 17 2015, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
>>> t = '''#Heading & 1
... ## Heading > 2
... ### Heading < 3
... '''
>>> md = markdown.Markdown(extensions=['toc'])
>>> md.convert(t)
'<h1 id="heading-1">Heading &amp; 1</h1>\n<h2 id="heading-2">Heading &gt; 2</h2>\n<h3 id="heading-3">Heading &lt; 3</h3>'
>>> md.toc
'<div class="toc">\n<ul>\n<li><a href="#heading-1">Heading &amp; 1</a><ul>\n<li><a href="#heading-2">Heading &gt; 2</a><ul>\n<li><a href="#heading-3">Heading &lt; 3</a></li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</div>\n'
>>> from mkdocs import toc
>>> str(toc.TableOfContents(md.toc))
'Heading & 1 - #heading-1\n    Heading > 2 - #heading-2\n        Heading < 3 - #heading-3\n'
```

In other python versions that last line returns:

```py
'Heading &amp; 1 - #heading-1\n    Heading &gt; 2 - #heading-2\n        Heading &lt; 3 - #heading-3\n'
```

Notice the HTML entities are retained everywhere except Python 3.5. For some reason they are converted back to the characters they represent in `mkdocs.tox.TableOfContents` in Python 3.5.

**Comment by facelessuser** [comment]
https://docs.python.org/3/library/html.parser.html#html.parser.HTMLParser

Looks like convert_charrefs is now True by default.  This is probably what is screwing things up.  It was added in 3.4 and then set to True in 3.5.

**Comment by waylan** [comment]
Yeah, I just found that. Given it was added in 3.4, we can't just set it to False without a few extra hoops. Annoying.

**Comment by facelessuser** [comment]
I can't understand why the change to True, but at least we know what it is.

**Comment by d0ugal** [comment]
Thanks :)
