### ISSUE TITLE
Struggling with multilevel navigation

### ISSUE THREAD

**Issue by JayHoltslander** [mkdocs/mkdocs#788]
Trying to get Multilevel navigation working and having baffling and frustrating problems.

With this YAML:
````
pages:
- Home: 'index.md'
- Wordpress: 'wordpress/index.md'
- 01_login: 'wordpress/01_login/index.md'
````
Everything works fine. 
When following [these](http://www.mkdocs.org/user-guide/writing-your-docs/) directions for making subsections, so that I end up with this YAML.
````
pages:
- Home: 'index.md'
- Wordpress: 'wordpress/index.md'
	- 01_login: 'wordpress/01_login/index.md'
````

The moment I save my file I get the following error:

>[E 160108 11:11:06 ioloop:629] Exception in callback <bound method type.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/ioloop.py", line 1039, in _run
        return self.callback()
      File "/Library/Python/2.7/site-packages/livereload/handlers.py", line 65, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/Library/Python/2.7/site-packages/livereload/watcher.py", line 72, in examine
        func and func()
      File "/Library/Python/2.7/site-packages/mkdocs/serve.py", line 71, in builder
        theme=theme,
      File "/Library/Python/2.7/site-packages/mkdocs/config/base.py", line 143, in load_config
        cfg.load_file(config_file)
      File "/Library/Python/2.7/site-packages/mkdocs/config/base.py", line 96, in load_file
        return self.load_dict(utils.yaml_load(config_file))
      File "/Library/Python/2.7/site-packages/mkdocs/utils/__init__.py", line 58, in yaml_load
        return yaml.load(source, Loader)
      File "/Library/Python/2.7/site-packages/yaml/__init__.py", line 71, in load
        return loader.get_single_data()
      File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
        node = self.get_single_node()
      File "/Library/Python/2.7/site-packages/yaml/composer.py", line 36, in get_single_node
        document = self.compose_document()
      File "/Library/Python/2.7/site-packages/yaml/composer.py", line 55, in compose_document
        node = self.compose_node(None, None)
      File "/Library/Python/2.7/site-packages/yaml/composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/Library/Python/2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "/Library/Python/2.7/site-packages/yaml/composer.py", line 82, in compose_node
        node = self.compose_sequence_node(anchor)
      File "/Library/Python/2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
        node.value.append(self.compose_node(node, index))
      File "/Library/Python/2.7/site-packages/yaml/composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/Library/Python/2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
        while not self.check_event(MappingEndEvent):
      File "/Library/Python/2.7/site-packages/yaml/parser.py", line 98, in check_event
        self.current_event = self.state()
      File "/Library/Python/2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
        if self.check_token(KeyToken):
      File "/Library/Python/2.7/site-packages/yaml/scanner.py", line 116, in check_token
        self.fetch_more_tokens()
      File "/Library/Python/2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
        % ch.encode('utf-8'), self.get_mark())
    ScannerError: while scanning for the next token
    found character '\t' that cannot start any token
      in "/Users/jholtslander/Desktop/mkdocs-project/mkdocs.yml", line 7, column 1

I examined the [MkDocs source](https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml) and noticed that unlike [the docs](http://www.mkdocs.org/user-guide/writing-your-docs/) show, the paths are not wrapped with any ticks. So I tried my code as:

````
pages:
- Home: index.md
- Wordpress: wordpress/index.md
	- 01_login: wordpress/01_login/index.md
```` 
Which results in the same error.

I googled ``found character '\t' that cannot start any token`` and discovered that tabs shouldn't be used in YAML. (News to me) So I tried using spaces. 1 space, 2 spaces, 3 spaces all got errors in regards to the line and column number of the space until I hit 4 spaces. at which point I have this YAML

````
pages:
- Home: index.md
- Wordpress: wordpress/index.md
    - 01_login: wordpress/01_login/index.md
````

Suddenly I get

>ScannerError: mapping values are not allowed here
      in "/Users/jholtslander/Desktop/mkdocs-project/mkdocs.yml", line 7, column 15

which refers to the colon.

I'm lost now. wtf.

**Comment by facelessuser** [comment]
You are having problems with the YAML syntax.  Maybe it will help to show you what is actually happening:

As you can see what you are doing translates into nonsense as you try to assign an array and string to `Wordpress`.

```
pages: [{Home: index.md}, {Wordpress: index.md [{01_login: wordpress/01_login/index.md}]}]
```

In the docs you can see that `User Guide` only has an array assigned to it:

```yaml
- User Guide:
    - 'Writing your docs': 'user-guide/writing-your-docs.md'
    - 'Styling your docs': 'user-guide/styling-your-docs.md'
```

Not a string and array:

```yaml
- User Guide: 'I can't do this!'
    - 'Writing your docs': 'user-guide/writing-your-docs.md'
    - 'Styling your docs': 'user-guide/styling-your-docs.md'
```

**Comment by JayHoltslander** [comment]
I did try that as well but didn't include that in my above post. I will try it again in case I made a typo.
