### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'meta' is undefined

### ISSUE THREAD

**Issue by ccpereirabt** [mkdocs/mkdocs#864]
Trying to use bootstrap theme from mkdocs. But when I copy the theme to my project to bitbucket it gives me a **jinja2.exceptions.UndefinedError: 'meta' is undefined** error. I've tried the patch #368 and patch #244 

Currently, inside my project is:
- INSTALL (md files)
- custom (theme)
- build.py
- build_tests.py
- build_test.py 
- config.py
- index.md
- index.rst
- mkdocs.yml

**.yml entry**

```
site_name: The website
theme_dir: ./custom
```

**Error**

```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/checkouts/latest/_build/html 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/mkdocs/__main__.py", line 137, in build_command
    ), clean_site_dir=clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 289, in build
    build_pages(config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 235, in build_pages
    if not build_template('search.html', env, config, site_navigation):
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 148, in build_template
    output_content = template.render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/mkdocs/themes/readthedocs/search.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/checkouts/latest/custom/base.html", line 48, in top-level template code
    <div class="col-md-9" role="main">{% include "content.html" %}</div>
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/checkouts/latest/custom/content.html", line 1, in top-level template code
    {% if meta.source %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/claudiatestingprojectkentico/envs/latest/local/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'meta' is undefined
```

**Comment by d0ugal** [comment]
I don't think customising the theme will work well on ReadTheDocs, they do some special changes to force the readthedocs theme. This means that you are getting a **merge** of both the readthedocs theme and whatever custom theme you are adding.

I can only see two ways to make this work, make the custom theme compatible with the readthedocs theme by matching the same filenames or adding empty files that overwrite and essentially delete the readthedocs theme. Both options are horrible any somewhat hacky.

ReadTheDocs need to make changes on their end to allow users to use other themes. This would be the third option I guess.
