### ISSUE TITLE
Question: What is the availability of meta variables

### ISSUE THREAD

**Issue by anantshri** [mkdocs/mkdocs#920]
This is more of a question around mkdocs themes whats the availability of meta variables.

I tried editing the base.html for default mkdocs theme but looks like meta variables are not available outside on {{ block content }} section

I wanted to add a feature in theme where specific page could include its own set of js and css files based on a meta keyword on that file. Any suggestions appreciated.

**Comment by waylan** [comment]
> looks like meta variables are not available outside on `{{ block content }}` section

What makes you say that?  Run the build command with `--verbose` and see which page is generating your error. My guess is that it is the `404.html` page, which does not get passed a page context, only a global context. Of course, the `{{ block content }}` section is override by the `404.html` template, but anywhere outside of that section, all page specific context variables are tested for existence before use. For example: `{% if current_page and current_page.is_homepage %}...`. If you aren't doing that, then you will get an error for the `404.html` template. And as any template without a page specific context (like `404.html`) will never need any page specific variables, and all Markdown pages will have a page specific context, everything will still work correctly.

If that's not your problem, then you'll need to provide more specific info regarding the problem/error you are getting.

**Comment by anantshri** [comment]
Let me give you an exact example.

https://github.com/anantshri/mkdocs-reloaded/blob/master/mkdocs-reloaded/content.html#L8 This is the code block i wanted to use. Its working when its in content.html or after {{ block content }}

If i add this code block anywhere outside of block content on base.html page i get this error message
code block added
```
{% if meta.mindmap %}

{% endif %}
```
```
INFO    -  Building documentation...
DEBUG   -  Loading configuration file: /Work/Workspace/mkdocs-reloaded/mkdocs.yml
DEBUG   -  Config value: 'site_name' = u'MkDocs Reloaded Theme'
DEBUG   -  Config value: 'extra' = <mkdocs.config.config_options.SubConfig object at 0x10f483d10>
DEBUG   -  Config value: 'extra_javascript' = []
DEBUG   -  Config value: 'site_favicon' = None
DEBUG   -  Config value: 'extra_css' = []
DEBUG   -  Config value: 'theme_dir' = [u'/Work/Workspace/mkdocs-reloaded/mkdocs-reloaded', u'/usr/local/lib/python2.7/site-packages/mkdocs/assets/search']
DEBUG   -  Config value: 'config_file_path' = u'/Work/Workspace/mkdocs-reloaded/mkdocs.yml'
DEBUG   -  Config value: 'copyright' = u'Copyright &copy; <a href="https://anantshri.info">Anant Shrivastava</a>'
DEBUG   -  Config value: 'remote_branch' = u'gh-pages'
DEBUG   -  Config value: 'site_url' = u'http://anantshri.github.io/mkdocs-reloaded/'
DEBUG   -  Config value: 'use_directory_urls' = True
DEBUG   -  Config value: 'strict' = False
DEBUG   -  Config value: 'theme' = u'mkdocs'
DEBUG   -  Config value: 'mkdocs_templates' = u'/usr/local/lib/python2.7/site-packages/mkdocs/templates'
DEBUG   -  Config value: 'include_nav' = True
DEBUG   -  Config value: 'docs_dir' = u'/Work/Workspace/mkdocs-reloaded/docs'
DEBUG   -  Config value: 'repo_name' = u'GitHub'
DEBUG   -  Config value: 'site_dir' = u'/Work/Workspace/mkdocs-reloaded/site'
DEBUG   -  Config value: 'dev_addr' = u'127.0.0.1:8000'
DEBUG   -  Config value: 'repo_url' = u'https://github.com/mkdocs/mkdocs-bootstrap'
DEBUG   -  Config value: 'remote_name' = u'origin'
DEBUG   -  Config value: 'pages' = [u'index.md', u'mindmap.md', {u'Second level': [u'second_level/third.md']}]
DEBUG   -  Config value: 'markdown_extensions' = [u'meta', u'toc', u'tables', u'fenced_code']
DEBUG   -  Config value: 'include_next_prev' = False
DEBUG   -  Config value: 'site_description' = u'MkDocs Reloaded Theme'
DEBUG   -  Config value: 'extra_templates' = []
DEBUG   -  Config value: 'site_author' = u'Anant Shrivastava'
DEBUG   -  Config value: 'google_analytics' = None
DEBUG   -  Config value: 'mdx_configs' = {}
INFO    -  Cleaning site directory
DEBUG   -  Copying static assets from theme: /usr/local/lib/python2.7/site-packages/mkdocs/assets/search
DEBUG   -  Copying static assets from theme: /Work/Workspace/mkdocs-reloaded/mkdocs-reloaded
DEBUG   -  Copying static assets from the docs dir.
DEBUG   -  Building markdown pages.
DEBUG   -  Building template: 404.html
[E 160501 05:13:12 ioloop:629] Exception in callback <bound method type.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 1039, in _run
        return self.callback()
      File "/usr/local/lib/python2.7/site-packages/livereload/handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/usr/local/lib/python2.7/site-packages/livereload/watcher.py", line 73, in examine
        func and func()
      File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 74, in builder
        build(config, live_server=True, clean_site_dir=True)
      File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 289, in build
        build_pages(config)
      File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 233, in build_pages
        build_template('404.html', env, config, site_navigation)
      File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 148, in build_template
        output_content = template.render(context)
      File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
        return self.environment.handle_exception(exc_info, True)
      File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/Work/Workspace/mkdocs-reloaded/mkdocs-reloaded/404.html", line 1, in top-level template code
        {% extends "base.html" %}
      File "/Work/Workspace/mkdocs-reloaded/mkdocs-reloaded/base.html", line 23, in top-level template code
        {% if meta.mindmap %}
      File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
        return getattr(obj, attribute)
    UndefinedError: 'meta' is undefined
```

 By the looks of it you seem to be right its pointing to 404.html 

So what am i doing wrong and how can i correct it.

I bascially need to add the check somewhere https://github.com/anantshri/mkdocs-reloaded/blob/master/mkdocs-reloaded/base.html#L17 to ensure custom page specific css can be loaded and simmilarly towards the bottom portion when we have js.

**Comment by waylan** [comment]
Did you try my suggestion:

    {% if current_page and meta.mindmap %}

    {% endif %}

That's how page specific variables are used everywhere outside of block content in the built-in themes.

**Comment by anantshri** [comment]
Ah not sure how but this skipped my eyes when i read the response last time. I can confirm this seems to be working just fine. Thanks for the quick help. closing the issue
