### ISSUE TITLE
can not use date time format as page name

### ISSUE THREAD

**Issue by bbili** [mkdocs/mkdocs#940]
I have pages like this:

```
pages:
- Home: index.md
- Daily:
    - 2016-05-17: daily/2016-05-17.md
```

When I run `mkdocs serve`, got errors:

Error comes from `generate_search_index`:

code - https://github.com/mkdocs/mkdocs/blob/3e10e014b63dfcc85a30e6198da00677f7eefb24/mkdocs/search.py#L93

```
  File "/Library/Python/2.7/site-packages/mkdocs/commands/build.py", line 257, in build_pages
    search_index = search_index.generate_search_index()
  File "/Library/Python/2.7/site-packages/mkdocs/search.py", line 93, in generate_search_index
    return json.dumps(page_dicts, sort_keys=True, indent=4)
```

Complete logs:

```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mkdocs/__main__.py", line 115, in serve_command
    livereload=livereload,
  File "/Library/Python/2.7/site-packages/mkdocs/commands/serve.py", line 78, in serve
    config = builder()
  File "/Library/Python/2.7/site-packages/mkdocs/commands/serve.py", line 74, in builder
    build(config, live_server=True, clean_site_dir=True)
  File "/Library/Python/2.7/site-packages/mkdocs/commands/build.py", line 289, in build
    build_pages(config)
  File "/Library/Python/2.7/site-packages/mkdocs/commands/build.py", line 257, in build_pages
    search_index = search_index.generate_search_index()
  File "/Library/Python/2.7/site-packages/mkdocs/search.py", line 93, in generate_search_index
    return json.dumps(page_dicts, sort_keys=True, indent=4)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.date(2016, 5, 17) is not JSON serializable

```

**Comment by bbili** [comment]
page name like `2016 05 17` is fine.

**Comment by ci5er** [comment]
Have you tried following the documentation and putting single quotes around your proposed page names and associated filenames?

http://www.mkdocs.org/user-guide/writing-your-docs/

**Comment by d0ugal** [comment]
Yup, using quotes as @ci5er suggested will fix this.
