### ISSUE TITLE
Livereload using the wrong port

### ISSUE THREAD

**Issue by jayfk** [mkdocs/mkdocs#959]
When started with a non custom port like `mkdocs serve -a 0.0.0.0:5000`, the function in `livereload.js` still uses the default port `8000`.

**Comment by d0ugal** [comment]
Interesting. I'm not sure how that happens. We do pass the port to livereload, so I suspect this might be a livereload bug and not something wrong with MkDocs.

https://github.com/mkdocs/mkdocs/blob/master/mkdocs/commands/serve.py#L27

**Comment by jayfk** [comment]
I did some further testing. The created websocket works, but something is polling `/livereload` on the wrong port.

Could you point me to the JS library you are using for further investigation?

**Comment by d0ugal** [comment]
We use python-livereload. https://github.com/lepture/python-livereload and it vendors livereload.js. https://github.com/lepture/python-livereload/tree/master/livereload/vendors - originally from https://github.com/livereload/livereload-js

I would guess the bug is in python-livereload, but I am not sure at all.

**Comment by laythun** [comment]
```
INFO    -  Building documentation...
[E 160609 14:25:24 ioloop:629] Exception in callback <bound method type.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/tornado/ioloop.py", line 1039, in _run
        return self.callback()
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/livereload/handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/livereload/watcher.py", line 73, in examine
        func and func()
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 71, in builder
        theme=theme,
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/mkdocs/config/base.py", line 147, in load_config
        cfg.load_file(config_file)
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/mkdocs/config/base.py", line 100, in load_file
        return self.load_dict(utils.yaml_load(config_file))
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/mkdocs/utils/__init__.py", line 70, in yaml_load
        return yaml.load(source, Loader)
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/yaml/__init__.py", line 69, in load
        loader = Loader(stream)
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/yaml/loader.py", line 34, in __init__
        Reader.__init__(self, stream)
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/yaml/reader.py", line 85, in __init__
        self.determine_encoding()
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/yaml/reader.py", line 124, in determine_encoding
        self.update_raw()
      File "/home/vagrant/envs/mkdocs/local/lib/python2.7/site-packages/yaml/reader.py", line 178, in update_raw
        data = self.stream.read(size)
    ValueError: I/O operation on closed file
```

Not sure if this is the same error (no details have been provided)

**Comment by waylan** [comment]
@laythun I am pretty certain that the error you are getting is not related. Looks more like something related to #741 which was fixed some time ago. Are you running the most recent release? Please follow up in a new issue.

**Comment by d0ugal** [comment]
I'm going to close this, I don't think there is anything we can do to fix it. Please let me know if I am wrong about that.
