### ISSUE TITLE
Live reload fails when modifying and saving a file

### ISSUE THREAD

**Issue by laythun** [mkdocs/mkdocs#960]
When editing a file and saving while the server is running livehandler errors out.

```
(api-documentation)vagrant@trusty64:~/conv_apps/api-documentation$ mkdocs --version
mkdocs, version 0.15.3
```

```
[I 160609 15:25:49 handlers:61] Start detecting changes
INFO    -  Building documentation...
[E 160609 15:26:11 ioloop:629] Exception in callback <bound method type.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/tornado/ioloop.py", line 1039, in _run
        return self.callback()
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/livereload/handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/livereload/watcher.py", line 73, in examine
        func and func()
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 71, in builder
        theme=theme,
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/mkdocs/config/base.py", line 147, in load_config
        cfg.load_file(config_file)
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/mkdocs/config/base.py", line 100, in load_file
        return self.load_dict(utils.yaml_load(config_file))
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/mkdocs/utils/__init__.py", line 70, in yaml_load
        return yaml.load(source, Loader)
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/yaml/__init__.py", line 69, in load
        loader = Loader(stream)
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/yaml/loader.py", line 34, in __init__
        Reader.__init__(self, stream)
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/yaml/reader.py", line 85, in __init__
        self.determine_encoding()
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/yaml/reader.py", line 124, in determine_encoding
        self.update_raw()
      File "/home/vagrant/envs/api-documentation/local/lib/python2.7/site-packages/yaml/reader.py", line 178, in update_raw
        data = self.stream.read(size)
    ValueError: I/O operation on closed file
```

**Comment by waylan** [comment]
Thanks for the report. I'm assuming this is related to #741. Will need to confirm.

**Comment by waylan** [comment]
Which OS are you using and what file is being edited (the config file, a Markdown page, or something else)? Also, do you have any unusual config options set?

**Comment by laythun** [comment]
OS: Ubuntu + Mac (happens on both)
It happens when i'm editing a markdown page

```
vagrant@trusty64:~/conv_apps/api-documentation$ ls api-documentation/
api-landing-page.yml  docs  site
vagrant@trusty64:~/conv_apps/api-documentation$ ls api-documentation/docs/
index.md

site_name: "API docs"
pages:
  - "index.md"
theme: readthedocs
site_description: "API docs"
site_author: "Daniel Inniss"
site_dir: "api-documentation/site"
docs_dir: "api-documentation/docs"
dev_addr: "0.0.0.0:8888"
copyright: "2016"
```

**Comment by waylan** [comment]
I can't help but notice that the paths assigned to `site_dir` and `docs_dir` are not relative to the YAML config file. Although I see that you have all documentation related stuff within a `api-documentation` subdir. I'm guessing you run the build/serve commands from the parent `conv_apps` dir. I'm just guessing (will test later), but that may be the problem. Generally we test for and expect that the commands would be run from the same dir as the YAML file, which would require all paths in the config to be relative to that file location. Of course, we should support other configs, its just that we don't use them so we may miss a few edge cases.

**Comment by laythun** [comment]
the yaml file is in the same directory as the docs and site directories, as far as the doco says i can next the actual markdown files anywhere?
